/* Hikmah Noor — site section chrome localization, part 2.
 * Hadees / Seerah / History / Meanings hubs + details in en/hi/ur/ar.
 * English strings are byte-identical to current pages.
 */
export function secUI2(locale: string, map: Record<string, any>): any {
  return (map as any)[locale] ?? map.en;
}

export const HADEES_UI: Record<string, any> = {
  en: {
    crumb: 'Hadees',
    hubTitle: 'Hadees Library — 40 for Children + 40 of Imam Nawawi + 40 Sahih Selections in Arabic, Urdu & English',
    hubDesc: 'All 120 hadees: 40 short hadees for kids, the 40 Hadith of Imam Nawawi, plus 40 Sahih selections on worship, Quran, family and character — Arabic, Urdu tarjuma, English meaning, lesson and source. Each hadees has its own page.',
    hubKw: 'hadees library, 40 hadees for children, 40 hadith nawawi, sahih bukhari muslim hadees, nawawi arbaeen in urdu, choti hadees in urdu, hadees in urdu, hadees in english, short hadith, arbaeen lil atfal, bachon ki hadees, niyat wali hadees',
    hubFaq: [
      { q: 'How many hadees are in this library?', a: '120 total: 40 short sahih hadees for children in 8 sabaq (from Mufradat min Ahadith al-Arbaeen lil Atfal), the 40 Hadith of Imam Nawawi for adults, plus 40 Sahih selections on worship, Quran, family, finance, character and hope. Open any hadees for Arabic, Urdu, English, lesson and source.' },
      { q: 'Does every hadees have its own page?', a: 'Yes — each of the 120 hadees has a separate SEO page with Arabic text, transliteration, Urdu tarjuma, English meaning, lesson, narrator, grade, FAQ and its own keywords.' },
      { q: 'Are these hadees authentic?', a: 'Yes — only famous wordings from Sahih al-Bukhari and Sahih Muslim (Muttafaq Alayh) or Hasan (Tirmidhi, Abu Dawud, Nasai, Ibn Majah and others). Each page names its collection without invented numbers.' },
      { q: 'What is the 40 Hadith of Nawawi?', a: 'Imam Yahya al-Nawawi’s world-famous collection of 40 foundational hadith — intention, pillars, sincerity, worship and character. Start with hadees 1 (intentions) and read in order.' },
      { q: 'What are the Sahih Selections?', a: '40 famous Bukhari/Muslim hadees for adults in 3 parts — worship & prayer, Quran/dhikr/dua, and character & society — each with Arabic, Urdu, English, lesson and source.' },
    ],
    hubH1: 'Hadees Library',
    hubSub: '40 short hadees for children, the 40 Hadith of Imam Nawawi, plus 40 Sahih selections — Arabic, Urdu tarjuma, English meaning and lessons. Tap any hadees for its own page.',
    searchPh: 'Search hadees — e.g. niyat, roza, gussa, saf…', filterPh: 'Filter 120 hadees — e.g. niyat, nawawi, roza, gussa…',
    badgeN: 'hadees', badge2: 'Kids + Nawawi + Sahih', badge3: 'Arabic + Urdu + English',
    secNawawi: '40 Hadith of Imam Nawawi', secNawawiSub: 'Foundations of faith, worship and character — for adults, in order.',
    sabaqL: 'Sabaq {n}', partL: 'Part {n}',
    detTitleSuffix: ' — Arabic, Urdu & English',
    badgeHadees: 'Hadees {n} of 40', alsoSearched: 'Also searched as:',
    lessonKids: 'Kids lesson', lessonL: 'Lesson', srcGradeL: 'Source & grade',
    fromL: 'From:', verifyL: 'Verify wording with a teacher; rulings differ — consult scholars.',
    relSame: 'Same lesson', relMore: 'More hadees', allHadees: 'All hadees',
    prevL: '← Previous hadees', nextL: 'Next hadees →',
    detFaqMean: 'What does "{a}" mean?', detFaqLes: 'What is the lesson of this hadees{kids}?', detFaqSrc: 'Where is this hadees from?',
    coll: {
      secT: 'Hadith Collections', secSub: 'Complete collections with full Arabic matn and English translation — browse by book, read in order.',
      countBadge: '{b} book · {t} hadith', bookOf: 'Book {n}', hadithOf: 'Hadith {n} of {t}',
      arabicL: 'Arabic matn', englishL: 'English translation', refL: 'Reference', provL: 'Source',
      studyT: 'Study version', studyD: 'Curated page with lesson, Urdu translation and FAQ.',
      readL: 'Read hadith {n}',
      prevL: '← Previous hadith', nextL: 'Next hadith →', backBookL: '← Back to book', backCollL: '← Collection',
      collTitle: '{name} — Full Collection in Arabic & English',
      collDesc: 'Read the complete {name} ({t} hadith) with full Arabic matn and English translation, in collection order.',
      bookTitle: '{name} — Read All {t} Hadith in Order',
      bookDesc: 'Browse all {t} hadith of {name}: full Arabic matn with English translation. Open any hadith for its own page.',
      entryTitle: '{short} Hadith {n} — Full Arabic Text & English Translation',
      faqWhatQ: 'Which collection is Hadith {n} from?',
      faqWhatA: 'Hadith {n} of {t} in the {name}, Book {b}. Shown with the verified Arabic matn and English translation.',
      faqFullQ: 'Where can I read the full collection?',
      faqFullA: 'Open the collection page to browse all {t} hadith in order, with the full Arabic matn and English translation.',
      faqLangQ: 'Which languages are shown?',
      faqLangA: 'The verified Arabic matn with the English translation. Urdu and Hindi pages show the same verified texts — no translations are invented.',
    },
  },
  ur: {
    crumb: 'حدیث',
    hubTitle: 'حدیث لائبریری — بچوں کے لیے 40 + امام نووی کی 40 + 40 صحیح منتخب',
    hubDesc: 'تمام 120 احادیث: بچوں کے لیے 40 مختصر، امام نووی کی 40، اور عبادت، قرآن، خاندان پر 40 صحیح منتخب — عربی، اردو ترجمہ، انگریزی مطلب، سبق اور حوالہ۔ ہر حدیث کا اپنا صفحہ۔',
    hubKw: 'حدیث لائبریری, بچوں کی 40 حدیثیں, چالیس نووی اردو میں, چھوٹی حدیث اردو میں, بخاری مسلم حدیث, نیت والی حدیث',
    hubFaq: [
      { q: 'اس لائبریری میں کتنی حدیثیں ہیں؟', a: '120 کل: 8 اسباق میں بچوں کے لیے 40 مختصر صحیح، بڑوں کے لیے امام نووی کی 40، اور عبادت، قرآن، خاندان پر 40 صحیح منتخب۔' },
      { q: 'کیا ہر حدیث کا اپنا صفحہ ہے؟', a: 'جی ہاں — 120 میں سے ہر ایک کا الگ صفحہ: عربی متن، تلفظ، اردو ترجمہ، انگریزی مطلب، سبق، راوی، درجہ۔' },
      { q: 'کیا یہ حدیثیں مستند ہیں؟', a: 'جی ہاں — صرف مشہور الفاظ صحیح بخاری و مسلم یا حسن درجے سے۔ ہر صفحہ بغیر گھڑے نمبروں کے مجموعے کا نام دیتا ہے۔' },
      { q: 'چالیس نووی کیا ہے؟', a: 'امام یحییٰ نووی کا عالمی مشہور 40 بنیادی حدیثوں کا مجموعہ — نیت، ارکان، اخلاص، عبادت۔ حدیث 1 سے شروع کرو۔' },
      { q: 'صحیح منتخب کیا ہیں؟', a: 'بڑوں کے لیے 3 حصوں میں 40 مشہور بخاری/مسلم حدیثیں — عبادت، قرآن/ذکر/دعا، اور اخلاق و معاشرت۔' },
    ],
    hubH1: 'حدیث لائبریری',
    hubSub: 'بچوں کے لیے 40 مختصر حدیثیں، امام نووی کی 40، اور 40 صحیح منتخب — عربی، اردو ترجمہ، انگریزی مطلب اور سبق۔ کسی بھی حدیث کا صفحہ کھولو۔',
    searchPh: 'حدیث تلاش کریں — مثلاً نیت، روزہ، غصہ…', filterPh: '120 حدیثیں چھانٹیں — مثلاً نیت، نووی، روزہ…',
    badgeN: 'حدیثیں', badge2: 'بچے + نووی + صحیح', badge3: 'عربی + اردو + انگریزی',
    secNawawi: 'امام نووی کی چالیس حدیثیں', secNawawiSub: 'ایمان، عبادت اور اخلاق کی بنیادیں — بڑوں کے لیے ترتیب سے۔',
    sabaqL: 'سبق {n}', partL: 'حصہ {n}',
    detTitleSuffix: ' — عربی، اردو و انگریزی',
    badgeHadees: 'حدیث {n} از 40', alsoSearched: 'اس نام سے بھی تلاش ہوتی ہے:',
    lessonKids: 'بچوں کا سبق', lessonL: 'سبق', srcGradeL: 'حوالہ و درجہ',
    fromL: 'ماخذ:', verifyL: 'الفاظ استاد سے تصدیق کرو؛ مسائل میں اختلاف ہے — علماء سے رجوع کرو۔',
    relSame: 'یہی سبق', relMore: 'مزید حدیثیں', allHadees: 'تمام حدیثیں',
    prevL: '← پچھلی حدیث', nextL: 'اگلی حدیث →',
    detFaqMean: '"{a}" کا مطلب کیا ہے؟', detFaqLes: 'اس حدیث{kids} کا سبق کیا ہے؟', detFaqSrc: 'یہ حدیث کہاں سے ہے؟',
    coll: {
      secT: 'حدیث کے مجموعے', secSub: 'مکمل مجموعے — مکمل عربی متن اور انگریزی ترجمے کے ساتھ، کتاب کے حساب سے پڑھو۔',
      countBadge: '{b} کتاب · {t} حدیث', bookOf: 'کتاب {n}', hadithOf: 'حدیث {n} از {t}',
      arabicL: 'عربی متن', englishL: 'انگریزی ترجمہ', refL: 'حوالہ', provL: 'ماخذ',
      studyT: 'مطالعاتی صفحہ', studyD: 'سبق، اردو ترجمہ اور سوالات کے ساتھ مرتب صفحہ۔',
      readL: 'حدیث {n} پڑھو',
      prevL: '← پچھلی حدیث', nextL: 'اگلی حدیث →', backBookL: '← کتاب پر واپس', backCollL: '← مجموعہ',
      collTitle: '{name} — مکمل مجموعہ عربی و انگریزی میں',
      collDesc: 'مکمل {name} ({t} حدیثیں) پڑھو — مکمل عربی متن اور انگریزی ترجمے کے ساتھ، ترتیب سے۔',
      bookTitle: '{name} — تمام {t} حدیثیں ترتیب سے',
      bookDesc: '{name} کی تمام {t} حدیثیں دیکھو: مکمل عربی متن مع انگریزی ترجمہ۔',
      entryTitle: '{short} حدیث {n} — مکمل عربی متن و انگریزی ترجمہ',
      faqWhatQ: 'حدیث {n} کس مجموعے سے ہے؟',
      faqWhatA: '{name} کی {t} میں سے حدیث {n}، کتاب {b}۔ مستند عربی متن اور انگریزی ترجمے کے ساتھ۔',
      faqFullQ: 'مکمل مجموعہ کہاں پڑھوں؟',
      faqFullA: 'مجموعے کا صفحہ کھولو — ترتیب سے تمام {t} حدیثیں، مکمل عربی متن اور انگریزی ترجمے کے ساتھ۔',
      faqLangQ: 'کون سی زبانیں دکھائی گئی ہیں؟',
      faqLangA: 'مستند عربی متن مع انگریزی ترجمہ۔ اردو اور ہندی صفحات پر وہی مستند متون ہیں — کوئی ترجمہ گھڑا نہیں گیا۔',
    },
  },
  hi: {
    crumb: 'हदीस',
    hubTitle: 'हदीस लाइब्रेरी — बच्चों हेतु 40 + इमाम नववी की 40 + 40 सहीह चयन',
    hubDesc: 'सभी 120 हदीसें: बच्चों हेतु 40 संक्षिप्त, इमाम नववी की 40, तथा उपासना, क़ुरान, परिवार पर 40 सहीह चयन — अरबी, उर्दू अनुवाद, अंग्रेज़ी अर्थ, शिक्षा और स्रोत। हर हदीस का अपना पृष्ठ।',
    hubKw: 'हदीस लाइब्रेरी, बच्चों हेतु 40 हदीसें, 40 हदीस नववी, सहीह बुख़ारी मुस्लिम हदीस, छोटी हदीस, नियत वाली हदीस',
    hubFaq: [
      { q: 'इस लाइब्रेरी में कितनी हदीसें हैं?', a: '120 कुल: 8 सबक़ में बच्चों हेतु 40 संक्षिप्त सहीह, बड़ों हेतु इमाम नववी की 40, तथा उपासना, क़ुरान, परिवार पर 40 सहीह चयन।' },
      { q: 'क्या हर हदीस का अपना पृष्ठ है?', a: 'हां — 120 में से हर एक का अलग पृष्ठ: अरबी, लिप्यंतरण, उर्दू अनुवाद, अंग्रेज़ी अर्थ, शिक्षा, कथावाचक, श्रेणी।' },
      { q: 'क्या ये हदीसें प्रामाणिक हैं?', a: 'हां — केवल प्रसिद्ध शब्द सहीह बुख़ारी व मुस्लिम या हसन श्रेणी से। हर पृष्ठ बिना गढ़े नंबरों के संग्रह का नाम देता है।' },
      { q: 'चालीस नववी क्या है?', a: 'इमाम यह्या नववी का विश्वप्रसिद्ध 40 बुनियादी हदीसों का संग्रह — नीयत, स्तंभ, निष्ठा, उपासना। हदीस 1 से आरंभ करो।' },
      { q: 'सहीह चयन क्या हैं?', a: 'बड़ों हेतु 3 भागों में 40 प्रसिद्ध बुख़ारी/मुस्लिम हदीसें — उपासना, क़ुरान/ज़िक्र/दुआ, और चरित्र व समाज।' },
    ],
    hubH1: 'हदीस लाइब्रेरी',
    hubSub: 'बच्चों हेतु 40 संक्षिप्त हदीसें, इमाम नववी की 40, तथा 40 सहीह चयन — अरबी, उर्दू अनुवाद, अंग्रेज़ी अर्थ और शिक्षाएं।',
    searchPh: 'हदीस खोजें — जैसे नियत, रोज़ा, गुस्सा…', filterPh: '120 हदीसें छांटें — जैसे नियत, नववी, रोज़ा…',
    badgeN: 'हदीसें', badge2: 'बच्चे + नववी + सहीह', badge3: 'अरबी + उर्दू + अंग्रेज़ी',
    secNawawi: 'इमाम नववी की चालीस हदीसें', secNawawiSub: 'आस्था, उपासना और चरित्र की नींवें — बड़ों हेतु क्रम से।',
    sabaqL: 'सबक़ {n}', partL: 'भाग {n}',
    detTitleSuffix: ' — अरबी, उर्दू व अंग्रेज़ी',
    badgeHadees: 'हदीस {n} / 40', alsoSearched: 'इन नामों से भी खोजा जाता है:',
    lessonKids: 'बच्चों की शिक्षा', lessonL: 'शिक्षा', srcGradeL: 'स्रोत व श्रेणी',
    fromL: 'स्रोत:', verifyL: 'शब्द शिक्षक से सत्यापित करो; नियमों में मतभेद है — विद्वानों से पूछो।',
    relSame: 'वही सबक़', relMore: 'और हदीसें', allHadees: 'सभी हदीसें',
    prevL: '← पिछली हदीस', nextL: 'अगली हदीस →',
    detFaqMean: '"{a}" का अर्थ क्या है?', detFaqLes: 'इस हदीस{kids} की शिक्षा क्या है?', detFaqSrc: 'यह हदीस कहां से है?',
    coll: {
      secT: 'हदीस संग्रह', secSub: 'पूर्ण संग्रह — पूर्ण अरबी मूलपाठ और अंग्रेज़ी अनुवाद सहित, पुस्तक अनुसार पढ़ें।',
      countBadge: '{b} पुस्तक · {t} हदीस', bookOf: 'पुस्तक {n}', hadithOf: 'हदीस {n} / {t}',
      arabicL: 'अरबी मूलपाठ', englishL: 'अंग्रेज़ी अनुवाद', refL: 'संदर्भ', provL: 'स्रोत',
      studyT: 'अध्ययन पृष्ठ', studyD: 'शिक्षा, उर्दू अनुवाद और प्रश्नोत्तर सहित संपादित पृष्ठ।',
      readL: 'हदीस {n} पढ़ें',
      prevL: '← पिछली हदीस', nextL: 'अगली हदीस →', backBookL: '← पुस्तक पर वापस', backCollL: '← संग्रह',
      collTitle: '{name} — अरबी व अंग्रेज़ी में पूर्ण संग्रह',
      collDesc: 'पूर्ण {name} ({t} हदीसें) पढ़ें — पूर्ण अरबी मूलपाठ और अंग्रेज़ी अनुवाद सहित, क्रम से।',
      bookTitle: '{name} — सभी {t} हदीसें क्रम से',
      bookDesc: '{name} की सभी {t} हदीसें देखें: पूर्ण अरबी मूलपाठ अंग्रेज़ी अनुवाद सहित।',
      entryTitle: '{short} हदीस {n} — पूर्ण अरबी मूलपाठ व अंग्रेज़ी अनुवाद',
      faqWhatQ: 'हदीस {n} किस संग्रह से है?',
      faqWhatA: '{name} की {t} में से हदीस {n}, पुस्तक {b}। प्रमाणित अरबी मूलपाठ और अंग्रेज़ी अनुवाद सहित।',
      faqFullQ: 'पूर्ण संग्रह कहां पढ़ें?',
      faqFullA: 'संग्रह पृष्ठ खोलें — क्रम से सभी {t} हदीसें, पूर्ण अरबी मूलपाठ और अंग्रेज़ी अनुवाद सहित।',
      faqLangQ: 'कौन सी भाषाएं दिखाई गई हैं?',
      faqLangA: 'प्रमाणित अरबी मूलपाठ अंग्रेज़ी अनुवाद सहित। उर्दू और हिंदी पृष्ठों पर वही प्रमाणित पाठ हैं।',
    },
  },
  ar: {
    crumb: 'الحديث',
    hubTitle: 'مكتبة الحديث — 40 للأطفال + 40 النووية + 40 مختارات صحيحة',
    hubDesc: 'جميع الأحاديث الـ120: 40 مختصرة للأطفال وأربعون النووية و40 مختارات صحيحة في العبادة والقرآن والأسرة — بالعربية والأردية والإنجليزية مع الدرس والمصدر. لكل حديث صفحته.',
    hubKw: 'مكتبة الحديث, 40 حديثا للأطفال, الأربعون النووية, صحيح البخاري مسلم, حديث قصير, حديث النية',
    hubFaq: [
      { q: 'كم حديثا في هذه المكتبة؟', a: '120 في المجموع: 40 مختصرة صحيحة للأطفال في 8 دروس والأربعون النووية للكبار و40 مختارات صحيحة في العبادة والقرآن والأسرة.' },
      { q: 'هل لكل حديث صفحته؟', a: 'نعم — لكل واحد من الـ120 صفحة مستقلة بالنص العربي والنطق والترجمة الأردية والمعنى الإنجليزي والدرس والراوي والدرجة.' },
      { q: 'هل هذه الأحاديث صحيحة؟', a: 'نعم — فقط الألفاظ المشهورة من صحيح البخاري ومسلم أو الحسن. كل صفحة تسمي المجموعة دون أرقام مخترعة.' },
      { q: 'ما الأربعون النووية؟', a: 'مجموعة الإمام يحيى النووي المشهورة عالميا من 40 حديثا تأسيسيا — النية والأركان والإخلاص والعبادة. ابدأ بالحديث 1.' },
      { q: 'ما المختارات الصحيحة؟', a: '40 حديثا مشهورا من البخاري ومسلم للكبار في 3 أقسام — العبادة والقرآن والذكر والدعاء والأخلاق والمجتمع.' },
    ],
    hubH1: 'مكتبة الحديث',
    hubSub: '40 حديثا مختصرا للأطفال والأربعون النووية و40 مختارات صحيحة — بالعربية والترجمة الأردية والمعنى الإنجليزي والدروس.',
    searchPh: 'ابحث في الحديث — مثل: النية، الصوم، الغضب…', filterPh: 'صف الـ120 حديثا — مثل: النية، النووية، الصوم…',
    badgeN: 'حديثا', badge2: 'أطفال + نووية + صحيح', badge3: 'العربية + الأردية + الإنجليزية',
    secNawawi: 'الأحاديث الأربعون النووية', secNawawiSub: 'أسس الإيمان والعبادة والأخلاق — للكبار مرتبة.',
    sabaqL: 'الدرس {n}', partL: 'الجزء {n}',
    detTitleSuffix: ' — بالعربية والأردية والإنجليزية',
    badgeHadees: 'الحديث {n} من 40', alsoSearched: 'يُبحث عنه أيضا باسم:',
    lessonKids: 'درس الأطفال', lessonL: 'الدرس', srcGradeL: 'المصدر والدرجة',
    fromL: 'المصدر:', verifyL: 'تحقق من الألفاظ مع معلم؛ والأحكام تختلف — استشر العلماء.',
    relSame: 'نفس الدرس', relMore: 'المزيد من الأحاديث', allHadees: 'جميع الأحاديث',
    prevL: '← الحديث السابق', nextL: 'الحديث التالي →',
    detFaqMean: 'ما معنى "{a}"؟', detFaqLes: 'ما درس هذا الحديث{kids}؟', detFaqSrc: 'من أين هذا الحديث؟',
    coll: {
      secT: 'مجموعات الحديث', secSub: 'مجموعات كاملة بالنص العربي الكامل والترجمة الإنجليزية — تصفح حسب الكتاب واقرأ بالترتيب.',
      countBadge: '{b} كتاب · {t} حديثا', bookOf: 'الكتاب {n}', hadithOf: 'الحديث {n} من {t}',
      arabicL: 'النص العربي', englishL: 'الترجمة الإنجليزية', refL: 'المرجع', provL: 'المصدر',
      studyT: 'صفحة الدراسة', studyD: 'صفحة محررة مع الدرس والترجمة الأردية والأسئلة.',
      readL: 'اقرأ الحديث {n}',
      prevL: '← الحديث السابق', nextL: 'الحديث التالي →', backBookL: '← عودة إلى الكتاب', backCollL: '← المجموعة',
      collTitle: '{name} — المجموعة الكاملة بالعربية والإنجليزية',
      collDesc: 'اقرأ {name} كاملة ({t} حديثا) بالنص العربي الكامل والترجمة الإنجليزية مرتبة.',
      bookTitle: '{name} — اقرأ الأحاديث الـ{t} مرتبة',
      bookDesc: 'تصفح أحاديث {name} الـ{t}: النص العربي الكامل مع الترجمة الإنجليزية.',
      entryTitle: 'حديث {short} رقم {n} — النص الكامل',
      faqWhatQ: 'من أي مجموعة الحديث {n}؟',
      faqWhatA: 'الحديث {n} من {t} في {name}، الكتاب {b}. بالنص العربي الموثق والترجمة الإنجليزية.',
      faqFullQ: 'أين أقرأ المجموعة كاملة؟',
      faqFullA: 'افتح صفحة المجموعة لتصفح الأحاديث الـ{t} مرتبة بالنص العربي الكامل والترجمة الإنجليزية.',
      faqLangQ: 'ما اللغات المعروضة؟',
      faqLangA: 'النص العربي الموثق مع الترجمة الإنجليزية. صفحات الأردية والهندية تعرض النصوص الموثقة نفسها.',
    },
  },
};

export const SEERAH_UI: Record<string, any> = {
  en: {
    crumb: 'Seerat',
    hubTitle: 'Seerat un Nabi ﷺ — Complete Biography in 16 Chapters (Makkah + Madinah)',
    hubDesc: 'The complete seerah in 16 chapters — birth, revelation, persecution, Hijrah, Badr, Uhud, conquest and farewell — with events, lessons and references. For adults, in order.',
    hubKw: 'seerah, seerat un nabi, biography of prophet muhammad, makkah madinah era, hijrah badr uhud, farewell sermon',
    hubFaq: [
      { q: 'How many chapters are there?', a: '16 chapters in order: 1–8 Makkah era (birth to the pledges), 9–16 Madinah era (Hijrah to the passing). Open any chapter for events, full story, lessons and references.' },
      { q: 'Where is this seerah sourced from?', a: 'The received sources (Ibn Hisham/Ibn Ishaq tradition) and Sahih collections, named qualitatively. Lessons are drawn plainly; consult scholars for deeper rulings.' },
      { q: 'Is this suitable for adults?', a: 'Yes — full adult depth with references. For shorter event-stories see Waqiat; for companions see Sahaba.' },
    ],
    hubH1: 'Seerat un Nabi ﷺ',
    hubSub: 'The complete biography in 16 chapters — Makkah and Madinah eras, with events, lessons and references. For adults, in order.',
    searchPh: 'Search seerah — e.g. badr, hijrah, miraj…', filterPh: 'Filter 16 chapters — e.g. badr, uhud, taif, wahi…',
    badgeN: '16 chapters', badge2: 'Makkah + Madinah eras', badge3: 'Full story for adults', badge2: 'Makkah + Madinah eras', badge3: 'Full story for adults',
    era1: 'Era 1 — Makkah', era1T: 'Birth to the Pledges (Ch.1–8)', era2: 'Era 2 — Madinah', era2T: 'Hijrah to the Passing (Ch.9–16)',
    era1S: 'Lineage, childhood, revelation, persecution, Taif, Miraj and Aqabah.', era2S: 'The state, Badr, Uhud, the conquest, farewell Hajj and legacy.',
    sahabaLine: 'For the men around him, see the', sahabaLink: '24 Sahaba companions →',
    detPrefix: 'Chapter {n} of 16', detSuffix: ' — Seerah Chapter',
    alsoSearched: 'Also searched as:',
    eraM: 'Makkah', eraD: 'Madinah', chShort: 'Ch.', eraWord: 'era', chBadge: 'Chapter {n}',
    alsoSearched: 'Also searched as:', emblemL: 'Emblematic verse', translitL: 'Transliteration',
    secEvents: 'Key events in order', secStory: 'The complete account', secLessons: 'Three lessons', lessonL: 'Lesson',
    sameEraT: 'More {e}-era chapters', moreLink: 'All 16 chapters', prevL: '← Previous chapter', nextL: 'Next chapter →',
    refL: 'References:', narratedL: 'Narrated from the received seerah and Sahih collections without invented details.',
    moreTitle: 'More chapters', moreLink: 'All 16 chapters', prevL: '← Previous chapter', nextL: 'Next chapter →',
    detFaqStory: 'What happened in this chapter?', detFaqLes: 'What are the lessons?', detFaqSrc: 'Where is this sourced from?',
  },
  ur: {
    crumb: 'سیرت',
    hubTitle: 'سیرت النبی ﷺ — 16 ابواب میں مکمل سوانح (مکہ + مدینہ)',
    hubDesc: '16 ابواب میں مکمل سیرت — پیدائش، وحی، ظلم، ہجرت، بدر، احد، فتح اور الوداع — واقعات، اسباق اور حوالوں کے ساتھ۔ بڑوں کے لیے ترتیب سے۔',
    hubKw: 'سیرت النبی, سوانح محمد, مکہ مدینہ دور, ہجرت بدر احد, خطبہ حجۃ الوداع',
    hubFaq: [
      { q: 'کتنے ابواب ہیں؟', a: 'ترتیب سے 16 ابواب: 1-8 مکی دور، 9-16 مدنی دور۔ کسی بھی باب کو واقعات، مکمل واقعہ، اسباق اور حوالوں سمیت کھولو۔' },
      { q: 'یہ سیرت کہاں سے ماخوذ ہے؟', a: 'مسلمہ ماخذ (ابن ہشام/ابن اسحاق روایت) اور صحیح مجموعوں سے — حوالے صفاتی ناموں سے۔' },
      { q: 'کیا یہ بڑوں کے لیے ہے؟', a: 'جی ہاں — حوالوں سمیت مکمل گہرائی۔ مختصر حادثاتی واقعات کے لیے واقعات، ساتھیوں کے لیے صحابہ دیکھو۔' },
    ],
    hubH1: 'سیرت النبی ﷺ',
    hubSub: '16 ابواب میں مکمل سوانح — مکی و مدنی ادوار، واقعات، اسباق اور حوالوں کے ساتھ۔ بڑوں کے لیے ترتیب سے۔',
    searchPh: 'سیرت تلاش کریں — مثلاً بدر، ہجرت، معراج…', filterPh: '16 ابواب چھانٹیں — مثلاً بدر، احد، طائف…',
    badgeN: '16 ابواب', badge2: 'مکہ + مدینہ ادوار', badge3: 'بڑوں کے لیے مکمل واقعہ', badge2: 'مکہ + مدینہ ادوار', badge3: 'بڑوں کے لیے مکمل واقعہ',
    era1: 'دور 1 — مکہ', era1T: 'پیدائش سے بیعتوں تک (باب 1-8)', era2: 'دور 2 — مدینہ', era2T: 'ہجرت سے وفات تک (باب 9-16)',
    era1S: 'نسب، بچپن، وحی، ظلم، طائف، معراج اور عقبہ۔', era2S: 'ریاست، بدر، احد، فتح، حجۃ الوداع اور ورثہ۔',
    sahabaLine: 'ان کے گرد مردوں کے لیے دیکھیں', sahabaLink: '24 صحابہ →',
    detPrefix: 'باب {n} از 16', detSuffix: ' — سیرت باب',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:',
    eraM: 'مکہ', eraD: 'مدینہ', chShort: 'باب', eraWord: 'دور', chBadge: 'باب {n}',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:', emblemL: 'نمایاں آیت', translitL: 'تلفظ',
    secEvents: 'اہم واقعات ترتیب سے', secStory: 'مکمل روداد', secLessons: 'تین اسباق', lessonL: 'سبق',
    sameEraT: 'مزید {e} دور کے ابواب', moreLink: 'تمام 16 ابواب', prevL: '← پچھلا باب', nextL: 'اگلا باب →',
    refL: 'حوالے:', narratedL: 'مسلمہ سیرت و صحیح مجموعوں سے بغیر کسی اضافے کے مروی۔',
    moreTitle: 'مزید ابواب', moreLink: 'تمام 16 ابواب', prevL: '← پچھلا باب', nextL: 'اگلا باب →',
    detFaqStory: 'اس باب میں کیا ہوا؟', detFaqLes: 'اسباق کیا ہیں؟', detFaqSrc: 'یہ کہاں سے ماخوذ ہے؟',
  },
  hi: {
    crumb: 'सीरत',
    hubTitle: 'सीरतुन नबी ﷺ — 16 अध्यायों में पूर्ण जीवनी (मक्का + मदीना)',
    hubDesc: '16 अध्यायों में पूर्ण सीरत — जन्म, वह्य, अत्याचार, हिजरत, बद्र, उहुद, विजय और विदाई — घटनाओं, शिक्षाओं और संदर्भों सहित। बड़ों हेतु क्रम से।',
    hubKw: 'सीरत नबी, पैग़ंबर Muhammad जीवनी, मक्का मदीना युग, हिजरत बद्र उहुद, विदाई उपदेश',
    hubFaq: [
      { q: 'कितने अध्याय हैं?', a: 'क्रम से 16 अध्याय: 1–8 मक्की युग, 9–16 मदनी युग। किसी भी अध्याय को घटनाओं, पूर्ण कथा, शिक्षाओं और संदर्भों सहित खोलो।' },
      { q: 'यह सीरत कहां से ली गई है?', a: 'प्राप्त स्रोतों (इब्ने हिशाम/इब्ने इसहाक़ परंपरा) और सहीह संग्रहों से — संदर्भ गुणात्मक नामों से।' },
      { q: 'क्या यह बड़ों हेतु है?', a: 'हां — संदर्भों सहित पूर्ण गहराई। संक्षिप्त घटना-कथाओं हेतु वाक़िआत, साथियों हेतु सहाबा देखो।' },
    ],
    hubH1: 'सीरतुन नबी ﷺ',
    hubSub: '16 अध्यायों में पूर्ण जीवनी — मक्की व मदनी युग, घटनाओं, शिक्षाओं और संदर्भों सहित। बड़ों हेतु क्रम से।',
    searchPh: 'सीरत खोजें — जैसे बद्र, हिजरत, मेराज…', filterPh: '16 अध्याय छांटें — जैसे बद्र, उहुद, ताइफ़…',
    badgeN: '16 अध्याय', badge2: 'मक्का + मदीना युग', badge3: 'बड़ों हेतु पूर्ण कथा', badge2: 'मक्का + मदीना युग', badge3: 'बड़ों हेतु पूर्ण कथा',
    era1: 'युग 1 — मक्का', era1T: 'जन्म से शपथों तक (अ.1–8)', era2: 'युग 2 — मदीना', era2T: 'हिजरत से निधन तक (अ.9–16)',
    era1S: 'वंश, बचपन, वह्य, अत्याचार, ताइफ़, मेराज और अक़बा।', era2S: 'राज्य, बद्र, उहुद, विजय, विदाई Hajj और विरासत।',
    sahabaLine: 'उनके आसपास पुरुषों हेतु देखें', sahabaLink: '24 सहाबा →',
    detPrefix: 'अध्याय {n} / 16', detSuffix: ' — सीरत अध्याय',
    alsoSearched: 'इन नामों से भी खोजा जाता है:',
    eraM: 'मक्का', eraD: 'मदीना', chShort: 'अ.', eraWord: 'युग', chBadge: 'अध्याय {n}',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', emblemL: 'प्रतीकात्मक आयत', translitL: 'लिप्यंतरण',
    secEvents: 'प्रमुख घटनाएं क्रम से', secStory: 'पूर्ण वृत्तांत', secLessons: 'तीन शिक्षाएं', lessonL: 'शिक्षा',
    sameEraT: 'और {e}-युग अध्याय', moreLink: 'सभी 16 अध्याय', prevL: '← पिछला अध्याय', nextL: 'अगला अध्याय →',
    refL: 'संदर्भ:', narratedL: 'प्राप्त सीरत व सहीह संग्रहों से बिना किसी मिलावट के वर्णित।',
    moreTitle: 'और अध्याय', moreLink: 'सभी 16 अध्याय', prevL: '← पिछला अध्याय', nextL: 'अगला अध्याय →',
    detFaqStory: 'इस अध्याय में क्या हुआ?', detFaqLes: 'शिक्षाएं क्या हैं?', detFaqSrc: 'यह कहां से ली गई है?',
  },
  ar: {
    crumb: 'السيرة',
    hubTitle: 'السيرة النبوية ﷺ — كاملة في 16 فصلا (مكة + المدينة)',
    hubDesc: 'السيرة كاملة في 16 فصلا — المولد والوحي والاضطهاد والهجرة وبدر وأحد والفتح والوداع — بالأحداث والدروس والمراجع. للكبار مرتبة.',
    hubKw: 'السيرة النبوية, سيرة محمد, العهد المكي المدني, الهجرة بدر أحد, خطبة الوداع',
    hubFaq: [
      { q: 'كم فصلا؟', a: '16 فصلا مرتبة: 1-8 العهد المكي و9-16 العهد المدني. افتح أي فصل بالأحداث والقصة الكاملة والدروس والمراجع.' },
      { q: 'من أين أخذت هذه السيرة؟', a: 'من المصادر المتلقاة (رواية ابن هشام/ابن إسحاق) والمجاميع الصحيحة المسماة وصفيا.' },
      { q: 'هل هي للكبار؟', a: 'نعم — بعمق كامل مع المراجع. وللقصص المختصرة انظر الوقائع وللصحابة انظر الصحابة.' },
    ],
    hubH1: 'السيرة النبوية ﷺ',
    hubSub: 'السيرة كاملة في 16 فصلا — العهدان المكي والمدني بالأحداث والدروس والمراجع. للكبار مرتبة.',
    searchPh: 'ابحث في السيرة — مثل: بدر، الهجرة، المعراج…', filterPh: 'صف الـ16 فصلا — مثل: بدر، أحد، الطائف…',
    badgeN: '16 فصلا', badge2: 'العهدان المكي والمدني', badge3: 'القصة الكاملة للكبار', badge2: 'العهدان المكي والمدني', badge3: 'القصة الكاملة للكبار',
    era1: 'العهد 1 — مكة', era1T: 'المولد إلى البيعات (1-8)', era2: 'العهد 2 — المدينة', era2T: 'الهجرة إلى الوفاة (9-16)',
    era1S: 'النسب والطفولة والوحي والاضطهاد والطائف والمعراج والعقبة.', era2S: 'الدولة وبدر وأحد والفتح وحجة الوداع والإرث.',
    sahabaLine: 'للرجال حوله انظر', sahabaLink: 'الصحابة الـ24 ←',
    detPrefix: 'الفصل {n} من 16', detSuffix: ' — فصل السيرة',
    alsoSearched: 'يُبحث عنه أيضا باسم:',
    eraM: 'مكة', eraD: 'المدينة', chShort: 'ف.', eraWord: 'العهد', chBadge: 'الفصل {n}',
    alsoSearched: 'يُبحث عنها أيضا باسم:', emblemL: 'الآية المميزة', translitL: 'النطق',
    secEvents: 'الأحداث الرئيسية مرتبة', secStory: 'الرواية الكاملة', secLessons: 'ثلاثة دروس', lessonL: 'درس',
    sameEraT: 'المزيد من فصول {e}', moreLink: 'جميع الفصول الـ16', prevL: '← الفصل السابق', nextL: 'الفصل التالي →',
    refL: 'المراجع:', narratedL: 'مروية من السيرة المتلقاة والمجاميع الصحيحة دون إضافات مخترعة.',
    moreTitle: 'المزيد من الفصول', moreLink: 'جميع الفصول الـ16', prevL: '← الفصل السابق', nextL: 'الفصل التالي →',
    detFaqStory: 'ماذا حدث في هذا الفصل؟', detFaqLes: 'ما الدروس؟', detFaqSrc: 'من أين أخذت؟',
  },
};

export const HISTORY_UI: Record<string, any> = {
  en: {
    crumb: 'History',
    hubTitle: 'Islamic History — Tarikh: 20 Landmark Events (Hijrah to Modern Age)',
    hubDesc: 'Fourteen centuries in 20 events — Hijrah, Khulafa, Cordoba, 1453 and beyond — with timelines and lessons. For the prophetic life see Seerat.',
    hubKw: 'islamic history, tarikh, hijrah khulafa cordoba 1453, muslim history timeline, landmark events islam',
    hubFaq: [
      { q: 'How many events are covered?', a: '20 landmark events in order: Prophetic, Rashidun, Classical and Later eras. Open any event for timeline, full story, lessons and references.' },
      { q: 'Where is this history sourced from?', a: 'Widely transmitted histories (Ibn Hisham, Tabari tradition) and Sahih collections — named qualitatively.' },
      { q: 'How is this different from Seerat?', a: 'Seerat covers the Prophet’s ﷺ life in 16 chapters. History continues through the caliphs, classical age and modern era.' },
    ],
    hubH1: 'Islamic History — Tarikh', hubSub: 'Fourteen centuries in 20 events — with timelines and lessons. For the prophetic life, see the Seerat.',
    searchPh: 'Search history — e.g. badr, cordoba, 1453…', badgeN: '20 events', badge2: 'Hijrah to the modern age', badge3: 'Timelines + lessons', badge2: 'Hijrah to the modern age', badge3: 'Timelines + lessons',
    seeratLine: 'For the prophetic life, see the', seeratLink: '16-chapter Seerat →',
    eraNames: ['Prophetic', 'Rashidun', 'Classical', 'Later'],
    hubEras: [
      { era: 'Prophetic', eyebrow: 'Era 1 — Prophetic', title: 'The Foundation', sub: 'Hijrah to the passing — the community is born.' },
      { era: 'Rashidun', eyebrow: 'Era 2 — Rashidun', title: 'The First Generation', sub: 'Caliphs, compilation and conquests — the deen is secured.' },
      { era: 'Classical', eyebrow: 'Era 3 — Classical', title: 'Empires & Scholarship', sub: 'Damascus to Jerusalem — dynasties rise, knowledge flowers.' },
      { era: 'Later', eyebrow: 'Era 4 — Later', title: 'Trial & Renewal', sub: 'Mongols to the modern age — catastrophe survived, revival seeded.' },
    ],
    detPrefix: 'Event {n} of 20', detSuffix: ' — History',
    alsoSearched: 'Also searched as:', emblemL: 'Emblematic words',
    secStory: 'The full story', timelineL: 'The event in order', reflectL: 'Lessons', refL: 'References:',
    narratedL: 'Narrated from widely transmitted histories without invented details.',
    seeratQ: 'For the prophetic life, read the', seeratA: '16-chapter Seerat →',
    moreTitle: 'More events', moreLink: 'All 20 events', prevL: '← Event {n}', nextL: 'Event {n} →',
    detFaqWhat: 'What happened at {p}?', detFaqWhen: 'When did it happen?', detFaqLes: 'What are the lessons?', detFaqSrc: 'Where is this sourced from?',
    alsoSearched: 'Also searched as:', emblemL: 'Emblematic words',
    secStory: 'The full story', timelineL: 'The event in order', reflectL: 'Lessons', refL: 'References:',
    narratedL: 'Narrated from widely transmitted histories without invented details.',
    moreTitle: 'More events', moreLink: 'All 20 events', prevL: '← Event {n}', nextL: 'Event {n} →',
    detFaqStory: 'What happened in this event?', detFaqLes: 'What are the lessons?', detFaqSrc: 'Where is this sourced from?',
  },
  ur: {
    crumb: 'تاریخ',
    hubTitle: 'اسلامی تاریخ — 20 سنگ میل واقعات (ہجرت سے جدید دور)',
    hubDesc: 'چودہ صدیاں 20 واقعات میں — ہجرت، خلفاء، قرطبہ، 1453 اور آگے — ٹائم لائن اور اسباق کے ساتھ۔ نبوی زندگی کے لیے سیرت دیکھو۔',
    hubKw: 'اسلامی تاریخ, تاریخ اسلام, ہجرت خلفاء قرطبہ 1453, مسلم تاریخ ٹائم لائن',
    hubFaq: [
      { q: 'کتنے واقعات شامل ہیں؟', a: 'ترتیب سے 20 سنگ میل: نبوی، راشدہ، کلاسیکی اور بعدی ادوار۔' },
      { q: 'یہ تاریخ کہاں سے ماخوذ ہے؟', a: 'وسیع مروی تواریخ (ابن ہشام، طبری روایت) اور صحیح مجموعوں سے۔' },
      { q: 'سیرت سے کیا فرق ہے؟', a: 'سیرت نبی ﷺ کی زندگی 16 ابواب میں دیتی ہے۔ تاریخ خلفاء، کلاسیکی دور اور جدید دور تک جاری رہتی ہے۔' },
    ],
    hubH1: 'اسلامی تاریخ', hubSub: 'چودہ صدیاں 20 واقعات میں — ٹائم لائن اور اسباق کے ساتھ۔ نبوی زندگی کے لیے سیرت دیکھو۔',
    searchPh: 'تاریخ تلاش کریں — مثلاً بدر، قرطبہ، 1453…', badgeN: '20 واقعات', badge2: 'ہجرت سے جدید دور', badge3: 'ٹائم لائن + اسباق', badge2: 'ہجرت سے جدید دور', badge3: 'ٹائم لائن + اسباق',
    seeratLine: 'نبوی زندگی کے لیے دیکھیں', seeratLink: '16 باب کی سیرت →',
    eraNames: ['نبوی', 'راشدہ', 'کلاسیکی', 'بعدی'],
    hubEras: [
      { era: 'Prophetic', eyebrow: 'دور 1 — نبوی', title: 'بنیاد', sub: 'ہجرت سے وفات تک — برادری پیدا ہوئی۔' },
      { era: 'Rashidun', eyebrow: 'دور 2 — راشدہ', title: 'پہلی نسل', sub: 'خلفاء، تدوین اور فتوحات — دین محفوظ ہوا۔' },
      { era: 'Classical', eyebrow: 'دور 3 — کلاسیکی', title: 'سلطنتیں و علم', sub: 'دمشق سے یروشلم — خاندان اٹھے، علم پھولا۔' },
      { era: 'Later', eyebrow: 'دور 4 — بعدی', title: 'آزمائش و تجدید', sub: 'منگول سے جدید دور — تباہی جھیلی، تجدید بوئی۔' },
    ],
    detPrefix: 'واقعہ {n} از 20', detSuffix: ' — تاریخ',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:', emblemL: 'نمایاں الفاظ',
    secStory: 'مکمل واقعہ', timelineL: 'واقعہ ترتیب سے', reflectL: 'اسباق', refL: 'حوالے:',
    narratedL: 'وسیع مروی تواریخ سے بغیر کسی اضافے کے مروی۔',
    seeratQ: 'نبوی زندگی کے لیے پڑھیں', seeratA: '16 باب کی سیرت →',
    moreTitle: 'مزید واقعات', moreLink: 'تمام 20 واقعات', prevL: '← واقعہ {n}', nextL: 'واقعہ {n} →',
    detFaqWhat: '{p} میں کیا ہوا؟', detFaqWhen: 'کب ہوا؟', detFaqLes: 'اسباق کیا ہیں؟', detFaqSrc: 'یہ کہاں سے ماخوذ ہے؟',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:', emblemL: 'نمایاں الفاظ',
    secStory: 'مکمل واقعہ', timelineL: 'واقعہ ترتیب سے', reflectL: 'اسباق', refL: 'حوالے:',
    narratedL: 'وسیع مروی تواریخ سے بغیر کسی اضافے کے مروی۔',
    moreTitle: 'مزید واقعات', moreLink: 'تمام 20 واقعات', prevL: '← واقعہ {n}', nextL: 'واقعہ {n} →',
    detFaqStory: 'اس واقعے میں کیا ہوا؟', detFaqLes: 'اسباق کیا ہیں؟', detFaqSrc: 'یہ کہاں سے ماخوذ ہے؟',
  },
  hi: {
    crumb: 'इतिहास',
    hubTitle: 'इस्लामी इतिहास — 20 ऐतिहासिक घटनाएं (हिजरत से आधुनिक युग)',
    hubDesc: 'चौदह शताब्दियां 20 घटनाओं में — हिजरत, ख़ुलफ़ा, क़ुर्तुबा, 1453 और आगे — समयरेखा और शिक्षाओं सहित। नबवी जीवन हेतु सीरत देखो।',
    hubKw: 'इस्लामी इतिहास, तारीख़ इस्लाम, हिजरत ख़ुलफ़ा क़ुर्तुबा 1453, मुस्लिम इतिहास समयरेखा',
    hubFaq: [
      { q: 'कितनी घटनाएं शामिल हैं?', a: 'क्रम से 20 ऐतिहासिक घटनाएं: नबवी, राशिदून, शास्त्रीय और परवर्ती युग।' },
      { q: 'यह इतिहास कहां से लिया गया है?', a: 'व्यापक वर्णित इतिहासों (इब्ने हिशाम, तबरी परंपरा) और सहीह संग्रहों से।' },
      { q: 'सीरत से क्या अंतर है?', a: 'सीरत नबी ﷺ का जीवन 16 अध्यायों में देती है। इतिहास ख़लीफ़ाओं, शास्त्रीय युग और आधुनिक युग तक जारी रहता है।' },
    ],
    hubH1: 'इस्लामी इतिहास', hubSub: 'चौदह शताब्दियां 20 घटनाओं में — समयरेखा और शिक्षाओं सहित। नबवी जीवन हेतु सीरत देखो।',
    searchPh: 'इतिहास खोजें — जैसे बद्र, क़ुर्तुबा, 1453…', badgeN: '20 घटनाएं', badge2: 'हिजरत से आधुनिक युग', badge3: 'समयरेखा + शिक्षाएं', badge2: 'हिजरत से आधुनिक युग', badge3: 'समयरेखा + शिक्षाएं',
    seeratLine: 'नबवी जीवन हेतु देखें', seeratLink: '16-अध्याय सीरत →',
    eraNames: ['नबवी', 'राशिदून', 'शास्त्रीय', 'परवर्ती'],
    hubEras: [
      { era: 'Prophetic', eyebrow: 'युग 1 — नबवी', title: 'नींव', sub: 'हिजरत से निधन तक — समुदाय जन्मा।' },
      { era: 'Rashidun', eyebrow: 'युग 2 — राशिदून', title: 'प्रथम पीढ़ी', sub: 'ख़लीफ़ा, संकलन और विजय — धर्म सुरक्षित हुआ।' },
      { era: 'Classical', eyebrow: 'युग 3 — शास्त्रीय', title: 'साम्राज्य व विद्वता', sub: 'दमिश्क़ से यरूशलम — वंश उठे, ज्ञान फूला।' },
      { era: 'Later', eyebrow: 'युग 4 — परवर्ती', title: 'परीक्षा व नवीकरण', sub: 'मंगोल से आधुनिक युग — विनाश सहा, नवीकरण बोया।' },
    ],
    detPrefix: 'घटना {n} / 20', detSuffix: ' — इतिहास',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', emblemL: 'प्रतीकात्मक शब्द',
    secStory: 'पूरी कहानी', timelineL: 'घटना क्रम से', reflectL: 'शिक्षाएं', refL: 'संदर्भ:',
    narratedL: 'व्यापक वर्णित इतिहासों से बिना किसी मिलावट के वर्णित।',
    seeratQ: 'नबवी जीवन हेतु पढ़ें', seeratA: '16-अध्याय सीरत →',
    moreTitle: 'और घटनाएं', moreLink: 'सभी 20 घटनाएं', prevL: '← घटना {n}', nextL: 'घटना {n} →',
    detFaqWhat: '{p} में क्या हुआ?', detFaqWhen: 'कब हुआ?', detFaqLes: 'शिक्षाएं क्या हैं?', detFaqSrc: 'यह कहां से ली गई है?',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', emblemL: 'प्रतीकात्मक शब्द',
    secStory: 'पूरी कहानी', timelineL: 'घटना क्रम से', reflectL: 'शिक्षाएं', refL: 'संदर्भ:',
    narratedL: 'व्यापक वर्णित इतिहासों से बिना किसी मिलावट के वर्णित।',
    moreTitle: 'और घटनाएं', moreLink: 'सभी 20 घटनाएं', prevL: '← घटना {n}', nextL: 'घटना {n} →',
    detFaqStory: 'इस घटना में क्या हुआ?', detFaqLes: 'शिक्षाएं क्या हैं?', detFaqSrc: 'यह कहां से ली गई है?',
  },
  ar: {
    crumb: 'التاريخ',
    hubTitle: 'التاريخ الإسلامي — 20 حدثا مفصليا (من الهجرة إلى العصر الحديث)',
    hubDesc: 'أربعة عشر قرنا في 20 حدثا — الهجرة والخلفاء وقرطبة و1453 وما بعدها — بخطوط زمنية ودروس. وللحياة النبوية انظر السيرة.',
    hubKw: 'التاريخ الإسلامي, تاريخ الإسلام, الهجرة الخلفاء قرطبة 1453, خط زمني إسلامي',
    hubFaq: [
      { q: 'كم حدثا مشمولا؟', a: '20 حدثا مفصليا مرتبة: العهود النبوي والراشدي والكلاسيكي والمتأخر.' },
      { q: 'من أين أخذ هذا التاريخ؟', a: 'من التواريخ المتناقلة (رواية ابن هشام والطبري) والمجاميع الصحيحة.' },
      { q: 'ما الفرق عن السيرة؟', a: 'السيرة تعطي حياة النبي ﷺ في 16 فصلا. والتاريخ يستمر عبر الخلفاء والعصر الكلاسيكي والحديث.' },
    ],
    hubH1: 'التاريخ الإسلامي', hubSub: 'أربعة عشر قرنا في 20 حدثا — بخطوط زمنية ودروس. وللحياة النبوية انظر السيرة.',
    searchPh: 'ابحث في التاريخ — مثل: بدر، قرطبة، 1453…', badgeN: '20 حدثا', badge2: 'من الهجرة إلى العصر الحديث', badge3: 'خطوط زمنية + دروس', badge2: 'من الهجرة إلى العصر الحديث', badge3: 'خطوط زمنية + دروس',
    seeratLine: 'للحياة النبوية انظر', seeratLink: 'السيرة ذات الـ16 فصلا ←',
    eraNames: ['النبوي', 'الراشدي', 'الكلاسيكي', 'المتأخر'],
    hubEras: [
      { era: 'Prophetic', eyebrow: 'العهد 1 — النبوي', title: 'الأساس', sub: 'الهجرة إلى الوفاة — ولدت الجماعة.' },
      { era: 'Rashidun', eyebrow: 'العهد 2 — الراشدي', title: 'الجيل الأول', sub: 'الخلفاء والتدوين والفتوح — حفظ الدين.' },
      { era: 'Classical', eyebrow: 'العهد 3 — الكلاسيكي', title: 'الإمبراطوريات والعلم', sub: 'دمشق إلى القدس — قامت الأسر وازدهر العلم.' },
      { era: 'Later', eyebrow: 'العهد 4 — المتأخر', title: 'المحنة والتجديد', sub: 'المغول إلى العصر الحديث — نجاة من الكارثة وبذر التجديد.' },
    ],
    detPrefix: 'الحدث {n} من 20', detSuffix: ' — تاريخ',
    alsoSearched: 'يُبحث عنه أيضا باسم:', emblemL: 'الكلمات المميزة',
    secStory: 'القصة كاملة', timelineL: 'الحدث مرتبا', reflectL: 'الدروس', refL: 'المراجع:',
    narratedL: 'مروي من التواريخ المتناقلة دون إضافات مخترعة.',
    seeratQ: 'للحياة النبوية اقرأ', seeratA: 'السيرة ذات الـ16 فصلا ←',
    moreTitle: 'المزيد من الأحداث', moreLink: 'جميع الأحداث الـ20', prevL: '← الحدث {n}', nextL: 'الحدث {n} →',
    detFaqWhat: 'ماذا حدث في {p}؟', detFaqWhen: 'متى حدث؟', detFaqLes: 'ما الدروس؟', detFaqSrc: 'من أين أخذ؟',
    alsoSearched: 'يُبحث عنه أيضا باسم:', emblemL: 'الكلمات المميزة',
    secStory: 'القصة كاملة', timelineL: 'الحدث مرتبا', reflectL: 'الدروس', refL: 'المراجع:',
    narratedL: 'مروي من التواريخ المتناقلة دون إضافات مخترعة.',
    moreTitle: 'المزيد من الأحداث', moreLink: 'جميع الأحداث الـ20', prevL: '← الحدث {n}', nextL: 'الحدث {n} →',
    detFaqStory: 'ماذا حدث في هذا الحدث؟', detFaqLes: 'ما الدروس؟', detFaqSrc: 'من أين أخذ؟',
  },
};

export const MEANING_UI: Record<string, any> = {
  en: {
    crumb: 'Meanings',
    hubTitle: 'Islamic Meanings — 55 Key Terms with Proof & Practice (Tawakkul, Sabr, Shukr…)',
    hubDesc: 'Core concepts with definition, Quran/hadith proof, misconception correction and 3 practice steps. Each term has its own page.',
    hubKw: 'islamic meanings, tawakkul sabr shukr taqwa meaning, iman ihsan ikhlas, key islamic terms',
    hubFaq: [
      { q: 'How many terms are covered?', a: '55 core concepts — from Iman and Tawakkul to Rizq and Dhikr. Open any term for definition, proof, misconception and practice.' },
      { q: 'What does each page include?', a: 'Definition, Quran proof with reference, hadith proof where present, a common misconception corrected, and 3 daily practice steps.' },
      { q: 'How should I study them?', a: 'One term a day: read the proof, drop the misconception, and do the 3 steps. Teach one term a week to lock it.' },
    ],
    hubH1: 'Islamic Meanings', hubSub: 'Core concepts every Muslim should understand — definition, proof, misconception and practice. Tap any term.',
    searchPh: 'Search meanings — e.g. sabr, taqwa, shukr…',
    badgeN: '55 terms', secTerms: 'Browse all terms', secGuides: 'In-depth guides',
    detPrefix: 'Meaning',
    alsoSearched: 'Also searched as:', proofL: 'Proof', hadithL: 'Hadith',
    misL: 'Common misconception', pracL: 'Practice in 3 steps', srcNote: 'Learn details from a teacher; consult scholars for deeper rulings.',
    moreTitle: 'More meanings', moreLink: 'All meanings', prevL: '← Previous', nextL: 'Next →',
    detFaqDef: 'What does {t} mean?', detFaqPrac: 'How do I practice {t} daily?', detFaqSrc: 'Where is {t} proven from?',
  },
  ur: {
    crumb: 'مطلب',
    hubTitle: 'اسلامی معانی — ثبوت و عمل کے ساتھ 55 اہم الفاظ',
    hubDesc: 'بنیادی تصورات: تعریف، قرآنی/حدیثی دلیل، غلط فہمی کی اصلاح اور 3 عملی قدم۔ ہر لفظ کا اپنا صفحہ۔',
    hubKw: 'اسلامی معانی, توکل صبر شکر تقوی مطلب, ایمان احسان اخلاص',
    hubFaq: [
      { q: 'کتنے الفاظ شامل ہیں؟', a: '55 بنیادی تصورات — ایمان اور توکل سے رزق و ذکر تک۔' },
      { q: 'ہر صفحے میں کیا ہے؟', a: 'تعریف، حوالے سمیت قرآنی دلیل، حدیثی دلیل، ایک عام غلط فہمی کی اصلاح، اور 3 روزانہ عملی قدم۔' },
      { q: 'انہیں کیسے پڑھیں؟', a: 'روز ایک لفظ: دلیل پڑھو، غلط فہمی چھوڑو، 3 قدم کرو۔ ہفتے میں ایک لفظ پڑھاؤ۔' },
    ],
    hubH1: 'اسلامی معانی', hubSub: 'ہر مسلمان کے سمجھنے والے بنیادی تصورات — تعریف، دلیل، غلط فہمی اور عمل۔ کوئی بھی لفظ کھولو۔',
    searchPh: 'معانی تلاش کریں — مثلاً صبر، تقوی، شکر…',
    badgeN: '55 الفاظ', secTerms: 'تمام الفاظ دیکھیں', secGuides: 'تفصیلی رہنمائی',
    detPrefix: 'مطلب',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:', proofL: 'دلیل', hadithL: 'حدیث',
    misL: 'عام غلط فہمی', pracL: '3 قدموں میں عمل', srcNote: 'تفصیل استاد سے سیکھو؛ گہرے مسائل کے لیے علماء سے رجوع کرو۔',
    moreTitle: 'مزید معانی', moreLink: 'تمام معانی', prevL: '← پچھلا', nextL: 'اگلا →',
    detFaqDef: '{t} کا مطلب کیا ہے؟', detFaqPrac: '{t} پر روزانہ عمل کیسے کروں؟', detFaqSrc: '{t} کہاں سے ثابت ہے؟',
  },
  hi: {
    crumb: 'अर्थ',
    hubTitle: 'इस्लामी अर्थ — प्रमाण व अभ्यास सहित 55 प्रमुख शब्द',
    hubDesc: 'मूल अवधारणाएं: परिभाषा, क़ुरानी/हदीसी प्रमाण, भ्रांति-सुधार और 3 अभ्यास चरण। हर शब्द का अपना पृष्ठ।',
    hubKw: 'इस्लामी अर्थ, तवक्कुल सब्र शुक्र तक़वा अर्थ, ईमान इहसान इख़लास',
    hubFaq: [
      { q: 'कितने शब्द शामिल हैं?', a: '55 मूल अवधारणाएं — ईमान और तवक्कुल से रोज़ी व ज़िक्र तक।' },
      { q: 'हर पृष्ठ में क्या है?', a: 'परिभाषा, संदर्भ सहित क़ुरानी प्रमाण, हदीसी प्रमाण, एक सामान्य भ्रांति-सुधार, और 3 दैनिक अभ्यास चरण।' },
      { q: 'इन्हें कैसे पढ़ें?', a: 'रोज़ एक शब्द: प्रमाण पढ़ो, भ्रांति छोड़ो, 3 चरण करो। सप्ताह में एक शब्द पढ़ाओ।' },
    ],
    hubH1: 'इस्लामी अर्थ', hubSub: 'हर मुसलमान के समझने योग्य मूल अवधारणाएं — परिभाषा, प्रमाण, भ्रांति और अभ्यास। कोई भी शब्द खोलो।',
    searchPh: 'अर्थ खोजें — जैसे सब्र, तक़वा, शुक्र…',
    badgeN: '55 शब्द', secTerms: 'सभी शब्द देखें', secGuides: 'विस्तृत मार्गदर्शन',
    detPrefix: 'अर्थ',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', proofL: 'प्रमाण', hadithL: 'हदीस',
    misL: 'सामान्य भ्रांति', pracL: '3 चरणों में अभ्यास', srcNote: 'विवरण शिक्षक से सीखो; गहरे नियमों हेतु विद्वानों से पूछो।',
    moreTitle: 'और अर्थ', moreLink: 'सभी अर्थ', prevL: '← पिछला', nextL: 'अगला →',
    detFaqDef: '{t} का अर्थ क्या है?', detFaqPrac: '{t} का रोज़ अभ्यास कैसे करूं?', detFaqSrc: '{t} कहां से सिद्ध है?',
  },
  ar: {
    crumb: 'المعاني',
    hubTitle: 'المعاني الإسلامية — 55 مصطلحا رئيسيا بالدليل والعمل',
    hubDesc: 'مفاهيم أساسية: التعريف والدليل القرآني/الحديثي وتصحيح الفهم الخاطئ و3 خطوات عملية. لكل مصطلح صفحته.',
    hubKw: 'المعاني الإسلامية, التوكل الصبر الشكر التقوى معنى, الإيمان الإحسان الإخلاص',
    hubFaq: [
      { q: 'كم مصطلحا مشمولا؟', a: '55 مفهوما أساسيا — من الإيمان والتوكل إلى الرزق والذكر.' },
      { q: 'ماذا تشمل كل صفحة؟', a: 'التعريف والدليل القرآني بالمرجع والدليل الحديثي وتصحيح فهم خاطئ شائع و3 خطوات يومية.' },
      { q: 'كيف أدرسها؟', a: 'مصطلح يوميا: اقرأ الدليل واترك الفهم الخاطئ وطبق الخطوات الثلاث. وعلم مصطلحا أسبوعيا.' },
    ],
    hubH1: 'المعاني الإسلامية', hubSub: 'مفاهيم أساسية يجب أن يفهمها كل مسلم — التعريف والدليل والفهم والعمل. افتح أي مصطلح.',
    searchPh: 'ابحث في المعاني — مثل: الصبر، التقوى، الشكر…',
    badgeN: '55 مصطلحا', secTerms: 'تصفح جميع المصطلحات', secGuides: 'أدلة مفصلة',
    detPrefix: 'المعنى',
    alsoSearched: 'يُبحث عنه أيضا باسم:', proofL: 'الدليل', hadithL: 'الحديث',
    misL: 'فهم خاطئ شائع', pracL: 'العمل في 3 خطوات', srcNote: 'تعلم التفاصيل من معلم؛ واستشر العلماء في الأحكام.',
    moreTitle: 'المزيد من المعاني', moreLink: 'جميع المعاني', prevL: '← السابق', nextL: 'التالي →',
    detFaqDef: 'ما معنى {t}؟', detFaqPrac: 'كيف أطبق {t} يوميا؟', detFaqSrc: 'من أين ثبت {t}؟',
  },
};
