/* Hikmah Noor — site section chrome localization, part 1.
 * Kalima / Hadees / Seerah / Prophet / Sahaba / Women hubs + details
 * in en/hi/ur/ar. English strings are byte-identical to current pages.
 * Templates: {t} title, {n} count, {o} order, {c} cat, {e}/{l} counts.
 */
export function secUI(locale: string, map: Record<string, any>): any {
  return (map as any)[locale] ?? map.en;
}

/* Short section eyebrows shared by story details (prophets/sahaba/women/history). */
export const SEC_E: Record<string, { story: string; time: string; refl: string }> = {
  en: { story: 'Story', time: 'Timeline', refl: 'Reflect' },
  ur: { story: 'واقعہ', time: 'ترتیب', refl: 'غور کریں' },
  hi: { story: 'कहानी', time: 'क्रम', refl: 'विचार करें' },
  ar: { story: 'القصة', time: 'الترتيب', refl: 'تأمل' },
};
export function secE(locale: string): { story: string; time: string; refl: string } {
  return (SEC_E as any)[locale] ?? SEC_E.en;
}

export const KALIMA_UI: Record<string, any> = {
  en: {
    hubTitle: 'All 6 Kalimas in Arabic with Transliteration, Meaning & Explanation',
    hubDesc: 'All 6 kalimas — Tayyibah, Shahadah, Tamjeed, Tawheed, Astaghfar and Radd-e-Kufr — with Arabic, transliteration, English meaning and source basis.',
    hubKw: '6 kalimas, 6 kalma, all kalimas, kalma in arabic, pehla kalma, dusra kalma, first kalima, second kalima, la ilaha illallah, shahadah',
    hubFaq: [
      { q: 'How many kalimas are there?', a: 'Traditionally six are taught: Tayyibah, Shahadah, Tamjeed, Tawheed, Astaghfar and Radd-e-Kufr. Open each for Arabic, transliteration, meaning and source basis.' },
      { q: 'Does every kalima include transliteration and meaning?', a: 'Yes — Arabic text, easy transliteration, English meaning, virtue and source basis on each kalima’s own page.' },
      { q: 'Are these kalimas from hadith?', a: 'The first two match hadith wordings directly. Kalimas 3–6 are traditional curriculum wordings whose phrases come from the Quran and hadith — each page states its exact basis without invented references.' },
    ],
    hubH1: 'All 6 Kalimas', hubSub: 'Learn each kalima with Arabic, transliteration, English meaning, virtue and source basis — from Tayyibah to Radd-e-Kufr.',
    searchPh: 'Search kalimas — e.g. pehla kalma, shahadah…', badgeN: '6 kalimas', badge3: 'Arabic + transliteration + meaning',
    secList: 'The six kalimas', faqTitle: 'Frequently asked questions',
    detTitle: '{t} in Arabic with Transliteration & Meaning',
    alsoSearched: 'Also searched as:', whenL: 'When', virtueL: 'Virtue', basisL: 'Basis:',
    verifyL: 'Verify wording with a teacher; rulings differ — consult scholars.',
    relTitle: 'The other kalimas', relLink: 'All 6 kalimas', prevL: '← Previous kalima', nextL: 'Next kalima →',
    detFaqWhat: 'What is the {t}?', detFaqVirtue: 'What is the virtue of {t}?', detFaqSrc: 'Where is {t} from?',
  },
  ur: {
    hubTitle: 'تمام 6 کلمات — عربی متن، تلفظ، ترجمہ و وضاحت',
    hubDesc: 'تمام 6 کلمات — طیبہ، شہادت، تمجید، توحید، استغفار اور رد کفر — عربی متن، تلفظ، ترجمہ اور حوالے کے ساتھ۔',
    hubKw: '6 kalimas, 6 کلمے, تمام کلمات, کلمہ عربی میں, پہلا کلمہ, دوسرا کلمہ, لا الہ الا اللہ, شہادت',
    hubFaq: [
      { q: 'کلمے کتنے ہیں؟', a: 'روایتی طور پر چھ پڑھائے جاتے ہیں: طیبہ، شہادت، تمجید، توحید، استغفار اور رد کفر۔ ہر ایک کا عربی متن، تلفظ، ترجمہ اور حوالہ اس کے صفحے پر کھولو۔' },
      { q: 'کیا ہر کلمے میں تلفظ اور ترجمہ شامل ہے؟', a: 'جی ہاں — ہر کلمے کے اپنے صفحے پر عربی متن، آسان تلفظ، ترجمہ، فضیلت اور حوالہ ہے۔' },
      { q: 'کیا یہ کلمات حدیث سے ہیں؟', a: 'پہلے دو حدیث کے الفاظ سے براہ راست ملتے ہیں۔ کلمات 3-6 روایتی نصابی الفاظ ہیں جن کے جملے قرآن و حدیث سے ہیں — ہر صفحہ بغیر گھڑے حوالوں کے اصل بتاتا ہے۔' },
    ],
    hubH1: 'تمام 6 کلمات', hubSub: 'ہر کلمہ عربی متن، تلفظ، ترجمہ، فضیلت اور حوالے کے ساتھ سیکھو — طیبہ سے رد کفر تک۔',
    searchPh: 'کلمات تلاش کریں — مثلاً پہلا کلمہ، شہادت…', badgeN: '6 کلمات', badge3: 'عربی + تلفظ + ترجمہ',
    secList: 'چھ کلمات', faqTitle: 'اکثر پوچھے گئے سوالات',
    detTitle: '{t} — عربی متن، تلفظ و ترجمہ',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:', whenL: 'وقت', virtueL: 'فضیلت', basisL: 'حوالہ:',
    verifyL: 'الفاظ استاد سے تصدیق کرو؛ مسائل میں اختلاف ہے — علماء سے رجوع کرو۔',
    relTitle: 'دوسرے کلمات', relLink: 'تمام 6 کلمات', prevL: '← پچھلا کلمہ', nextL: 'اگلا کلمہ →',
    detFaqWhat: '{t} کیا ہے؟', detFaqVirtue: '{t} کی فضیلت کیا ہے؟', detFaqSrc: '{t} کا حوالہ کیا ہے؟',
  },
  hi: {
    hubTitle: 'सभी 6 कलिमे — अरबी, लिप्यंतरण, अर्थ व व्याख्या सहित',
    hubDesc: 'सभी 6 कलिमे — तैयिबा, शहादत, तमजीद, तौहीद, इस्तिगफार और रद्दे कुफ़्र — अरबी, लिप्यंतरण, अर्थ और स्रोत सहित।',
    hubKw: '6 kalimas, 6 कलमे, सभी कलिमे, कलमा अरबी में, पहला कलमा, दूसरा कलमा, ला इलाहा इल्लल्लाह, शहादत',
    hubFaq: [
      { q: 'कलिमे कितने हैं?', a: 'परंपरागत छह पढ़ाए जाते हैं: तैयिबा, शहादत, तमजीद, तौहीद, इस्तिगफार और रद्दे कुफ़्र। हर एक का अरबी, लिप्यंतरण, अर्थ और स्रोत उसके पृष्ठ पर खोलो।' },
      { q: 'क्या हर कलिमे में लिप्यंतरण और अर्थ शामिल है?', a: 'हां — हर कलिमे के अपने पृष्ठ पर अरबी, सरल लिप्यंतरण, अर्थ, फ़ज़ीलत और स्रोत है।' },
      { q: 'क्या ये कलिमे हदीस से हैं?', a: 'प्रथम दो हदीस शब्दों से सीधे मिलते हैं। 3-6 पारंपरिक पाठ्यचर्या शब्द हैं जिनके वाक्य क़ुरान व हदीस से हैं — हर पृष्ठ बिना गढ़े संदर्भों के मूल बताता है।' },
    ],
    hubH1: 'सभी 6 कलिमे', hubSub: 'हर कलिमा अरबी, लिप्यंतरण, अर्थ, फ़ज़ीलत और स्रोत सहित सीखो — तैयिबा से रद्दे कुफ़्र तक।',
    searchPh: 'कलिमे खोजें — जैसे पहला कलमा, शहादत…', badgeN: '6 कलिमे', badge3: 'अरबी + लिप्यंतरण + अर्थ',
    secList: 'छह कलिमे', faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    detTitle: '{t} — अरबी, लिप्यंतरण व अर्थ सहित',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', whenL: 'समय', virtueL: 'फ़ज़ीलत', basisL: 'स्रोत:',
    verifyL: 'शब्द शिक्षक से सत्यापित करो; नियमों में मतभेद है — विद्वानों से पूछो।',
    relTitle: 'अन्य कलिमे', relLink: 'सभी 6 कलिमे', prevL: '← पिछला कलिमा', nextL: 'अगला कलिमा →',
    detFaqWhat: '{t} क्या है?', detFaqVirtue: '{t} की फ़ज़ीलत क्या है?', detFaqSrc: '{t} का स्रोत क्या है?',
  },
  ar: {
    hubTitle: 'الكلمات الست بالعربية مع النطق والمعنى والشرح',
    hubDesc: 'الكلمات الست — الطيبة والشهادة والتمجيد والتوحيد والاستغفار ورد الكفر — بالنص العربي والنطق والمعنى والمصدر.',
    hubKw: '6 kalimas, الكلمات الست, الكلمة بالعربية, الكلمة الأولى, لا إله إلا الله, الشهادة',
    hubFaq: [
      { q: 'كم عدد الكلمات؟', a: 'ست تدرس تقليديا: الطيبة والشهادة والتمجيد والتوحيد والاستغفار ورد الكفر. افتح كل واحدة للنص العربي والنطق والمعنى والمصدر.' },
      { q: 'هل تشمل كل كلمة النطق والمعنى؟', a: 'نعم — كل كلمة في صفحتها بالنص العربي والنطق السهل والمعنى والفضل والمصدر.' },
      { q: 'هل هذه الكلمات من الحديث؟', a: 'الأوليان تطابقان ألفاظ الحديث مباشرة. والكلمات 3-6 صيغ منهجية تقليدية عباراتها من القرآن والحديث — وكل صفحة تبين أصلها الدقيق دون مراجع مخترعة.' },
    ],
    hubH1: 'الكلمات الست', hubSub: 'تعلم كل كلمة بالنص العربي والنطق والمعنى والفضل والمصدر — من الطيبة إلى رد الكفر.',
    searchPh: 'ابحث في الكلمات — مثل: الأولى، الشهادة…', badgeN: '6 كلمات', badge3: 'العربية + النطق + المعنى',
    secList: 'الكلمات الست', faqTitle: 'الأسئلة الشائعة',
    detTitle: '{t} بالعربية مع النطق والمعنى',
    alsoSearched: 'يُبحث عنها أيضا باسم:', whenL: 'الوقت', virtueL: 'الفضل', basisL: 'المصدر:',
    verifyL: 'تحقق من الألفاظ مع معلم؛ والأحكام تختلف — استشر العلماء.',
    relTitle: 'الكلمات الأخرى', relLink: 'الكلمات الست', prevL: '← الكلمة السابقة', nextL: 'الكلمة التالية →',
    detFaqWhat: 'ما هي {t}؟', detFaqVirtue: 'ما فضل {t}؟', detFaqSrc: 'ما مصدر {t}؟',
  },
};

export const PROPHET_UI: Record<string, any> = {
  en: {
    hubTitle: 'The 25 Prophets in Islam — Stories in Order with Lessons (25 prophets)',
    hubDesc: 'All 25 prophets in order — Adam, Nuh, Ibrahim, Musa, Dawud, Sulayman, Yunus, Isa and Muhammad ﷺ — with events, lessons and Quran references. Each prophet has its own page.',
    hubKw: '25 prophets in islam, prophets stories in order, qisse ambiya, adam, nuh, ibrahim, musa, dawud, sulayman, yunus, isa, muhammad, anbiya stories',
    hubFaq: [
      { q: 'How many prophets are covered?', a: '25 prophets in chronological order, from Adam to Muhammad ﷺ. Open any prophet for the full story with events, lessons and Quran references.' },
      { q: 'Where do these stories come from?', a: 'Each story cites its Quran passages — no invented details. Lessons are drawn plainly from the verses; consult scholars for deeper rulings.' },
      { q: 'How is this different from Waqiat?', a: 'Waqiat tells famous event-stories (the Well, the Fire, the Hijrah). The Prophets hub gives every prophet — including Idris, Hud, Shuayb, Dhul-Kifl, Zakariya and others — in one chronological series. The 8 overlapping prophets link both ways.' },
    ],
    hubH1: 'The 25 Prophets', hubSub: 'Every prophet from Adam to Muhammad ﷺ — in order, with the story, key events, lessons and Quran references. Tap any prophet for his own page.',
    searchPh: 'Search prophets — e.g. yusuf, musa, yunus…', badgeN: 'prophets', badge2: 'In chronological order', badge3: 'Quran-only narratives',
    waqiatLine: 'Looking for event-stories like the Well or the Hijrah?', waqiatLink: 'Browse Waqiat →',
    eraNames: ['Early', 'Patriarchs', 'Exodus & Kings', 'Late & Final'],
    eraTitles: ['The Beginning (1–5)', 'The Patriarchs (6–11)', 'Exodus & Kings (12–21)', 'The Closing Chain (22–25)'],
    eraSubs: ['Adam to Salih — humanity’s first chapters.', 'Ibrahim to Yusuf — the family of nations.', 'Shuayb to Yunus — exodus, kingdom and trials.', 'Zakariya to Muhammad ﷺ — the closing chain.'],
    faqTitle: 'Frequently asked questions',
    detSuffix: ' — Story & Lessons', badgeProphet: 'Prophet {o} of 25',
    alsoSearched: 'Also searched as:', emblemL: 'Emblematic verse', translitL: 'Transliteration',
    secStory: 'The full story', timelineL: 'The story in order', reflectL: 'Lessons', refL: 'References:',
    narratedL: 'Narrated strictly from the Quran ({r}) without invented details.',
    consultL: 'Narrated from the Quran without invented details; consult scholars for rulings.',
    waqiatQ: 'Want the event-focused telling?', waqiatA: 'Read the Waqiat narrative →',
    moreTitle: 'More prophets', moreLink: 'All 25 prophets', prevL: '← Prophet {o}', nextL: 'Prophet {o} →',
    detFaqWho: 'Who was Prophet {p}?', detFaqLes: 'What are the lessons from {p}’s story?', detFaqWhere: 'Where is this story in the Quran?',
  },
  ur: {
    hubTitle: 'اسلام میں 25 انبیاء — ترتیب سے واقعات و اسباق (25 انبیاء)',
    hubDesc: 'تمام 25 انبیاء ترتیب سے — آدم، نوح، ابراہیم، موسیٰ، داؤد، سلیمان، یونس، عیسیٰ اور محمد ﷺ — واقعات، اسباق اور قرآنی حوالوں کے ساتھ۔ ہر نبی کا اپنا صفحہ۔',
    hubKw: '25 انبیاء اسلام, انبیاء کے واقعات ترتیب سے, قصص انبیاء, آدم, نوح, ابراہیم, موسیٰ, یوسف, محمد',
    hubFaq: [
      { q: 'کتنے انبیاء شامل ہیں؟', a: 'آدم سے محمد ﷺ تک ترتیب سے 25 انبیاء۔ کسی بھی نبی کو واقعات، اسباق اور قرآنی حوالوں سمیت مکمل پڑھو۔' },
      { q: 'یہ واقعات کہاں سے لیے گئے ہیں؟', a: 'ہر واقعہ قرآنی آیات سے ہے — کوئی گھڑی بات نہیں۔ اسباق آیات سے واضح لیے گئے؛ گہرے مسائل کے لیے علماء سے رجوع کرو۔' },
      { q: 'واقعات سے کیا فرق ہے؟', a: 'واقعات مشہور حادثے سناتے ہیں (کنواں، آگ، ہجرت)۔ انبیاء میں ہر نبی ہے — ادریس، ہود، شعیب، ذوالکفل، زکریا سمیت — ایک ترتیب وار سلسلے میں۔' },
    ],
    hubH1: '25 انبیاء', hubSub: 'آدم سے محمد ﷺ تک ہر نبی — ترتیب سے، واقعہ، اہم حالات، اسباق اور قرآنی حوالوں کے ساتھ۔ کسی بھی نبی کا صفحہ کھولو۔',
    searchPh: 'انبیاء تلاش کریں — مثلاً یوسف، موسیٰ، یونس…', badgeN: 'انبیاء', badge2: 'ترتیب وار', badge3: 'صرف قرآنی واقعات',
    waqiatLine: 'کنویں یا ہجرت جیسے حادثاتی واقعات چاہیے؟', waqiatLink: 'واقعات دیکھیں →',
    eraNames: ['ابتدائی', 'آبائی', 'خروج و بادشاہت', 'آخری سلسلہ'],
    eraTitles: ['آغاز (1-5)', 'آبائی (6-11)', 'خروج و بادشاہت (12-21)', 'آخری سلسلہ (22-25)'],
    eraSubs: ['آدم سے صالح — انسانیت کے پہلے ابواب۔', 'ابراہیم سے یوسف — قوموں کا خاندان۔', 'شعیب سے یونس — خروج، بادشاہت اور آزمائش۔', 'زکریا سے محمد ﷺ — آخری سلسلہ۔'],
    faqTitle: 'اکثر پوچھے گئے سوالات',
    detSuffix: ' — واقعہ و اسباق', badgeProphet: 'نبی {o} از 25',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:', emblemL: 'نمایاں آیت', translitL: 'تلفظ',
    secStory: 'مکمل واقعہ', timelineL: 'واقعہ ترتیب سے', reflectL: 'اسباق', refL: 'حوالے:',
    narratedL: 'صرف قرآن ({r}) سے بغیر کسی اضافے کے بیان کیا گیا۔',
    consultL: 'قرآن سے بغیر اضافے کے مروی؛ مسائل کے لیے علماء سے رجوع کریں۔',
    waqiatQ: 'حادثے والی روایت چاہیے؟', waqiatA: 'واقعات کی روایت پڑھیں →',
    moreTitle: 'مزید انبیاء', moreLink: 'تمام 25 انبیاء', prevL: '← نبی {o}', nextL: 'نبی {o} →',
    detFaqWho: 'نبی {p} کون تھے؟', detFaqLes: '{p} کے واقعے سے کیا سبق ملتے ہیں؟', detFaqWhere: 'یہ واقعہ قرآن میں کہاں ہے؟',
  },
  hi: {
    hubTitle: 'इस्लाम में 25 नबी — क्रम से कहानियां व शिक्षाएं (25 नबी)',
    hubDesc: 'सभी 25 नबी क्रम से — आदम, नूह, इब्राहीम, मूसा, दाऊद, सुलैमान, यूनुस, ईसा और Muhammad ﷺ — घटनाओं, शिक्षाओं और क़ुरानी संदर्भों सहित। हर नबी का अपना पृष्ठ।',
    hubKw: '25 नबी इस्लाम, नबियों की कहानियां क्रम से, क़िस्से अंबिया, आदम, नूह, इब्राहीम, मूसा, यूसुफ़, Muhammad',
    hubFaq: [
      { q: 'कितने नबी शामिल हैं?', a: 'आदम से Muhammad ﷺ तक क्रम से 25 नबी। किसी भी नबी को घटनाओं, शिक्षाओं और क़ुरानी संदर्भों सहित पूरा पढ़ो।' },
      { q: 'ये कहानियां कहां से ली गई हैं?', a: 'हर कहानी क़ुरानी आयतों से है — कोई गढ़ी बात नहीं। शिक्षाएं आयतों से स्पष्ट ली गई हैं; गहरे नियमों हेतु विद्वानों से पूछो।' },
      { q: 'वाक़िआत से क्या अंतर है?', a: 'वाक़िआत प्रसिद्ध घटनाएं सुनाते हैं (कुआं, आग, हिजरत)। नबियों में हर नबी है — इदरीस, हूद, शुऐब सहित — एक क्रमबद्ध श्रृंखला में।' },
    ],
    hubH1: '25 नबी', hubSub: 'आदम से Muhammad ﷺ तक हर नबी — क्रम से, कहानी, मुख्य घटनाओं, शिक्षाओं और क़ुरानी संदर्भों सहित।',
    searchPh: 'नबी खोजें — जैसे यूसुफ़, मूसा, यूनुस…', badgeN: 'नबी', badge2: 'क्रमवार', badge3: 'केवल क़ुरानी कथाएं',
    waqiatLine: 'कुएं या हिजरत जैसी घटना-कहानियां चाहिए?', waqiatLink: 'वाक़िआत देखें →',
    eraNames: ['आरंभिक', 'पितृगण', 'निर्गमन व राज्य', 'अंतिम श्रृंखला'],
    eraTitles: ['आरंभ (1–5)', 'पितृगण (6–11)', 'निर्गमन व राज्य (12–21)', 'अंतिम श्रृंखला (22–25)'],
    eraSubs: ['आदम से सालेह — मानवता के प्रथम अध्याय।', 'इब्राहीम से यूसुफ़ — राष्ट्रों का परिवार।', 'शुऐब से यूनुस — निर्गमन, राज्य और परीक्षाएं।', 'ज़करिया से Muhammad ﷺ — अंतिम श्रृंखला।'],
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    detSuffix: ' — कहानी व शिक्षाएं', badgeProphet: 'नबी {o} / 25',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', emblemL: 'प्रतीकात्मक आयत', translitL: 'लिप्यंतरण',
    secStory: 'पूरी कहानी', timelineL: 'कहानी क्रम से', reflectL: 'शिक्षाएं', refL: 'संदर्भ:',
    narratedL: 'केवल क़ुरान ({r}) से, बिना किसी मिलावट के वर्णित।',
    consultL: 'क़ुरान से बिना मिलावट के वर्णित; नियमों हेतु विद्वानों से पूछें।',
    waqiatQ: 'घटना-केंद्रित वर्णन चाहिए?', waqiatA: 'वाक़िआत कथा पढ़ें →',
    moreTitle: 'और नबी', moreLink: 'सभी 25 नबी', prevL: '← नबी {o}', nextL: 'नबी {o} →',
    detFaqWho: 'नबी {p} कौन थे?', detFaqLes: '{p} की कहानी से क्या शिक्षाएं मिलती हैं?', detFaqWhere: 'यह कहानी क़ुरान में कहां है?',
  },
  ar: {
    hubTitle: 'الأنبياء الـ25 في الإسلام — القصص مرتبة مع الدروس (25 نبيا)',
    hubDesc: 'جميع الأنبياء الـ25 مرتبين — آدم ونوح وإبراهيم وموسى وداود وسليمان ويونس وعيسى ومحمد ﷺ — بالأحداث والدروس والمراجع القرآنية. لكل نبي صفحته.',
    hubKw: '25 نبي إسلام, قصص الأنبياء مرتبة, قصص الأنبياء, آدم, نوح, إبراهيم, موسى, يوسف, محمد',
    hubFaq: [
      { q: 'كم نبيا مشمولا؟', a: '25 نبيا بالترتيب الزمني من آدم إلى محمد ﷺ. افتح أي نبي للقصة الكاملة بالأحداث والدروس والمراجع القرآنية.' },
      { q: 'من أين أخذت هذه القصص؟', a: 'كل قصة من آيات قرآنية — دون أي إضافات مخترعة. الدروس مأخوذة بوضوح من الآيات؛ استشر العلماء في الأحكام.' },
      { q: 'ما الفرق عن الوقائع؟', a: 'الوقائع تروي الأحداث المشهورة (البئر والنار والهجرة). ومحور الأنبياء يعطي كل نبي — بمن فيهم إدريس وهود وشعيب وذو الكفل وزكريا — في سلسلة زمنية واحدة.' },
    ],
    hubH1: 'الأنبياء الـ25', hubSub: 'كل نبي من آدم إلى محمد ﷺ — مرتبا بالقصة والأحداث الرئيسية والدروس والمراجع القرآنية.',
    searchPh: 'ابحث في الأنبياء — مثل: يوسف، موسى، يونس…', badgeN: 'نبيا', badge2: 'بالترتيب الزمني', badge3: 'روايات قرآنية فقط',
    waqiatLine: 'تريد قصص الأحداث كالبئر أو الهجرة؟', waqiatLink: 'تصفح الوقائع ←',
    eraNames: ['الأوائل', 'الآباء', 'الخروج والملك', 'السلسلة الأخيرة'],
    eraTitles: ['البداية (1-5)', 'الآباء (6-11)', 'الخروج والملك (12-21)', 'السلسلة الأخيرة (22-25)'],
    eraSubs: ['من آدم إلى صالح — الفصول الأولى للبشرية.', 'من إبراهيم إلى يوسف — أسرة الأمم.', 'من شعيب إلى يونس — الخروج والملك والابتلاءات.', 'من زكريا إلى محمد ﷺ — السلسلة الخاتمة.'],
    faqTitle: 'الأسئلة الشائعة',
    detSuffix: ' — القصة والدروس', badgeProphet: 'النبي {o} من 25',
    alsoSearched: 'يُبحث عنها أيضا باسم:', emblemL: 'الآية المميزة', translitL: 'النطق',
    secStory: 'القصة كاملة', timelineL: 'القصة مرتبة', reflectL: 'الدروس', refL: 'المراجع:',
    narratedL: 'مروية من القرآن ({r}) فقط دون أي إضافات مخترعة.',
    consultL: 'مروية من القرآن دون إضافات؛ استشر العلماء في الأحكام.',
    waqiatQ: 'تريد الرواية المرتكزة على الحدث؟', waqiatA: 'اقرأ رواية الوقائع ←',
    moreTitle: 'المزيد من الأنبياء', moreLink: 'جميع الأنبياء الـ25', prevL: '← النبي {o}', nextL: 'النبي {o} →',
    detFaqWho: 'من كان النبي {p}؟', detFaqLes: 'ما الدروس من قصة {p}؟', detFaqWhere: 'أين هذه القصة في القرآن؟',
  },
};

export const SAHABA_UI: Record<string, any> = {
  en: {
    hubTitle: 'Sahaba Stories — Lives of the Prophet’s ﷺ Companions (24 companions)',
    hubDesc: 'All 24 companion stories — Abu Bakr, Umar, Uthman, Ali, Hamza, Bilal, Khalid and more — with events, lessons and references. Each companion has its own page.',
    hubKw: 'sahaba stories, companions of prophet, abu bakr umar uthman ali, khulafa rashidun, bilal hamza khalid, sahaba life lessons, sahabi stories',
    hubFaq: [
      { q: 'Who are covered here?', a: '24 popular companions in order of prominence: the four caliphs, the ten promised Paradise, and beloved figures like Hamza, Bilal, Salman, Abu Hurairah and Khalid. Open any companion for the full story.' },
      { q: 'Where do these stories come from?', a: 'The received seerah (Ibn Hisham/Ibn Ishaq tradition) and Sahih collections, named qualitatively. Lessons are drawn plainly; consult scholars for deeper rulings.' },
      { q: 'How is this different from Seerat?', a: 'Seerat tells the Prophet’s ﷺ own life in 16 chapters. The Sahaba hub tells his companions’ lives — with cross-links both ways.' },
    ],
    hubH1: 'Sahaba — The Companions', hubSub: 'Lives of the men around the Prophet ﷺ — truthfulness, courage, generosity and scholarship. Tap any companion for his own page.',
    searchPh: 'Search companions — e.g. umar, bilal, khalid…', badgeN: 'companions', badge2: 'Makkah + Madinah eras', badge3: 'Seerah-based narratives',
    seeratLine: 'For his life, see the', seeratLink: '16-chapter Seerat →',
    era1: 'Era 1 — Makkah', era1T: 'The First Rank', era1S: 'First believers, cave and shield — the Makkan generation.',
    era2: 'Era 2 — Madinah', era2T: 'Scholars, Scribes & Commanders', era2S: 'The Madinan generation — preservation, counsel and conquests.',
    faqTitle: 'Frequently asked questions',
    detSuffix: ' — Story & Lessons', badgeComp: 'Companion {o} of 24', crumb: 'Sahaba',
    alsoSearched: 'Also searched as:', emblemL: 'Emblematic words', translitL: 'Transliteration',
    secStory: 'The full story', timelineL: 'The life in order', reflectL: 'Lessons', refL: 'References:',
    narratedL: 'Narrated from the seerah and hadith collections without invented details.',
    seeratQ: 'For his life, read the', seeratA: '16-chapter Seerat →',
    moreTitle: 'More companions', moreLink: 'All 24 companions', prevL: '← Companion {o}', nextL: 'Companion {o} →',
    detFaqWho: 'Who was {p}?', detFaqLes: 'What are the lessons from {p}’s life?', detFaqWhere: 'Where is this story sourced from?',
  },
  ur: {
    hubTitle: 'صحابہ کے واقعات — نبی ﷺ کے ساتھیوں کی زندگیاں (24 صحابہ)',
    hubDesc: 'تمام 24 صحابہ کے واقعات — ابوبکر، عمر، عثمان، علی، حمزہ، بلال، خالد و دیگر — واقعات، اسباق اور حوالوں کے ساتھ۔ ہر صحابی کا اپنا صفحہ۔',
    hubKw: 'صحابہ واقعات, نبی کے ساتھی, ابوبکر عمر عثمان علی, خلفائے راشدین, بلال حمزہ خالد',
    hubFaq: [
      { q: 'یہاں کون شامل ہیں؟', a: 'اہمیت کی ترتیب سے 24 مشہور صحابہ: چار خلفاء، عشرہ مبشرہ، اور حمزہ، بلال، سلمان، ابوہریرہ، خالد جیسی پیاری ہستیاں۔' },
      { q: 'یہ واقعات کہاں سے لیے گئے ہیں؟', a: 'مسلمہ سیرت اور صحیح مجموعوں سے — حوالے صفاتی ناموں سے۔ اسباق واضح لیے گئے؛ گہرے مسائل کے لیے علماء سے رجوع کریں۔' },
      { q: 'سیرت سے کیا فرق ہے؟', a: 'سیرت نبی ﷺ کی اپنی زندگی 16 ابواب میں سناتی ہے۔ صحابہ ان کے ساتھیوں کی زندگیاں — دونوں طرف لنکس کے ساتھ۔' },
    ],
    hubH1: 'صحابہ — ساتھی', hubSub: 'نبی ﷺ کے گرد مردوں کی زندگیاں — سچائی، بہادری، سخاوت اور علم۔ کسی بھی صحابی کا صفحہ کھولو۔',
    searchPh: 'ساتھی تلاش کریں — مثلاً عمر، بلال، خالد…', badgeN: 'صحابہ', badge2: 'مکہ + مدینہ ادوار', badge3: 'سیرت پر مبنی واقعات',
    seeratLine: 'ان کی زندگی کے لیے دیکھیں', seeratLink: '16 باب کی سیرت →',
    era1: 'دور 1 — مکہ', era1T: 'پہلی صف', era1S: 'پہلے ایمان لانے والے، غار اور ڈھال — مکی نسل۔',
    era2: 'دور 2 — مدینہ', era2T: 'علماء، کاتب و سپہ سالار', era2S: 'مدنی نسل — حفاظت، مشورہ اور فتوحات۔',
    faqTitle: 'اکثر پوچھے گئے سوالات',
    detSuffix: ' — واقعہ و اسباق', badgeComp: 'صحابی {o} از 24', crumb: 'صحابہ',
    alsoSearched: 'اس نام سے بھی تلاش ہوتا ہے:', emblemL: 'نمایاں الفاظ', translitL: 'تلفظ',
    secStory: 'مکمل واقعہ', timelineL: 'زندگی ترتیب سے', reflectL: 'اسباق', refL: 'حوالے:',
    narratedL: 'سیرت و حدیث کے مجموعوں سے بغیر کسی اضافے کے مروی۔',
    seeratQ: 'ان کی زندگی کے لیے پڑھیں', seeratA: '16 باب کی سیرت →',
    moreTitle: 'مزید صحابہ', moreLink: 'تمام 24 صحابہ', prevL: '← صحابی {o}', nextL: 'صحابی {o} →',
    detFaqWho: '{p} کون تھے؟', detFaqLes: '{p} کی زندگی سے کیا سبق ملتے ہیں؟', detFaqWhere: 'یہ واقعہ کہاں سے ماخوذ ہے؟',
  },
  hi: {
    hubTitle: 'सहाबा कहानियां — नबी ﷺ के साथियों के जीवन (24 सहाबी)',
    hubDesc: 'सभी 24 साथियों की कहानियां — अबू बक्र, उमर, उस्मान, अली, हमज़ा, बिलाल, ख़ालिद आदि — घटनाओं, शिक्षाओं और संदर्भों सहित। हर साथी का अपना पृष्ठ।',
    hubKw: 'सहाबा कहानियां, नबी के साथी, अबू बक्र उमर उस्मान अली, ख़ुलफ़ा राशिदून, बिलाल हमज़ा ख़ालिद',
    hubFaq: [
      { q: 'यहां कौन शामिल हैं?', a: 'प्रमुखता क्रम से 24 प्रसिद्ध साथी: चार ख़लीफ़ा, दस स्वर्ग-सूचित, और हमज़ा, बिलाल, सलमान, अबू हुरैरा, ख़ालिद जैसी प्रिय हस्तियां।' },
      { q: 'ये कहानियां कहां से ली गई हैं?', a: 'प्राप्त सीरत और सहीह संग्रहों से — संदर्भ गुणात्मक नामों से। शिक्षाएं स्पष्ट ली गई हैं; गहरे नियमों हेतु विद्वानों से पूछें।' },
      { q: 'सीरत से क्या अंतर है?', a: 'सीरत नबी ﷺ का अपना जीवन 16 अध्यायों में सुनाती है। सहाबा उनके साथियों के जीवन — दोनों ओर लिंक सहित।' },
    ],
    hubH1: 'सहाबा — साथी', hubSub: 'नबी ﷺ के आसपास पुरुषों के जीवन — सत्यता, साहस, उदारता और विद्वता। किसी भी साथी का पृष्ठ खोलो।',
    searchPh: 'साथी खोजें — जैसे उमर, बिलाल, ख़ालिद…', badgeN: 'सहाबी', badge2: 'मक्का + मदीना युग', badge3: 'सीरत-आधारित कथाएं',
    seeratLine: 'उनके जीवन हेतु देखें', seeratLink: '16-अध्याय सीरत →',
    era1: 'युग 1 — मक्का', era1T: 'प्रथम पंक्ति', era1S: 'प्रथम आस्थावान, गुफा और ढाल — मक्की पीढ़ी।',
    era2: 'युग 2 — मदीना', era2T: 'विद्वान, लेखक व सेनापति', era2S: 'मदनी पीढ़ी — संरक्षण, परामर्श और विजय।',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    detSuffix: ' — कहानी व शिक्षाएं', badgeComp: 'साथी {o} / 24', crumb: 'सहाबा',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', emblemL: 'प्रतीकात्मक शब्द', translitL: 'लिप्यंतरण',
    secStory: 'पूरी कहानी', timelineL: 'जीवन क्रम से', reflectL: 'शिक्षाएं', refL: 'संदर्भ:',
    narratedL: 'सीरत व हदीस संग्रहों से बिना किसी मिलावट के वर्णित।',
    seeratQ: 'उनके जीवन हेतु पढ़ें', seeratA: '16-अध्याय सीरत →',
    moreTitle: 'और साथी', moreLink: 'सभी 24 साथी', prevL: '← साथी {o}', nextL: 'साथी {o} →',
    detFaqWho: '{p} कौन थे?', detFaqLes: '{p} के जीवन से क्या शिक्षाएं मिलती हैं?', detFaqWhere: 'यह कहानी कहां से ली गई है?',
  },
  ar: {
    hubTitle: 'قصص الصحابة — حياة أصحاب النبي ﷺ (24 صحابيا)',
    hubDesc: 'جميع قصص الصحابة الـ24 — أبو بكر وعمر وعثمان وعلي وحمزة وبلال وخالد وغيرهم — بالأحداث والدروس والمراجع. لكل صحابي صفحته.',
    hubKw: 'قصص الصحابة, أصحاب النبي, أبو بكر عمر عثمان علي, الخلفاء الراشدون, بلال حمزة خالد',
    hubFaq: [
      { q: 'من المشمولون هنا؟', a: '24 صحابيا مشهورا بترتيب المكانة: الخلفاء الأربعة والعشرة المبشرون بالجنة وشخصيات محبوبة كحمزة وبلال وسلمان وأبي هريرة وخالد.' },
      { q: 'من أين أخذت هذه القصص؟', a: 'من السيرة المتلقاة والمجاميع الصحيحة المسماة وصفيا. الدروس مأخوذة بوضوح؛ استشر العلماء في الأحكام.' },
      { q: 'ما الفرق عن السيرة؟', a: 'السيرة تروي حياة النبي ﷺ نفسه في 16 فصلا. ومحور الصحابة يروي حياة أصحابه — بروابط في الاتجاهين.' },
    ],
    hubH1: 'الصحابة — الأصحاب', hubSub: 'حياة الرجال حول النبي ﷺ — الصدق والشجاعة والكرم والعلم. افتح صفحة أي صحابي.',
    searchPh: 'ابحث في الصحابة — مثل: عمر، بلال، خالد…', badgeN: 'صحابيا', badge2: 'عهدا مكة والمدينة', badge3: 'روايات مبنية على السيرة',
    seeratLine: 'لحياته انظر', seeratLink: 'السيرة ذات الـ16 فصلا ←',
    era1: 'العهد 1 — مكة', era1T: 'الصف الأول', era1S: 'المؤمنون الأوائل والغار والدرع — الجيل المكي.',
    era2: 'العهد 2 — المدينة', era2T: 'العلماء والكتبة والقادة', era2S: 'الجيل المدني — الحفظ والمشورة والفتوح.',
    faqTitle: 'الأسئلة الشائعة',
    detSuffix: ' — القصة والدروس', badgeComp: 'الصحابي {o} من 24', crumb: 'الصحابة',
    alsoSearched: 'يُبحث عنها أيضا باسم:', emblemL: 'الكلمات المميزة', translitL: 'النطق',
    secStory: 'القصة كاملة', timelineL: 'الحياة مرتبة', reflectL: 'الدروس', refL: 'المراجع:',
    narratedL: 'مروية من السيرة ومجاميع الحديث دون إضافات مخترعة.',
    seeratQ: 'لحياته اقرأ', seeratA: 'السيرة ذات الـ16 فصلا ←',
    moreTitle: 'المزيد من الصحابة', moreLink: 'جميع الصحابة الـ24', prevL: '← الصحابي {o}', nextL: 'الصحابي {o} →',
    detFaqWho: 'من كان {p}؟', detFaqLes: 'ما الدروس من حياة {p}؟', detFaqWhere: 'من أين أخذت هذه القصة؟',
  },
};

export const WOMEN_UI: Record<string, any> = {
  en: {
    hubTitle: 'Women in Islam — Lives of 24 Noble Figures (24 stories)',
    hubDesc: 'Stories of Khadija, Aisha, Fatima, Maryam, Asiya and more — faith, courage and scholarship. Each figure has its own page with events, lessons and references.',
    hubKw: 'women in islam, khadija aisha fatima stories, maryam asiya, muslim women scholars, sahabiyat stories, ladies in islam',
    hubFaq: [
      { q: 'Who are covered here?', a: '24 figures: Maryam and Asiya before Islam, Khadija and the Makkan generation, the Prophet’s ﷺ wives and daughters, and Madinan scholars and defenders. Open any figure for the full story.' },
      { q: 'Where do these stories come from?', a: 'The Quran for Maryam and Asiya, and the received seerah and Sahih collections for the rest — named qualitatively. Virtues and events only; consult scholars for deeper rulings.' },
      { q: 'Why is Karbala not covered?', a: 'By scope: this hub covers lives through the prophetic era. Later history belongs to other books.' },
    ],
    hubH1: 'Women in Islam', hubSub: 'Faith that steadied revelation, courage that converted caliphs, scholarship that taught generations. Tap any figure for her own page.',
    searchPh: 'Search — e.g. khadija, aisha, maryam…', badgeN: 'figures', badge2: 'Quran + Seerah sourced', badge3: 'Virtues & events',
    eraTitles: ['Before Islam — Chosen Women', 'Makkah — First Believers', 'Madinah — Household & Scholars'],
    faqTitle: 'Frequently asked questions',
    detSuffix: ' — Story & Lessons', badgeFig: 'Figure {o} of 24', crumb: 'Women',
    alsoSearched: 'Also searched as:', emblemL: 'Emblematic words', translitL: 'Transliteration',
    secStory: 'The full story', timelineL: 'The life in order', reflectL: 'Lessons', refL: 'References:',
    narratedL: 'Narrated from the Quran, seerah and hadith collections without invented details.',
    sahabaQ: 'For the companions around them, see the', sahabaA: '24 Sahaba →',
    moreTitle: 'More figures', moreLink: 'All 24 figures', prevL: '← Figure {o}', nextL: 'Figure {o} →',
    detFaqWho: 'Who was {p}?', detFaqLes: 'What are the lessons from {p}’s life?', detFaqWhere: 'Where is this story sourced from?',
  },
  ur: {
    hubTitle: 'اسلام میں خواتین — 24 عظیم ہستیوں کی زندگیاں (24 واقعات)',
    hubDesc: 'خدیجہ، عائشہ، فاطمہ، مریم، آسیہ و دیگر کی کہانیاں — ایمان، بہادری اور علم۔ ہر ہستی کا اپنا صفحہ واقعات، اسباق اور حوالوں کے ساتھ۔',
    hubKw: 'اسلام میں خواتین, خدیجہ عائشہ فاطمہ واقعات, مریم آسیہ, مسلم خواتین علماء',
    hubFaq: [
      { q: 'یہاں کون شامل ہیں؟', a: '24 ہستیاں: اسلام سے پہلے مریم و آسیہ، خدیجہ اور مکی نسل، نبی ﷺ کی ازواج و بیٹیاں، اور مدنی علماء و مدافعین۔' },
      { q: 'یہ واقعات کہاں سے لیے گئے ہیں؟', a: 'مریم و آسیہ کے لیے قرآن، باقی کے لیے مسلمہ سیرت و صحیح مجموعے — حوالے صفاتی ناموں سے۔' },
      { q: 'کربلا کیوں شامل نہیں؟', a: 'دائرہ کار سے: یہ مرکز نبوی دور تک کی زندگیاں دیتا ہے۔ بعد کی تاریخ دوسری کتابوں کی ہے۔' },
    ],
    hubH1: 'اسلام میں خواتین', hubSub: 'ایمان جس نے وحی سنبھالی، بہادری جس نے خلیفہ بدلے، علم جس نے نسلیں پڑھائیں۔ کسی بھی ہستی کا صفحہ کھولو۔',
    searchPh: 'تلاش کریں — مثلاً خدیجہ، عائشہ، مریم…', badgeN: 'ہستیاں', badge2: 'قرآن + سیرت ماخذ', badge3: 'فضائل و واقعات',
    eraTitles: ['اسلام سے پہلے — چنی خواتین', 'مکہ — پہلی مومنات', 'مدینہ — گھرانہ و علماء'],
    faqTitle: 'اکثر پوچھے گئے سوالات',
    detSuffix: ' — واقعہ و اسباق', badgeFig: 'ہستی {o} از 24', crumb: 'خواتین',
    alsoSearched: 'اس نام سے بھی تلاش ہوتی ہے:', emblemL: 'نمایاں الفاظ', translitL: 'تلفظ',
    secStory: 'مکمل واقعہ', timelineL: 'زندگی ترتیب سے', reflectL: 'اسباق', refL: 'حوالے:',
    narratedL: 'قرآن، سیرت و حدیث کے مجموعوں سے بغیر کسی اضافے کے مروی۔',
    sahabaQ: 'ان کے گرد ساتھیوں کے لیے دیکھیں', sahabaA: '24 صحابہ →',
    moreTitle: 'مزید ہستیاں', moreLink: 'تمام 24 ہستیاں', prevL: '← ہستی {o}', nextL: 'ہستی {o} →',
    detFaqWho: '{p} کون تھیں؟', detFaqLes: '{p} کی زندگی سے کیا سبق ملتے ہیں؟', detFaqWhere: 'یہ واقعہ کہاں سے ماخوذ ہے؟',
  },
  hi: {
    hubTitle: 'इस्लाम में महिलाएं — 24 महान हस्तियों के जीवन (24 कहानियां)',
    hubDesc: 'ख़दीजा, आइशा, फ़ातिमा, मरयम, आसिया आदि की कहानियां — आस्था, साहस और विद्वता। हर हस्ती का अपना पृष्ठ घटनाओं, शिक्षाओं और संदर्भों सहित।',
    hubKw: 'इस्लाम में महिलाएं, ख़दीजा आइशा फ़ातिमा कहानियां, मरयम आसिया, मुस्लिम महिला विद्वान',
    hubFaq: [
      { q: 'यहां कौन शामिल हैं?', a: '24 हस्तियां: इस्लाम से पहले मरयम व आसिया, ख़दीजा और मक्की पीढ़ी, नबी ﷺ की पत्नियां व बेटियां, और मदनी विद्वान व रक्षिकाएं।' },
      { q: 'ये कहानियां कहां से ली गई हैं?', a: 'मरयम व आसिया हेतु क़ुरान, शेष हेतु प्राप्त सीरत व सहीह संग्रह — संदर्भ गुणात्मक नामों से।' },
      { q: 'कर्बला क्यों शामिल नहीं?', a: 'दायरे से: यह केंद्र नबवी युग तक के जीवन देता है। बाद का इतिहास अन्य पुस्तकों का है।' },
    ],
    hubH1: 'इस्लाम में महिलाएं', hubSub: 'आस्था जिसने वह्य संभाली, साहस जिसने ख़लीफ़ा बदले, विद्वता जिसने पीढ़ियां पढ़ाईं। किसी भी हस्ती का पृष्ठ खोलो।',
    searchPh: 'खोजें — जैसे ख़दीजा, आइशा, मरयम…', badgeN: 'हस्तियां', badge2: 'क़ुरान + सीरत स्रोत', badge3: 'गुण व घटनाएं',
    eraTitles: ['इस्लाम से पहले — चुनी महिलाएं', 'मक्का — प्रथम आस्थावान', 'मदीना — घराना व विद्वान'],
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    detSuffix: ' — कहानी व शिक्षाएं', badgeFig: 'हस्ती {o} / 24', crumb: 'महिलाएं',
    alsoSearched: 'इन नामों से भी खोजा जाता है:', emblemL: 'प्रतीकात्मक शब्द', translitL: 'लिप्यंतरण',
    secStory: 'पूरी कहानी', timelineL: 'जीवन क्रम से', reflectL: 'शिक्षाएं', refL: 'संदर्भ:',
    narratedL: 'क़ुरान, सीरत व हदीस संग्रहों से बिना किसी मिलावट के वर्णित।',
    sahabaQ: 'उनके आसपास साथियों हेतु देखें', sahabaA: '24 सहाबा →',
    moreTitle: 'और हस्तियां', moreLink: 'सभी 24 हस्तियां', prevL: '← हस्ती {o}', nextL: 'हस्ती {o} →',
    detFaqWho: '{p} कौन थीं?', detFaqLes: '{p} के जीवन से क्या शिक्षाएं मिलती हैं?', detFaqWhere: 'यह कहानी कहां से ली गई है?',
  },
  ar: {
    hubTitle: 'المرأة في الإسلام — حياة 24 شخصية نبيلة (24 قصة)',
    hubDesc: 'قصص خديجة وعائشة وفاطمة ومريم وآسية وغيرهن — الإيمان والشجاعة والعلم. لكل شخصية صفحتها بالأحداث والدروس والمراجع.',
    hubKw: 'المرأة في الإسلام, خديجة عائشة فاطمة قصص, مريم آسية, عالمات مسلمات',
    hubFaq: [
      { q: 'من المشمولات هنا؟', a: '24 شخصية: مريم وآسية قبل الإسلام وخديجة والجيل المكي وزوجات النبي ﷺ وبناته والعالمات والمدافعات في المدينة.' },
      { q: 'من أين أخذت هذه القصص؟', a: 'القرآن لمريم وآسية والسيرة المتلقاة والمجاميع الصحيحة للبقية — مسماة وصفيا.' },
      { q: 'لماذا لا تشمل كربلاء؟', a: 'بحكم النطاق: يغطي هذا المحور الحياة حتى العهد النبوي. والتاريخ اللاحق لكتب أخرى.' },
    ],
    hubH1: 'المرأة في الإسلام', hubSub: 'إيمان ثبت الوحي وشجاعة حولت الخلفاء وعلم علم الأجيال. افتحي صفحة أي شخصية.',
    searchPh: 'ابحثي — مثل: خديجة، عائشة، مريم…', badgeN: 'شخصية', badge2: 'مصادر القرآن والسيرة', badge3: 'الفضائل والأحداث',
    eraTitles: ['قبل الإسلام — المختارات', 'مكة — أول المؤمنات', 'المدينة — البيت والعالمات'],
    faqTitle: 'الأسئلة الشائعة',
    detSuffix: ' — القصة والدروس', badgeFig: 'الشخصية {o} من 24', crumb: 'المرأة',
    alsoSearched: 'يُبحث عنها أيضا باسم:', emblemL: 'الكلمات المميزة', translitL: 'النطق',
    secStory: 'القصة كاملة', timelineL: 'الحياة مرتبة', reflectL: 'الدروس', refL: 'المراجع:',
    narratedL: 'مروية من القرآن والسيرة ومجاميع الحديث دون إضافات مخترعة.',
    sahabaQ: 'للصحابة حولهن انظري', sahabaA: 'الصحابة الـ24 ←',
    moreTitle: 'المزيد من الشخصيات', moreLink: 'جميع الشخصيات الـ24', prevL: '← الشخصية {o}', nextL: 'الشخصية {o} →',
    detFaqWho: 'من كانت {p}؟', detFaqLes: 'ما الدروس من حياة {p}؟', detFaqWhere: 'من أين أخذت هذه القصة؟',
  },
};

/* Names of Allah + Names of Muhammad ﷺ hubs and detail pages (en/hi/ur/ar). */
export const ALLAH_UI: Record<string, any> = {
  en: {
    hubTitle: '99 Names of Allah (Asma-ul-Husna) with Meaning',
    hubDesc: 'All 99 names of Allah (Asma-ul-Husna) in Arabic with transliteration and English meaning — from Ar-Rahman to As-Sabur. Open any name for its own page.',
    hubKw: '99 names of allah, asma ul husna, allah names with meaning, ar rahman, ar rahim, al malik, as sabur',
    hubH1: '99 Names of Allah', hubSub: 'Asma-ul-Husna — the beautiful names in the well-known order. Tap any name for its own page with meaning, source and related resources.',
    filterPh: 'Filter names — e.g. rahman, forgiver, light…', badgeN: '99 names', badge2: 'Arabic + transliteration + meaning',
    hubFaq: [
      { q: 'How many names of Allah are there?', a: 'Allah has ninety-nine names — one hundred minus one — and whoever learns them by heart will enter Paradise (Sahih al-Bukhari, Sahih Muslim). All 99 are listed above in the well-known order.' },
      { q: 'What is the greatest name of Allah?', a: 'Scholars differ over which is the greatest name (Ism-e-Azam). Learn all the names, call upon Allah by them, and consult scholars for details.' },
      { q: 'How should I learn the 99 names?', a: 'Read a few daily with their meanings, revise often, and use them in dua — for example calling upon Ya Rahman, Ya Rahim, Ya Ghaffar.' },
    ],
    keepTitle: 'Keep learning', otherH1: '99 Names of Prophet Muhammad ﷺ', otherSub: 'Arabic, transliteration and meaning',
    duasH1: 'Duas for everyday life', duasSub: 'Call upon Allah by His beautiful names',
    detTitle: '{t} — Meaning, Source & Details', detDesc: '{t} ({m}) — one of the 99 names of Allah: Arabic, transliteration, meaning, source and related resources.',
    badgeDet: 'Name {n} of 99', meaningL: 'Meaning', srcL: 'Source',
    srcNote: 'The well-known Tirmidhi enumeration of the 99 names (Allah, then Ar-Rahman … As-Sabur). Meanings are short, literal and widely agreed — no rulings added.',
    faqTitle: 'Frequently asked questions',
    crumb: 'Names of Allah',
    faqMeaningQ: 'What does {t} mean?', faqSrcQ: 'Where is this name from?', faqUseQ: 'How do I use the names of Allah?',
    faqUseA: 'Learn a few names daily with their meanings, revise often, and call upon Allah by them in dua — for example Ya Rahman, Ya Rahim, Ya Ghaffar.',
    prevL: '← Previous name', nextL: 'Next name →', hubLink: 'All 99 names',
  },
  ur: {
    hubTitle: 'اللہ کے 99 نام (اسماء الحسنیٰ) معانی کے ساتھ',
    hubDesc: 'اللہ کے تمام 99 نام (اسماء الحسنیٰ) عربی متن، تلفظ اور ترجمے کے ساتھ — الرحمن سے الصبور تک۔ کسی بھی نام کا اپنا صفحہ کھولو۔',
    hubKw: '99 names of allah, اسماء الحسنیٰ, اللہ کے نام معانی, الرحمن, الرحیم, الملک, الصبور',
    hubH1: 'اللہ کے 99 نام', hubSub: 'اسماء الحسنیٰ — مشہور ترتیب میں خوبصورت نام۔ کسی بھی نام کا اپنا صفحہ معنی، حوالے اور متعلقہ مواد کے ساتھ کھولو۔',
    filterPh: 'نام تلاش کرو — مثلاً رحمن، بخشنے والا، نور…', badgeN: '99 نام', badge2: 'عربی + تلفظ + معنی',
    hubFaq: [
      { q: 'اللہ کے کتنے نام ہیں؟', a: 'اللہ کے ننانوے نام ہیں — سو میں سے ایک کم — اور جو انہیں یاد کرے گا جنت میں داخل ہوگا (صحیح بخاری، صحیح مسلم)۔ تمام 99 مشہور ترتیب میں اوپر درج ہیں۔' },
      { q: 'اللہ کا سب سے بڑا نام کونسا ہے؟', a: 'علماء میں اختلاف ہے کہ اسم اعظم کونسا ہے۔ تمام نام سیکھو، انہی سے اللہ کو پکارو، تفصیل کے لیے علماء سے رجوع کرو۔' },
      { q: '99 نام کیسے یاد کروں؟', a: 'روز چند نام معانی کے ساتھ پڑھو، دہراؤ، اور دعا میں انہی سے پکارو — مثلاً یا رحمن، یا رحیم، یا غفار۔' },
    ],
    keepTitle: 'سیکھنا جاری رکھو', otherH1: 'حضرت محمد ﷺ کے 99 نام', otherSub: 'عربی، تلفظ اور معنی',
    duasH1: 'روزمرہ کی دعائیں', duasSub: 'اللہ کو اس کے خوبصورت ناموں سے پکارو',
    detTitle: '{t} — معنی، حوالہ و تفصیل', detDesc: '{t} ({m}) — اللہ کے 99 ناموں میں سے ایک: عربی، تلفظ، معنی، حوالہ اور متعلقہ مواد۔',
    badgeDet: '99 میں سے نام {n}', meaningL: 'معنی', srcL: 'حوالہ',
    srcNote: '99 ناموں کی مشہور ترمذی ترتیب (اللہ، پھر الرحمن … الصبور)۔ معانی مختصر، لفظی اور متفقہ ہیں — کوئی مسئلہ شامل نہیں۔',
    faqTitle: 'اکثر پوچھے گئے سوالات',
    crumb: 'اللہ کے نام',
    faqMeaningQ: '{t} کا کیا مطلب ہے؟', faqSrcQ: 'یہ نام کہاں سے ہے؟', faqUseQ: 'اللہ کے نام کیسے استعمال کروں؟',
    faqUseA: 'روز چند نام معانی سمیت سیکھو، دہراتے رہو، اور دعا میں انہی سے اللہ کو پکارو — مثلاً یا رحمن، یا رحیم، یا غفار۔',
    prevL: '← پچھلا نام', nextL: 'اگلا نام →', hubLink: 'تمام 99 نام',
  },
  hi: {
    hubTitle: 'अल्लाह के 99 नाम (अस्मा-उल-हुस्ना) अर्थ सहित',
    hubDesc: 'अल्लाह के सभी 99 नाम (अस्मा-उल-हुस्ना) अरबी, लिप्यंतरण और अर्थ सहित — अर-रहमान से अस-सबूर तक। किसी भी नाम का अपना पृष्ठ खोलो।',
    hubKw: '99 names of allah, अस्मा उल हुस्ना, अल्लाह के नाम अर्थ सहित, अर रहमान, अर रहीम, अल मलिक, अस सबूर',
    hubH1: 'अल्लाह के 99 नाम', hubSub: 'अस्मा-उल-हुस्ना — प्रसिद्ध क्रम में सुंदर नाम। किसी भी नाम का अपना पृष्ठ अर्थ, स्रोत और संबंधित सामग्री सहित खोलो।',
    filterPh: 'नाम खोजें — जैसे रहमान, क्षमा करने वाला, नूर…', badgeN: '99 नाम', badge2: 'अरबी + लिप्यंतरण + अर्थ',
    hubFaq: [
      { q: 'अल्लाह के कितने नाम हैं?', a: 'अल्लाह के निन्यानवे नाम हैं — सौ में से एक कम — और जो इन्हें याद करेगा वह जन्नत में जाएगा (सहीह बुखारी, सहीह मुस्लिम)। सभी 99 प्रसिद्ध क्रम में ऊपर दिए हैं।' },
      { q: 'अल्लाह का सबसे बड़ा नाम कौनसा है?', a: 'विद्वानों में मतभेद है कि इस्मे आज़म कौनसा है। सभी नाम सीखो, उन्हीं से अल्लाह को पुकारो, विस्तार हेतु विद्वानों से पूछो।' },
      { q: '99 नाम कैसे याद करूं?', a: 'रोज़ कुछ नाम अर्थ सहित पढ़ो, दोहराओ, और दुआ में उन्हीं से पुकारो — जैसे या रहमान, या रहीम, या ग़फ़्फ़ार।' },
    ],
    keepTitle: 'सीखना जारी रखो', otherH1: 'हज़रत मुहम्मद ﷺ के 99 नाम', otherSub: 'अरबी, लिप्यंतरण और अर्थ',
    duasH1: 'रोज़मर्रा की दुआएं', duasSub: 'अल्लाह को उसके सुंदर नामों से पुकारो',
    detTitle: '{t} — अर्थ, स्रोत व विवरण', detDesc: '{t} ({m}) — अल्लाह के 99 नामों में से एक: अरबी, लिप्यंतरण, अर्थ, स्रोत और संबंधित सामग्री।',
    badgeDet: '99 में से नाम {n}', meaningL: 'अर्थ', srcL: 'स्रोत',
    srcNote: '99 नामों की प्रसिद्ध तिर्मिज़ी सूची (अल्लाह, फिर अर-रहमान … अस-सबूर)। अर्थ संक्षिप्त, शाब्दिक और सर्वमान्य हैं — कोई नियम नहीं जोड़े गए।',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    crumb: 'अल्लाह के नाम',
    faqMeaningQ: '{t} का क्या अर्थ है?', faqSrcQ: 'यह नाम कहां से है?', faqUseQ: 'अल्लाह के नामों का उपयोग कैसे करूं?',
    faqUseA: 'रोज़ कुछ नाम अर्थ सहित सीखो, दोहराते रहो, और दुआ में उन्हीं से अल्लाह को पुकारो — जैसे या रहमान, या रहीम, या ग़फ़्फ़ार।',
    prevL: '← पिछला नाम', nextL: 'अगला नाम →', hubLink: 'सभी 99 नाम',
  },
  ar: {
    hubTitle: 'أسماء الله الـ99 (الحسنى) مع المعاني',
    hubDesc: 'جميع أسماء الله الـ99 (الحسنى) بالنص العربي والنطق والمعنى — من الرحمن إلى الصبور. افتح أي اسم لصفحته الخاصة.',
    hubKw: '99 names of allah, أسماء الله الحسنى, معاني أسماء الله, الرحمن, الرحيم, الملك, الصبور',
    hubH1: 'أسماء الله الـ99', hubSub: 'الأسماء الحسنى — بالترتيب المشهور. اضغط أي اسم لصفحته الخاصة بالمعنى والمصدر والموارد ذات الصلة.',
    filterPh: 'رشح الأسماء — مثل: رحمن، الغفور، النور…', badgeN: '99 اسما', badge2: 'العربية + النطق + المعنى',
    hubFaq: [
      { q: 'كم عدد أسماء الله؟', a: 'لله تسعة وتسعون اسما — مائة إلا واحدا — ومن أحصاها دخل الجنة (صحيح البخاري وصحيح مسلم). وجميعها مذكورة أعلاه بالترتيب المشهور.' },
      { q: 'ما أعظم أسماء الله؟', a: 'اختلف العلماء في الاسم الأعظم. تعلم جميع الأسماء وادع الله بها واستشر العلماء في التفاصيل.' },
      { q: 'كيف أحفظ الأسماء الـ99؟', a: 'اقرأ كل يوم بضعة أسماء بمعانيها وراجعها كثيرا وادع الله بها — مثل: يا رحمن يا رحيم يا غفار.' },
    ],
    keepTitle: 'واصل التعلم', otherH1: 'أسماء النبي محمد ﷺ الـ99', otherSub: 'العربية والنطق والمعنى',
    duasH1: 'أدعية الحياة اليومية', duasSub: 'ادع الله بأسمائه الحسنى',
    detTitle: '{t} — المعنى والمصدر والتفاصيل', detDesc: '{t} ({m}) — من أسماء الله الـ99: النص العربي والنطق والمعنى والمصدر والموارد ذات الصلة.',
    badgeDet: 'الاسم {n} من 99', meaningL: 'المعنى', srcL: 'المصدر',
    srcNote: 'الترتيب المشهور لأسماء الـ99 في الترمذي (الله ثم الرحمن … الصبور). المعاني مختصرة حرفية ومتفق عليها — دون أحكام مضافة.',
    faqTitle: 'الأسئلة الشائعة',
    crumb: 'أسماء الله',
    faqMeaningQ: 'ما معنى {t}؟', faqSrcQ: 'من أين هذا الاسم؟', faqUseQ: 'كيف أستعمل أسماء الله؟',
    faqUseA: 'تعلم كل يوم بضعة أسماء بمعانيها وراجعها وادع الله بها — مثل: يا رحمن يا رحيم يا غفار.',
    prevL: '← الاسم السابق', nextL: 'الاسم التالي →', hubLink: 'جميع الأسماء الـ99',
  },
};

export const PROPHET_UI_NAMES: Record<string, any> = {
  en: {
    hubTitle: '99 Names of Prophet Muhammad ﷺ with Meaning',
    hubDesc: 'All 99 names and titles of Prophet Muhammad ﷺ in Arabic with transliteration and English meaning — Muhammad, Ahmad, Mustafa and more. Open any name for its own page.',
    hubKw: '99 names of prophet muhammad, asma un nabi, muhammad ahmad mustafa, prophet names with meaning',
    hubH1: '99 Names of Prophet Muhammad ﷺ', hubSub: 'Asma-un-Nabi — his names and titles from the Quran, hadith and classical descriptions. Tap any name for its own page.',
    filterPh: 'Filter names — e.g. ahmad, guide, mercy…', badgeN: '99 names', badge2: 'Arabic + transliteration + meaning',
    hubFaq: [
      { q: 'How many names does Prophet Muhammad ﷺ have?', a: 'Classical scholars compiled many names and titles from the Quran, hadith and Arabic descriptions. This page gathers 99 widely transmitted ones — Muhammad, Ahmad, Mustafa, Bashir, Nadhir and more.' },
      { q: 'Are these names from hadith?', a: 'Several come directly from the Quran and authentic hadith (Muhammad, Ahmad, Shahid, Bashir, Nadhir, Siraj Munir, Mahi, Hashir, Aqib). Others are classical titles describing his attributes. Unlike the 99 Names of Allah, there is no single canonical enumeration.' },
      { q: 'Why learn the names of the Prophet ﷺ?', a: 'Knowing his names deepens love and understanding of his mission — the praiser, the warner, the guide, the mercy to the worlds.' },
    ],
    keepTitle: 'Keep learning', otherH1: '99 Names of Allah', otherSub: 'Arabic, transliteration and meaning',
    duasH1: 'Duas for everyday life', duasSub: 'Send blessings upon the Prophet ﷺ',
    detTitle: '{t} — Meaning, Source & Details', detDesc: '{t} ({m}) — a name of Prophet Muhammad ﷺ: Arabic, transliteration, meaning, source-kind and related resources.',
    badgeDet: 'Name {n} of 99',
    meaningL: 'Meaning', crumb: 'Names of Muhammad ﷺ',
    kindQuranic: 'Quranic title', kindHadith: 'Prophetic epithet', kindTraditional: 'Classical attribute',
    srcQuranic: 'A Quranic title — among the names the repository notes as Quranic titles.',
    srcHadith: 'A Prophetic epithet — among the names the repository notes as coming from hadith.',
    srcTraditional: 'A classical attribute — from scholarly lists of his attributes. Unlike the 99 Names of Allah, there is no single canonical enumeration.',
    faqTitle: 'Frequently asked questions',
    faqMeaningQ: 'What does {t} mean?', faqSrcQ: 'Where is this name from?', faqUseQ: 'Why learn the names of the Prophet ﷺ?',
    faqUseA: 'Knowing his names deepens love and understanding of his mission — the praiser, the warner, the guide, the mercy to the worlds.',
    prevL: '← Previous name', nextL: 'Next name →', hubLink: 'All 99 names',
  },
  ur: {
    hubTitle: 'حضرت محمد ﷺ کے 99 نام معانی کے ساتھ',
    hubDesc: 'حضرت محمد ﷺ کے تمام 99 نام و القاب عربی متن، تلفظ اور ترجمے کے ساتھ — محمد، احمد، مصطفیٰ اور مزید۔ کسی بھی نام کا اپنا صفحہ کھولو۔',
    hubKw: '99 names of prophet muhammad, اسماء النبی, محمد احمد مصطفیٰ, نبی کے نام معانی',
    hubH1: 'حضرت محمد ﷺ کے 99 نام', hubSub: 'اسماء النبی — قرآن، حدیث اور کلاسیکی توصیفات سے ان کے نام و القاب۔ کسی بھی نام کا اپنا صفحہ کھولو۔',
    filterPh: 'نام تلاش کرو — مثلاً احمد، ہادی، رحمت…', badgeN: '99 نام', badge2: 'عربی + تلفظ + معنی',
    hubFaq: [
      { q: 'حضرت محمد ﷺ کے کتنے نام ہیں؟', a: 'علماء نے قرآن، حدیث اور عربی توصیفات سے بہت سے نام و القاب جمع کیے۔ یہ صفحہ 99 مشہور نام جمع کرتا ہے — محمد، احمد، مصطفیٰ، بشیر، نذیر اور مزید۔' },
      { q: 'کیا یہ نام حدیث سے ہیں؟', a: 'کئی براہ راست قرآن و صحیح حدیث سے ہیں (محمد، احمد، شاہد، بشیر، نذیر، سراج منیر، ماحی، حاشر، عاقب)۔ باقی ان کی صفات کے کلاسیکی القاب ہیں۔ اللہ کے 99 ناموں کے برعکس اس کی کوئی واحد مستند فہرست نہیں۔' },
      { q: 'نبی ﷺ کے نام کیوں سیکھوں؟', a: 'ان کے نام جاننے سے ان کے مشن سے محبت اور سمجھ بڑھتی ہے — حمد کرنے والے، ڈرانے والے، ہادی، رحمت للعالمین۔' },
    ],
    keepTitle: 'سیکھنا جاری رکھو', otherH1: 'اللہ کے 99 نام', otherSub: 'عربی، تلفظ اور معنی',
    duasH1: 'روزمرہ کی دعائیں', duasSub: 'نبی ﷺ پر درود بھیجو',
    detTitle: '{t} — معنی، حوالہ و تفصیل', detDesc: '{t} ({m}) — حضرت محمد ﷺ کا ایک نام: عربی، تلفظ، معنی، ماخذ کی قسم اور متعلقہ مواد۔',
    badgeDet: '99 میں سے نام {n}',
    meaningL: 'معنی', crumb: 'محمد ﷺ کے نام',
    kindQuranic: 'قرآنی لقب', kindHadith: 'حدیثی لقب', kindTraditional: 'کلاسیکی وصف',
    srcQuranic: 'قرآنی لقب — ان ناموں میں سے جنہیں ذخیرہ قرآنی القاب بتاتا ہے۔',
    srcHadith: 'حدیثی لقب — ان ناموں میں سے جنہیں ذخیرہ حدیث سے بتاتا ہے۔',
    srcTraditional: 'کلاسیکی وصف — ان کی صفات کی علمی فہرستوں سے۔ اللہ کے 99 ناموں کے برعکس اس کی کوئی واحد مستند فہرست نہیں۔',
    faqTitle: 'اکثر پوچھے گئے سوالات',
    faqMeaningQ: '{t} کا کیا مطلب ہے؟', faqSrcQ: 'یہ نام کہاں سے ہے؟', faqUseQ: 'نبی ﷺ کے نام کیوں سیکھوں؟',
    faqUseA: 'ان کے نام جاننے سے ان کے مشن سے محبت اور سمجھ بڑھتی ہے — حمد کرنے والے، ڈرانے والے، ہادی، رحمت للعالمین۔',
    prevL: '← پچھلا نام', nextL: 'اگلا نام →', hubLink: 'تمام 99 نام',
  },
  hi: {
    hubTitle: 'हज़रत मुहम्मद ﷺ के 99 नाम अर्थ सहित',
    hubDesc: 'हज़रत मुहम्मद ﷺ के सभी 99 नाम व उपाधियां अरबी, लिप्यंतरण और अर्थ सहित — मुहम्मद, अहमद, मुस्तफ़ा और अन्य। किसी भी नाम का अपना पृष्ठ खोलो।',
    hubKw: '99 names of prophet muhammad, अस्मा उन नबी, मुहम्मद अहमद मुस्तफा, नबी के नाम अर्थ सहित',
    hubH1: 'हज़रत मुहम्मद ﷺ के 99 नाम', hubSub: 'अस्मा-उन-नबी — क़ुरान, हदीस व शास्त्रीय वर्णनों से उनके नाम व उपाधियां। किसी भी नाम का अपना पृष्ठ खोलो।',
    filterPh: 'नाम खोजें — जैसे अहमद, हादी, रहमत…', badgeN: '99 नाम', badge2: 'अरबी + लिप्यंतरण + अर्थ',
    hubFaq: [
      { q: 'हज़रत मुहम्मद ﷺ के कितने नाम हैं?', a: 'विद्वानों ने क़ुरान, हदीस व अरबी वर्णनों से अनेक नाम व उपाधियां संकलित कीं। यह पृष्ठ 99 प्रसिद्ध नाम देता है — मुहम्मद, अहमद, मुस्तफ़ा, बशीर, नज़ीर व अन्य।' },
      { q: 'क्या ये नाम हदीस से हैं?', a: 'कई सीधे क़ुरान व प्रामाणिक हदीस से हैं (मुहम्मद, अहमद, शाहिद, बशीर, नज़ीर, सिराज मुनीर, माही, हाशिर, आक़िब)। शेष उनकी विशेषताओं की शास्त्रीय उपाधियां हैं। अल्लाह के 99 नामों जैसी कोई एकल प्रामाणिक सूची नहीं है।' },
      { q: 'नबी ﷺ के नाम क्यों सीखूं?', a: 'उनके नाम जानने से उनके मिशन से प्रेम व समझ बढ़ती है — प्रशंसा करने वाले, चेतावनी देने वाले, मार्गदर्शक, समस्त लोकों हेतु दया।' },
    ],
    keepTitle: 'सीखना जारी रखो', otherH1: 'अल्लाह के 99 नाम', otherSub: 'अरबी, लिप्यंतरण और अर्थ',
    duasH1: 'रोज़मर्रा की दुआएं', duasSub: 'नबी ﷺ पर दरूद भेजो',
    detTitle: '{t} — अर्थ, स्रोत व विवरण', detDesc: '{t} ({m}) — हज़रत मुहम्मद ﷺ का एक नाम: अरबी, लिप्यंतरण, अर्थ, स्रोत-प्रकार और संबंधित सामग्री।',
    badgeDet: '99 में से नाम {n}',
    meaningL: 'अर्थ', crumb: 'मुहम्मद ﷺ के नाम',
    kindQuranic: 'क़ुरानी उपाधि', kindHadith: 'हदीस उपाधि', kindTraditional: 'शास्त्रीय विशेषता',
    srcQuranic: 'क़ुरानी उपाधि — उन नामों में से जिन्हें भंडार क़ुरानी उपाधियां बताता है।',
    srcHadith: 'हदीस उपाधि — उन नामों में से जिन्हें भंडार हदीस से बताता है।',
    srcTraditional: 'शास्त्रीय विशेषता — उनकी विशेषताओं की विद्वतापूर्ण सूचियों से। अल्लाह के 99 नामों जैसी कोई एकल प्रामाणिक सूची नहीं है।',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqMeaningQ: '{t} का क्या अर्थ है?', faqSrcQ: 'यह नाम कहां से है?', faqUseQ: 'नबी ﷺ के नाम क्यों सीखूं?',
    faqUseA: 'उनके नाम जानने से उनके मिशन से प्रेम व समझ बढ़ती है — प्रशंसा करने वाले, चेतावनी देने वाले, मार्गदर्शक, समस्त लोकों हेतु दया।',
    prevL: '← पिछला नाम', nextL: 'अगला नाम →', hubLink: 'सभी 99 नाम',
  },
  ar: {
    hubTitle: 'أسماء النبي محمد ﷺ الـ99 مع المعاني',
    hubDesc: 'جميع أسماء النبي محمد ﷺ وألقابه الـ99 بالنص العربي والنطق والمعنى — محمد وأحمد ومصطفى وغيرها. افتح أي اسم لصفحته الخاصة.',
    hubKw: '99 names of prophet muhammad, أسماء النبي, محمد أحمد مصطفى, معاني أسماء النبي',
    hubH1: 'أسماء النبي محمد ﷺ الـ99', hubSub: 'أسماء النبي — أسماؤه وألقابه من القرآن والحديث والأوصاف الكلاسيكية. اضغط أي اسم لصفحته الخاصة.',
    filterPh: 'رشح الأسماء — مثل: أحمد، الهادي، الرحمة…', badgeN: '99 اسما', badge2: 'العربية + النطق + المعنى',
    hubFaq: [
      { q: 'كم عدد أسماء النبي محمد ﷺ؟', a: 'جمع العلماء أسماء وألقابا كثيرة من القرآن والحديث والأوصاف العربية. تجمع هذه الصفحة 99 اسما مشهورا — محمد وأحمد ومصطفى وبشير ونذير وغيرها.' },
      { q: 'هل هذه الأسماء من الحديث؟', a: 'عدة منها من القرآن والحديث الصحيح مباشرة (محمد وأحمد وشاهد وبشير ونذير وسراج منير وماح وحاشر وعاقب). والبقية ألقاب كلاسيكية تصف صفاته. وعلى خلاف أسماء الله الـ99 لا يوجد إحصاء واحد معتمد.' },
      { q: 'لماذا أتعلم أسماء النبي ﷺ؟', a: 'معرفة أسمائه تزيد المحبة والفهم لرسالته — الحامد والنذير والهادي ورحمة للعالمين.' },
    ],
    keepTitle: 'واصل التعلم', otherH1: 'أسماء الله الـ99', otherSub: 'العربية والنطق والمعنى',
    duasH1: 'أدعية الحياة اليومية', duasSub: 'صل على النبي ﷺ',
    detTitle: '{t} — المعنى والمصدر والتفاصيل', detDesc: '{t} ({m}) — من أسماء النبي محمد ﷺ: النص العربي والنطق والمعنى ونوع المصدر والموارد ذات الصلة.',
    badgeDet: 'الاسم {n} من 99',
    meaningL: 'المعنى', crumb: 'أسماء النبي ﷺ',
    kindQuranic: 'لقب قرآني', kindHadith: 'لقب نبوي', kindTraditional: 'وصف كلاسيكي',
    srcQuranic: 'لقب قرآني — من الأسماء التي يذكرها المخزون كألقاب قرآنية.',
    srcHadith: 'لقب نبوي — من الأسماء التي يذكرها المخزون من الحديث.',
    srcTraditional: 'وصف كلاسيكي — من قوائم العلماء لصفاته. وعلى خلاف أسماء الله الـ99 لا يوجد إحصاء واحد معتمد.',
    faqTitle: 'الأسئلة الشائعة',
    faqMeaningQ: 'ما معنى {t}؟', faqSrcQ: 'من أين هذا الاسم؟', faqUseQ: 'لماذا أتعلم أسماء النبي ﷺ؟',
    faqUseA: 'معرفة أسمائه تزيد المحبة والفهم لرسالته — الحامد والنذير والهادي ورحمة للعالمين.',
    prevL: '← الاسم السابق', nextL: 'الاسم التالي →', hubLink: 'جميع الأسماء الـ99',
  },
};
