/* Hikmah Noor — topic hub chrome localization (Phase 3).
 * Ramadan / Eid / Hajj / Umrah / Calendar hubs + Hijri month pages
 * in en/hi/ur/ar. English strings reuse current hub pages byte-for-byte.
 * Only verified facts; no invented rulings, dates or virtues.
 */

export const RAMADAN_UI: Record<string, any> = {
  en: {
    hubTitle: 'Ramadan Guide — Fasting Rules, Moon Sighting, Itikaf, Laylatul Qadr, Fitrana & Sehri Times',
    hubDesc: 'Everything for Ramadan: moon sighting, fasting rules, itikaf, Laylatul Qadr, last-10-nights plan, Taraweeh, khatm schedule, fitrana, fidyah, countdown and prayer times.',
    hubKw: 'ramadan guide, roza rules, chand dekhne ka tarika, sehri dua, iftar dua, taraweeh method, itikaf ka tarika, laylatul qadr dua, shab e qadr, fitrana kitna hai, fidyah amount, quran khatm plan, ramadan countdown, sehri iftar time, zakat al fitr',
    hubFaq: [
      { q: 'How is Ramadan dated each year?', a: 'By moon sighting — Ramadan begins with the crescent sighting and ends with Shawwal’s. See our moon-sighting guide for the hilal rules. Dates vary by country; follow local scholars and moon committees, not apps alone.' },
      { q: 'When do sehri and iftar happen?', a: 'Sehri ends at Fajr (true dawn) and iftar begins at Maghrib (sunset). Use the prayer-times tool for your city’s exact times.' },
      { q: 'How do I find Laylatul Qadr?', a: 'Worship all of the last ten nights — most hoped on the odd nights — with prayer, Quran and the Allahumma innaka afuwwun supplication. Our last-10-nights plan gives a repeatable nightly template.' },
      { q: 'How much is fitrana and when is it paid?', a: 'One sa’ (~2.5-3kg) of staple food per person, paid in Ramadan’s last days and before the Eid prayer. See the Zakat al-Fitr guide and calculator.' },
    ],
    crumb: 'Ramadan', badge1: 'Ramadan hub', badge2: 'Guides + Duas + Tools',
    hubH1: 'Ramadan Guide',
    hubSub: 'Fasting rules, sehri and iftar duas, Taraweeh method, Laylatul Qadr, countdown and prayer times — everything for the month in one place.',
    crossL: 'For pilgrimage rites, see the', crossHajj: 'Hajj & Umrah Guide →', crossMid: 'For Eid prayer, takbeer and Qurbani, see the', crossEid: 'Eid Guide (Fitr & Adha) →',
    btnCountdown: 'Ramadan countdown', btnTimes: 'Sehri & iftar times',
    secGuides: 'Guides', secGuidesT: 'Fasting & worship guides', allGuides: 'All guides',
    secDuas: 'Duas', secDuasT: 'Ramadan duas', allDuas: 'All Ramadan duas',
    secKeyDuas: 'Key duas', secKeyDuasT: 'Sehri, iftar & Qadr',
    secQuiz: 'Quiz', secQuizT: 'Test your Ramadan knowledge', quizLink: 'Ramadan quiz',
    secTools: 'Tools', secToolsT: 'Ramadan tools', allTools: 'All tools',
    secMonth: 'Calendar', secMonthT: 'Ramadan in the Hijri calendar', monthLink: 'Ramadan — the 9th month',
    faqTitle: 'Frequently asked questions',
  },
  ur: {
    hubTitle: 'رمضان گائیڈ — روزے کے احکام، چاند، اعتکاف، شب قدر، فطرانہ و سحری افطار',
    hubDesc: 'رمضان کے لیے سب کچھ: چاند دیکھنا، روزے کے احکام، اعتکاف، شب قدر، آخری عشرے کا معمول، تراویح، ختم کا شیڈول، فطرانہ، فدیہ، کاؤنٹ ڈاؤن اور نماز کے اوقات۔',
    hubKw: 'ramadan guide, roza rules, chand dekhne ka tarika, sehri dua, iftar dua, taraweeh method, itikaf ka tarika, laylatul qadr dua, shab e qadr, fitrana kitna hai, fidyah amount, quran khatm plan, ramadan countdown, sehri iftar time, zakat al fitr',
    hubFaq: [
      { q: 'رمضان کی تاریخ ہر سال کیسے طے ہوتی ہے؟', a: 'چاند دیکھ کر — رمضان ہلال دیکھنے سے شروع ہوتا ہے اور شوال کے چاند پر ختم۔ ہلال کے احکام کے لیے ہماری چاند دیکھنے والی رہنما دیکھو۔ تاریخیں ملک کے حساب سے بدلتی ہیں؛ صرف ایپس پر نہیں، مقامی علماء اور کمیٹیوں کی پیروی کرو۔' },
      { q: 'سحری اور افطار کب ہوتے ہیں؟', a: 'سحری فجر (صبح صادق) پر ختم ہوتی ہے اور افطار مغرب (غروب) پر شروع ہوتا ہے۔ اپنے شہر کے صحیح اوقات کے لیے نماز کے اوقات والا ٹول استعمال کرو۔' },
      { q: 'شب قدر کیسے پاؤں؟', a: 'آخری عشرے کی تمام راتیں عبادت کرو — طاق راتوں میں زیادہ امید — نماز، قرآن اور اللہم انک عفو والی دعا کے ساتھ۔ ہمارا آخری عشرے کا معمول ہر رات کا دہرایا جانے والا خاکہ دیتا ہے۔' },
      { q: 'فطرانہ کتنا ہے اور کب دیا جاتا ہے؟', a: 'فی کس تقریباً نصف صاع (~2.5-3 کلو) بنیادی غذا، رمضان کے آخری دنوں میں اور عید کی نماز سے پہلے۔ زکاۃ الفطر والی رہنما اور کیلکولیٹر دیکھو۔' },
    ],
    crumb: 'رمضان', badge1: 'رمضان مرکز', badge2: 'رہنما + دعائیں + اوزار',
    hubH1: 'رمضان گائیڈ',
    hubSub: 'روزے کے احکام، سحری افطار کی دعائیں، تراویح کا طریقہ، شب قدر، کاؤنٹ ڈاؤن اور نماز کے اوقات — مہینے بھر کا سب کچھ ایک جگہ۔',
    crossL: 'حج کے ارکان کے لیے دیکھو', crossHajj: 'حج و عمرہ گائیڈ →', crossMid: 'عید کی نماز، تکبیر اور قربانی کے لیے دیکھو', crossEid: 'عید گائیڈ (فطر و اضحیٰ) →',
    btnCountdown: 'رمضان کاؤنٹ ڈاؤن', btnTimes: 'سحری و افطار کے اوقات',
    secGuides: 'رہنما', secGuidesT: 'روزہ و عبادت کی رہنما', allGuides: 'تمام رہنما',
    secDuas: 'دعائیں', secDuasT: 'رمضان کی دعائیں', allDuas: 'تمام رمضان دعائیں',
    secKeyDuas: 'اہم دعائیں', secKeyDuasT: 'سحری، افطار و قدر',
    secQuiz: 'کوئز', secQuizT: 'رمضان کا علم آزماؤ', quizLink: 'رمضان کوئز',
    secTools: 'اوزار', secToolsT: 'رمضان کے اوزار', allTools: 'تمام اوزار',
    secMonth: 'کیلنڈر', secMonthT: 'ہجری کیلنڈر میں رمضان', monthLink: 'رمضان — نواں مہینہ',
    faqTitle: 'اکثر پوچھے گئے سوالات',
  },
  hi: {
    hubTitle: 'रमज़ान गाइड — रोज़े के नियम, चांद, एतिकाफ़, शबे क़द्र, फितराना व सेहरी समय',
    hubDesc: 'रमज़ान हेतु सब कुछ: चांद देखना, रोज़े के नियम, एतिकाफ़, शबे क़द्र, अंतिम दस रातों की योजना, तरावीह, ख़त्म सूची, फितराना, फ़िदया, उलटी गिनती और नमाज़ के समय।',
    hubKw: 'ramadan guide, roza rules, chand dekhne ka tarika, sehri dua, iftar dua, taraweeh method, itikaf ka tarika, laylatul qadr dua, shab e qadr, fitrana kitna hai, fidyah amount, quran khatm plan, ramadan countdown, sehri iftar time, zakat al fitr',
    hubFaq: [
      { q: 'रमज़ान की तारीख हर साल कैसे तय होती है?', a: 'चांद देखकर — रमज़ान हिलाल दिखने से शुरू होता है और शव्वाल के चांद पर समाप्त। हिलाल नियमों हेतु हमारी चांद देखने वाली गाइड देखो। तारीखें देशानुसार बदलती हैं; केवल ऐप्स पर नहीं, स्थानीय विद्वानों व समितियों का पालन करो।' },
      { q: 'सेहरी और इफ़्तार कब होते हैं?', a: 'सेहरी फ़ज्र (सच्ची भोर) पर समाप्त होती है और इफ़्तार मग़रिब (सूर्यास्त) पर शुरू होता है। अपने शहर के सही समय हेतु नमाज़-समय टूल अपनाओ।' },
      { q: 'शबे क़द्र कैसे पाऊं?', a: 'अंतिम दसों रातों में इबादत करो — विषम रातों में सर्वाधिक आशा — नमाज़, क़ुरान और अल्लाहुम्मा इन्नका अफ़ुव्वुन दुआ सहित। हमारी अंतिम-दस-रात योजना हर रात का दोहराया जाने वाला खाका देती है।' },
      { q: 'फ़ितराना कितना है और कब दिया जाता है?', a: 'प्रति व्यक्ति एक सा’ (~2.5-3 किलो) मुख्य भोजन, रमज़ान के अंतिम दिनों में ईद की नमाज़ से पहले। ज़कात-उल-फ़ित्र गाइड व कैलकुलेटर देखो।' },
    ],
    crumb: 'रमज़ान', badge1: 'रमज़ान केंद्र', badge2: 'गाइड + दुआएं + टूल्स',
    hubH1: 'रमज़ान गाइड',
    hubSub: 'रोज़े के नियम, सेहरी-इफ़्तार दुआएं, तरावीह विधि, शबे क़द्र, उलटी गिनती व नमाज़ समय — माह भर का सब कुछ एक स्थान पर।',
    crossL: 'हज के अरकान हेतु देखो', crossHajj: 'हज व उमरा गाइड →', crossMid: 'ईद नमाज़, तकबीर व क़ुर्बानी हेतु देखो', crossEid: 'ईद गाइड (फ़ित्र व अज़हा) →',
    btnCountdown: 'रमज़ान उलटी गिनती', btnTimes: 'सेहरी व इफ़्तार समय',
    secGuides: 'गाइड', secGuidesT: 'रोज़ा व इबादत गाइड', allGuides: 'सभी गाइड',
    secDuas: 'दुआएं', secDuasT: 'रमज़ान दुआएं', allDuas: 'सभी रमज़ान दुआएं',
    secKeyDuas: 'प्रमुख दुआएं', secKeyDuasT: 'सेहरी, इफ़्तार व क़द्र',
    secQuiz: 'क्विज़', secQuizT: 'रमज़ान ज्ञान परखो', quizLink: 'रमज़ान क्विज़',
    secTools: 'टूल्स', secToolsT: 'रमज़ान टूल्स', allTools: 'सभी टूल्स',
    secMonth: 'कैलेंडर', secMonthT: 'हिजरी कैलेंडर में रमज़ान', monthLink: 'रमज़ान — नौवां महीना',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
  },
  ar: {
    hubTitle: 'دليل رمضان — أحكام الصيام ورؤية الهلال والاعتكاف وليلة القدر والفطرة وأوقات السحور',
    hubDesc: 'كل ما يخص رمضان: رؤية الهلال وأحكام الصيام والاعتكاف وليلة القدر وخطة العشر الأواخر والتراويح وخطة الختم والفطرة والفدية والعد التنازلي ومواقيت الصلاة.',
    hubKw: 'ramadan guide, أحكام الصيام, رؤية الهلال, دعاء السحور, دعاء الإفطار, التراويح, الاعتكاف, ليلة القدر, زكاة الفطر, الفدية, خطة الختم, العد التنازلي لرمضان, مواقيت الصلاة',
    hubFaq: [
      { q: 'كيف يحدد رمضان كل عام؟', a: 'برؤية الهلال — يبدأ رمضان برؤية الهلال وينتهي بهلال شوال. انظر دليل رؤية الهلال. وتختلف التواريخ حسب البلد؛ فاتبع علماء بلدك ولجان الأهلة لا التطبيقات وحدها.' },
      { q: 'متى السحور والإفطار؟', a: 'ينتهي السحور عند الفجر (الصبح الصادق) ويبدأ الإفطار عند المغرب (الغروب). استخدم أداة مواقيت الصلاة لمدينتك.' },
      { q: 'كيف أدرك ليلة القدر؟', a: 'اعبد الله في الليالي العشر الأخيرة كلها — وأرجاها الأوتار — بالصلاة والقرآن ودعاء اللهم إنك عفو. وخطة الليالي العشر تمنحك قالبا ليليا متكررا.' },
      { q: 'كم مقدار الفطرة ومتى تدفع؟', a: 'صاع (~2.5-3 كغ) من الطعام الأساسي عن كل شخص، في أواخر رمضان وقبل صلاة العيد. انظر دليل زكاة الفطر والحاسبة.' },
    ],
    crumb: 'رمضان', badge1: 'مركز رمضان', badge2: 'أدلة + أدعية + أدوات',
    hubH1: 'دليل رمضان',
    hubSub: 'أحكام الصيام وأدعية السحور والإفطار وطريقة التراويح وليلة القدر والعد التنازلي ومواقيت الصلاة — كل الشهر في مكان واحد.',
    crossL: 'لأركان الحج انظر', crossHajj: 'دليل الحج والعمرة ←', crossMid: 'لصلاة العيد والتكبير والأضحية انظر', crossEid: 'دليل العيد (الفطر والأضحى) ←',
    btnCountdown: 'العد التنازلي لرمضان', btnTimes: 'أوقات السحور والإفطار',
    secGuides: 'الأدلة', secGuidesT: 'أدلة الصيام والعبادة', allGuides: 'جميع الأدلة',
    secDuas: 'الأدعية', secDuasT: 'أدعية رمضان', allDuas: 'جميع أدعية رمضان',
    secKeyDuas: 'أدعية أساسية', secKeyDuasT: 'السحور والإفطار والقدر',
    secQuiz: 'اختبار', secQuizT: 'اختبر معلوماتك عن رمضان', quizLink: 'اختبار رمضان',
    secTools: 'الأدوات', secToolsT: 'أدوات رمضان', allTools: 'جميع الأدوات',
    secMonth: 'التقويم', secMonthT: 'رمضان في التقويم الهجري', monthLink: 'رمضان — الشهر التاسع',
    faqTitle: 'الأسئلة الشائعة',
  },
};

export const EID_UI: Record<string, any> = {
  en: {
    hubTitle: 'Eid Guide — Eid ul-Fitr & Eid ul-Adha Prayer, Takbeer, Qurbani & Sunnahs',
    hubDesc: 'Both Eids in one place: Eid prayer method, day sunnahs, takbeer wording, khutbah rulings, Zakat al-Fitr, Qurbani rules, shares, meat distribution, Tashriq days and Eid duas.',
    hubKw: 'eid guide, eid ul fitr, eid ul adha, eid namaz ka tarika, eid takbeer, eid ki sunnatein, qurbani ka tarika, qurbani rules, bakra eid, eid ul adha qurbani, tashriq days, fitrana kitna hai, eid khutbah, eid mubarak greeting',
    hubFaq: [
      { q: 'What is the difference between Eid al-Fitr and Eid al-Adha?', a: 'Fitr (1st Shawwal) celebrates completing Ramadan — dates before prayer, fitrana before prayer. Adha (10th Dhul-Hijjah) honours Ibrahim’s sacrifice — Qurbani after prayer, no eating till the sacrifice. Prayer, takbeer and khutbah structures are shared.' },
      { q: 'How is Eid prayer performed?', a: 'Two rakahs with extra takbirs behind the imam, then the khutbah. See our step-by-step Eid prayer guide for the school-wise takbir counts.' },
      { q: 'When is Qurbani slaughtered?', a: 'After the Eid prayer on the 10th through Maghrib of the 13th. Slaughter before the prayer counts as ordinary meat only.' },
      { q: 'What takbeer is recited on Eid?', a: 'Allahu akbar Allahu akbar la ilaha illallah — from the Shawwal moon (Fitr) or Arafah dawn (Adha, continuing after every fard till the 13th Asr). Wording and timings in our Eid takbeer guide.' },
    ],
    crumb: 'Eid', badge1: 'Eid hub', badge2: 'Fitr + Adha + Qurbani',
    hubH1: 'Eid Guide — Fitr & Adha',
    hubSub: 'Eid prayer, sunnahs, takbeer, khutbah, fitrana, Qurbani shares and distribution, Tashriq days — both Eids, one page.',
    crossHajjL: 'For pilgrimage rites, see the', crossHajj: 'Hajj & Umrah Guide →',
    btnQurbani: 'Qurbani share splitter', btnChecklist: 'Eid-day checklist',
    secFitr: 'Eid ul-Fitr', secFitrT: 'Fitr — prayer, sunnahs & Shawwal', allGuides: 'All guides',
    secAdha: 'Eid ul-Adha', secAdhaT: 'Adha & Qurbani — sacrifice & Tashriq',
    secDuas: 'Duas', secDuasT: 'Eid & Qurbani duas', duasLink: 'Hajj & Umrah duas',
    secTools: 'Tools', secToolsT: 'Eid tools', allTools: 'All tools',
    secMonths: 'Calendar', secMonthsT: 'The Eid months', fitrMonth: 'Shawwal — Eid al-Fitr', adhaMonth: 'Dhul-Hijjah — Eid al-Adha',
    faqTitle: 'Frequently asked questions',
  },
  ur: {
    hubTitle: 'عید گائیڈ — عید الفطر و عید الاضحی نماز، تکبیر، قربانی و سنتیں',
    hubDesc: 'دونوں عیدیں ایک جگہ: عید کی نماز کا طریقہ، دن کی سنتیں، تکبیر کے الفاظ، خطبے کے احکام، زکاۃ الفطر، قربانی کے احکام، حصے، گوشت کی تقسیم، ایام تشریق اور عید کی دعائیں۔',
    hubKw: 'eid guide, eid ul fitr, eid ul adha, eid namaz ka tarika, eid takbeer, eid ki sunnatein, qurbani ka tarika, qurbani rules, bakra eid, eid ul adha qurbani, tashriq days, fitrana kitna hai, eid khutbah, eid mubarak greeting',
    hubFaq: [
      { q: 'عید الفطر اور عید الاضحیٰ میں کیا فرق ہے؟', a: 'فطر (یکم شوال) رمضان مکمل ہونے کی خوشی ہے — نماز سے پہلے کھجوریں، نماز سے پہلے فطرانہ۔ اضحیٰ (10 ذوالحجہ) ابراہیم کی قربانی کی یاد ہے — نماز کے بعد قربانی، قربانی سے پہلے کچھ نہ کھاؤ۔ نماز، تکبیر اور خطبے کا ڈھانچہ مشترک ہے۔' },
      { q: 'عید کی نماز کیسے پڑھی جاتی ہے؟', a: 'امام کے پیچھے اضافی تکبیروں کے ساتھ دو رکعتیں، پھر خطبہ۔ مسلک کے حساب سے تکبیروں کی تعداد کے لیے ہماری مرحلہ وار عید نماز والی رہنما دیکھو۔' },
      { q: 'قربانی کب ذبح کی جاتی ہے؟', a: '10 تاریخ کو عید کی نماز کے بعد سے 13 کی مغرب تک۔ نماز سے پہلے ذبح عام گوشت شمار ہوتا ہے۔' },
      { q: 'عید پر کونسی تکبیر پڑھی جاتی ہے؟', a: 'اللہ اکبر اللہ اکبر لا الہ الا اللہ — شوال کے چاند سے (فطر) یا عرفہ کی فجر سے (اضحیٰ، ہر فرض کے بعد 13 کی عصر تک)۔ الفاظ و اوقات ہماری عید تکبیر والی رہنما میں۔' },
    ],
    crumb: 'عید', badge1: 'عید مرکز', badge2: 'فطر + اضحیٰ + قربانی',
    hubH1: 'عید گائیڈ — فطر و اضحیٰ',
    hubSub: 'عید کی نماز، سنتیں، تکبیر، خطبہ، فطرانہ، قربانی کے حصے و تقسیم، ایام تشریق — دونوں عیدیں، ایک صفحہ۔',
    crossHajjL: 'حج کے ارکان کے لیے دیکھو', crossHajj: 'حج و عمرہ گائیڈ →',
    btnQurbani: 'قربانی حصہ تقسیم', btnChecklist: 'عید کے دن کی فہرست',
    secFitr: 'عید الفطر', secFitrT: 'فطر — نماز، سنتیں و شوال', allGuides: 'تمام رہنما',
    secAdha: 'عید الاضحیٰ', secAdhaT: 'اضحیٰ و قربانی — ذبیحہ و تشریق',
    secDuas: 'دعائیں', secDuasT: 'عید و قربانی کی دعائیں', duasLink: 'حج و عمرہ دعائیں',
    secTools: 'اوزار', secToolsT: 'عید کے اوزار', allTools: 'تمام اوزار',
    secMonths: 'کیلنڈر', secMonthsT: 'عید کے مہینے', fitrMonth: 'شوال — عید الفطر', adhaMonth: 'ذوالحجہ — عید الاضحیٰ',
    faqTitle: 'اکثر پوچھے گئے سوالات',
  },
  hi: {
    hubTitle: 'ईद गाइड — ईद-उल-फ़ित्र व ईद-उल-अज़हा नमाज़, तकबीर, क़ुर्बानी व सुन्नतें',
    hubDesc: 'दोनों ईदें एक स्थान पर: ईद नमाज़ विधि, दिन की सुन्नतें, तकबीर शब्द, ख़ुतबा नियम, ज़कात-उल-फ़ित्र, क़ुर्बानी नियम, हिस्से, मांस वितरण, तशरीक़ दिन व ईद दुआएं।',
    hubKw: 'eid guide, eid ul fitr, eid ul adha, eid namaz ka tarika, eid takbeer, eid ki sunnatein, qurbani ka tarika, qurbani rules, bakra eid, eid ul adha qurbani, tashriq days, fitrana kitna hai, eid khutbah, eid mubarak greeting',
    hubFaq: [
      { q: 'ईद-उल-फ़ित्र और ईद-उल-अज़हा में क्या अंतर है?', a: 'फ़ित्र (1 शव्वाल) रमज़ान पूर्णता का उत्सव है — नमाज़ से पहले खजूरें, नमाज़ से पहले फ़ितराना। अज़हा (10 ज़ुल-हिज्जा) इब्राहीम की क़ुर्बानी की स्मृति है — नमाज़ के बाद क़ुर्बानी, क़ुर्बानी तक कुछ न खाओ। नमाज़, तकबीर व ख़ुतबा संरचना साझा है।' },
      { q: 'ईद की नमाज़ कैसे पढ़ी जाती है?', a: 'इमाम के पीछे अतिरिक्त तकबीरों सहित दो रकअतें, फिर ख़ुतबा। मसलक अनुसार तकबीर संख्या हेतु हमारी चरणबद्ध ईद नमाज़ गाइड देखो।' },
      { q: 'क़ुर्बानी कब ज़बह की जाती है?', a: '10 तारीख़ को ईद नमाज़ के बाद से 13 की मग़रिब तक। नमाज़ से पहले ज़बह केवल सामान्य मांस गिना जाता है।' },
      { q: 'ईद पर कौनसी तकबीर पढ़ी जाती है?', a: 'अल्लाहु अकबर अल्लाहु अकबर ला इलाहा इल्लल्लाह — शव्वाल चांद से (फ़ित्र) या अरफ़ा फ़ज्र से (अज़हा, हर फ़र्ज़ बाद 13 अस्र तक)। शब्द व समय हमारी ईद तकबीर गाइड में।' },
    ],
    crumb: 'ईद', badge1: 'ईद केंद्र', badge2: 'फ़ित्र + अज़हा + क़ुर्बानी',
    hubH1: 'ईद गाइड — फ़ित्र व अज़हा',
    hubSub: 'ईद नमाज़, सुन्नतें, तकबीर, ख़ुतबा, फ़ितराना, क़ुर्बानी हिस्से व वितरण, तशरीक़ दिन — दोनों ईदें, एक पृष्ठ।',
    crossHajjL: 'हज अरकान हेतु देखो', crossHajj: 'हज व उमरा गाइड →',
    btnQurbani: 'क़ुर्बानी हिस्सा विभाजक', btnChecklist: 'ईद-दिवस सूची',
    secFitr: 'ईद-उल-फ़ित्र', secFitrT: 'फ़ित्र — नमाज़, सुन्नतें व शव्वाल', allGuides: 'सभी गाइड',
    secAdha: 'ईद-उल-अज़हा', secAdhaT: 'अज़हा व क़ुर्बानी — ज़बीहा व तशरीक़',
    secDuas: 'दुआएं', secDuasT: 'ईद व क़ुर्बानी दुआएं', duasLink: 'हज व उमरा दुआएं',
    secTools: 'टूल्स', secToolsT: 'ईद टूल्स', allTools: 'सभी टूल्स',
    secMonths: 'कैलेंडर', secMonthsT: 'ईद के महीने', fitrMonth: 'शव्वाल — ईद-उल-फ़ित्र', adhaMonth: 'ज़ुल-हिज्जा — ईद-उल-अज़हा',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
  },
  ar: {
    hubTitle: 'دليل العيد — صلاة عيد الفطر وعيد الأضحى والتكبير والأضحية والسنن',
    hubDesc: 'العيدان في مكان واحد: طريقة صلاة العيد وسنن اليوم وصيغة التكبير وأحكام الخطبة وزكاة الفطر وأحكام الأضحية والحصص وتوزيع اللحم وأيام التشريق وأدعية العيد.',
    hubKw: 'eid guide, عيد الفطر, عيد الأضحى, صلاة العيد, تكبير العيد, سنن العيد, أحكام الأضحية, أيام التشريق, زكاة الفطر, خطبة العيد',
    hubFaq: [
      { q: 'ما الفرق بين عيد الفطر وعيد الأضحى؟', a: 'الفطر (1 شوال) يحتفل بإتمام رمضان — تمر قبل الصلاة وفطرة قبل الصلاة. والأضحى (10 ذي الحجة) يخلد تضحية إبراهيم — الأضحية بعد الصلاة ولا أكل قبلها. وهيكل الصلاة والتكبير والخطبة مشترك.' },
      { q: 'كيف تصلى صلاة العيد؟', a: 'ركعتان بتكبيرات زائدة خلف الإمام ثم الخطبة. انظر دليل صلاة العيد خطوة بخطوة لعدد التكبيرات حسب المذهب.' },
      { q: 'متى تذبح الأضحية؟', a: 'بعد صلاة العيد يوم العاشر حتى مغرب الثالث عشر. والذبح قبل الصلاة لحم عادي فقط.' },
      { q: 'ما التكبير الذي يقال في العيد؟', a: 'الله أكبر الله أكبر لا إله إلا الله — من هلال شوال (الفطر) أو فجر عرفة (الأضحى مع الاستمرار بعد كل فرض حتى عصر الثالث عشر). الصيغة والأوقات في دليل تكبير العيد.' },
    ],
    crumb: 'العيد', badge1: 'مركز العيد', badge2: 'الفطر + الأضحى + الأضحية',
    hubH1: 'دليل العيد — الفطر والأضحى',
    hubSub: 'صلاة العيد والسنن والتكبير والخطبة والفطرة وحصص الأضحية وتوزيعها وأيام التشريق — العيدان في صفحة واحدة.',
    crossHajjL: 'لأركان الحج انظر', crossHajj: 'دليل الحج والعمرة ←',
    btnQurbani: 'مقسم حصص الأضحية', btnChecklist: 'قائمة يوم العيد',
    secFitr: 'عيد الفطر', secFitrT: 'الفطر — الصلاة والسنن وشوال', allGuides: 'جميع الأدلة',
    secAdha: 'عيد الأضحى', secAdhaT: 'الأضحى والأضحية — الذبح والتشريق',
    secDuas: 'الأدعية', secDuasT: 'أدعية العيد والأضحية', duasLink: 'أدعية الحج والعمرة',
    secTools: 'الأدوات', secToolsT: 'أدوات العيد', allTools: 'جميع الأدوات',
    secMonths: 'التقويم', secMonthsT: 'شهرا العيد', fitrMonth: 'شوال — عيد الفطر', adhaMonth: 'ذو الحجة — عيد الأضحى',
    faqTitle: 'الأسئلة الشائعة',
  },
};

export const HAJJ_UI: Record<string, any> = {
  en: {
    hubTitle: 'Hajj & Umrah Guide — Ihram, Tawaf, Sai, Arafah, Stoning & Farewell Tawaf',
    hubDesc: 'Complete Hajj & Umrah guide: ihram, tawaf, sai, Mina, Arafah, Muzdalifah, stoning, sacrifice, day-by-day timeline, packing checklist, common mistakes and essential duas.',
    hubKw: 'hajj guide, umrah ka tarika, hajj steps, ihram ka tarika, tawaf ka tarika, sai ka tarika, wuquf e arafah, muzdalifah, rami stoning, hajj day by day, umrah day plan, hajj packing list, talbiyah, arafah dua',
    hubFaq: [
      { q: 'What are the steps of Umrah in order?', a: 'Ihram at the miqat with talbiyah, tawaf (7 circuits), 2 rakahs + Zamzam, sai (7 passages Safa-Marwa), then haircut. See our Umrah day plan for timings and crowd tips.' },
      { q: 'What are the days of Hajj?', a: '8th Tarwiyah (Mina), 9th Arafah standing (the essence of Hajj) + Muzdalifah night, 10th stoning + sacrifice + tawaf al-ifadah, 11th-13th stoning all pillars + farewell tawaf.' },
      { q: 'What invalidates Hajj?', a: 'Missing the Arafah standing from noon to Fajr invalidates that year’s Hajj. Other violations (ihram restrictions, missed rites) need fidyah — consult scholars.' },
      { q: 'Which duas do I need for Hajj & Umrah?', a: 'Talbiyah, Arafah dua (La ilaha illallah...), Rabbana atina in tawaf, Safa-Marwa dhikr, Zamzam dua, Eid takbir and Kaaba-sight dua — all linked below with Arabic and meaning.' },
    ],
    crumb: 'Hajj & Umrah', badge1: 'Hajj hub', badge2: 'Rites + Duas + Planning',
    hubH1: 'Hajj & Umrah Guide',
    hubSub: 'Ihram, tawaf, sai, Arafah, Muzdalifah, stoning and farewell tawaf — rites in order, duas with Arabic, and packing + mistake guides.',
    crossEidL: 'Travelling for Eid al-Adha? See the', crossEid: 'Eid & Qurbani Guide →',
    btnUmrah: 'Umrah day plan', btnHajj: 'Hajj day by day',
    secRites: 'Rites', secRitesT: 'Hajj & Umrah rites in order', allGuides: 'All guides',
    secPlan: 'Planning', secPlanT: 'Packing, mistakes & special cases',
    secDuas: 'Duas', secDuasT: 'Essential Hajj & Umrah duas', duasLink: 'All Hajj duas',
    secQuiz: 'Quiz', secQuizT: 'Test your Hajj knowledge', quizLink: 'Hajj & Umrah quiz',
    secTools: 'Tools', secToolsT: 'Hajj tools', allTools: 'All tools',
    secMonth: 'Calendar', secMonthT: 'Hajj in the Hijri calendar', monthLink: 'Dhul-Hijjah — the 12th month',
    faqTitle: 'Frequently asked questions',
  },
  ur: {
    hubTitle: 'حج و عمرہ گائیڈ — احرام، طواف، سعی، عرفات، رمی و طواف وداع',
    hubDesc: 'مکمل حج و عمرہ گائیڈ: احرام، طواف، سعی، منیٰ، عرفات، مزدلفہ، رمی، قربانی، day-by-day خاکہ، سامان کی فہرست، عام غلطیاں اور ضروری دعائیں۔',
    hubKw: 'hajj guide, umrah ka tarika, hajj steps, ihram ka tarika, tawaf ka tarika, sai ka tarika, wuquf e arafah, muzdalifah, rami stoning, hajj day by day, umrah day plan, hajj packing list, talbiyah, arafah dua',
    hubFaq: [
      { q: 'عمرے کے مراحل ترتیب سے کیا ہیں؟', a: 'میقات سے تلبیہ کے ساتھ احرام، طواف (7 چکر)، 2 رکعت + زمزم، سعی (صفا مروہ کے 7 پھیرے)، پھر بال کٹوانا۔ اوقات اور بھیڑ سے بچنے کے مشوروں کے لیے ہمارا عمرہ day plan دیکھو۔' },
      { q: 'حج کے دن کونسے ہیں؟', a: '8 ترویہ (منیٰ)، 9 عرفات کا وقوف (حج کی جان) + مزدلفہ کی رات، 10 رمی + قربانی + طواف افاضہ، 11-13 تمام ستونوں کی رمی + طواف وداع۔' },
      { q: 'حج کس چیز سے باطل ہوتا ہے؟', a: 'ظہر سے فجر تک عرفات کا وقوف چھوٹ جائے تو اس سال کا حج باطل۔ دیگر خلاف ورزیوں (احرام کی پابندیاں، چھوٹے ارکان) پر فدیہ ہے — علماء سے رجوع کرو۔' },
      { q: 'حج و عمرہ کے لیے کونسی دعائیں چاہئیں؟', a: 'تلبیہ، عرفہ کی دعا (لا الہ الا اللہ...)، طواف میں ربنا آتنا، صفا مروہ کا ذکر، زمزم کی دعا، عید کی تکبیر اور کعبہ دیکھنے کی دعا — سب نیچے عربی و ترجمے کے ساتھ۔' },
    ],
    crumb: 'حج و عمرہ', badge1: 'حج مرکز', badge2: 'ارکان + دعائیں + منصوبہ',
    hubH1: 'حج و عمرہ گائیڈ',
    hubSub: 'احرام، طواف، سعی، عرفات، مزدلفہ، رمی اور طواف وداع — ترتیب سے ارکان، عربی کے ساتھ دعائیں، اور سامان + غلطیوں کی رہنما۔',
    crossEidL: 'عید الاضحیٰ کا سفر؟ دیکھو', crossEid: 'عید و قربانی گائیڈ →',
    btnUmrah: 'عمرہ day plan', btnHajj: 'حج day by day',
    secRites: 'ارکان', secRitesT: 'ترتیب سے حج و عمرہ ارکان', allGuides: 'تمام رہنما',
    secPlan: 'منصوبہ بندی', secPlanT: 'سامان، غلطیاں و خاص صورتیں',
    secDuas: 'دعائیں', secDuasT: 'ضروری حج و عمرہ دعائیں', duasLink: 'تمام حج دعائیں',
    secQuiz: 'کوئز', secQuizT: 'حج کا علم آزماؤ', quizLink: 'حج و عمرہ کوئز',
    secTools: 'اوزار', secToolsT: 'حج کے اوزار', allTools: 'تمام اوزار',
    secMonth: 'کیلنڈر', secMonthT: 'ہجری کیلنڈر میں حج', monthLink: 'ذوالحجہ — بارھواں مہینہ',
    faqTitle: 'اکثر پوچھے گئے سوالات',
  },
  hi: {
    hubTitle: 'हज व उमरा गाइड — इहराम, तवाफ़, सई, अराफ़ात, रमी व विदाई तवाफ़',
    hubDesc: 'संपूर्ण हज व उमरा गाइड: इहराम, तवाफ़, सई, मीना, अराफ़ात, मुज़दलिफ़ा, रमी, क़ुर्बानी, day-by-day समयरेखा, सामान सूची, सामान्य ग़लतियां व आवश्यक दुआएं।',
    hubKw: 'hajj guide, umrah ka tarika, hajj steps, ihram ka tarika, tawaf ka tarika, sai ka tarika, wuquf e arafah, muzdalifah, rami stoning, hajj day by day, umrah day plan, hajj packing list, talbiyah, arafah dua',
    hubFaq: [
      { q: 'उमरे के चरण क्रम से क्या हैं?', a: 'मीक़ात से तल्बिया सहित इहराम, तवाफ़ (7 चक्कर), 2 रकअत + ज़मज़म, सई (सफ़ा-मर्वा के 7 फेरे), फिर बाल कटवाना। समय व भीड़ सुझावों हेतु हमारा उमरा day plan देखो।' },
      { q: 'हज के दिन कौनसे हैं?', a: '8वीं तर्विया (मीना), 9वीं अराफ़ात ठहराव (हज की जान) + मुज़दलिफ़ा रात, 10वीं रमी + क़ुर्बानी + तवाफ़े इफ़ाज़ा, 11-13वीं सभी स्तंभों की रमी + विदाई तवाफ़।' },
      { q: 'हज किससे बातिल होता है?', a: 'ज़ुहर से फ़ज्र तक अराफ़ात ठहराव छूट जाए तो उस वर्ष का हज बातिल। अन्य उल्लंघनों (इहराम प्रतिबंध, छूटे अरकान) पर फ़िदया है — विद्वानों से पूछो।' },
      { q: 'हज व उमरे हेतु कौनसी दुआएं चाहिएं?', a: 'तल्बिया, अरफ़ा दुआ (ला इलाहा इल्लल्लाह...), तवाफ़ में रब्बना आतिना, सफ़ा-मर्वा ज़िक्र, ज़मज़म दुआ, ईद तकबीर व काबा-दर्शन दुआ — सब नीचे अरबी व अर्थ सहित।' },
    ],
    crumb: 'हज व उमरा', badge1: 'हज केंद्र', badge2: 'अरकान + दुआएं + योजना',
    hubH1: 'हज व उमरा गाइड',
    hubSub: 'इहराम, तवाफ़, सई, अराफ़ात, मुज़दलिफ़ा, रमी व विदाई तवाफ़ — क्रम से अरकान, अरबी सहित दुआएं, और सामान + ग़लती गाइड।',
    crossEidL: 'ईद-उल-अज़हा यात्रा? देखो', crossEid: 'ईद व क़ुर्बानी गाइड →',
    btnUmrah: 'उमरा day plan', btnHajj: 'हज day by day',
    secRites: 'अरकान', secRitesT: 'क्रम से हज व उमरा अरकान', allGuides: 'सभी गाइड',
    secPlan: 'योजना', secPlanT: 'सामान, ग़लतियां व विशेष स्थितियां',
    secDuas: 'दुआएं', secDuasT: 'आवश्यक हज व उमरा दुआएं', duasLink: 'सभी हज दुआएं',
    secQuiz: 'क्विज़', secQuizT: 'हज ज्ञान परखो', quizLink: 'हज व उमरा क्विज़',
    secTools: 'टूल्स', secToolsT: 'हज टूल्स', allTools: 'सभी टूल्स',
    secMonth: 'कैलेंडर', secMonthT: 'हिजरी कैलेंडर में हज', monthLink: 'ज़ुल-हिज्जा — बारहवां महीना',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
  },
  ar: {
    hubTitle: 'دليل الحج والعمرة — الإحرام والطواف والسعي وعرفة والرمي وطواف الوداع',
    hubDesc: 'دليل الحج والعمرة الكامل: الإحرام والطواف والسعي ومنى وعرفة ومزدلفة والرمي والأضحية والجدول اليومي وقائمة التجهيز والأخطاء الشائعة والأدعية الأساسية.',
    hubKw: 'hajj guide, مناسك الحج, طريقة العمرة, الإحرام, الطواف, السعي, الوقوف بعرفة, مزدلفة, رمي الجمرات, التلبية, دعاء عرفة',
    hubFaq: [
      { q: 'ما خطوات العمرة بالترتيب؟', a: 'الإحرام من الميقات بالتلبية والطواف (7 أشواط) وركعتان + زمزم والسعي (7 أشواط بين الصفا والمروة) ثم الحلق أو التقصير. انظر خطة العمرة اليومية للأوقات ونصائح الزحام.' },
      { q: 'ما أيام الحج؟', a: 'الثامن التروية (منى) والتاسع الوقوف بعرفة (روح الحج) + ليلة مزدلفة والعاشر الرمي + الأضحية + طواف الإفاضة والحادي عشر حتى الثالث عشر رمي الجمرات + طواف الوداع.' },
      { q: 'ما الذي يبطل الحج؟', a: 'فوات الوقوف بعرفة من الظهر إلى الفجر يبطل حج تلك السنة. والمخالفات الأخرى (محظورات الإحرام والمناسك الفائتة) فيها فدية — استشر العلماء.' },
      { q: 'ما الأدعية اللازمة للحج والعمرة؟', a: 'التلبية ودعاء عرفة (لا إله إلا الله...) وربنا آتنا في الطواف وذكر الصفا والمروة ودعاء زمزم وتكبير العيد ودعاء رؤية الكعبة — كلها أدناه بالعربية والمعنى.' },
    ],
    crumb: 'الحج والعمرة', badge1: 'مركز الحج', badge2: 'المناسك + الأدعية + التخطيط',
    hubH1: 'دليل الحج والعمرة',
    hubSub: 'الإحرام والطواف والسعي وعرفة ومزدلفة والرمي وطواف الوداع — المناسك مرتبة والأدعية بالعربية وأدلة التجهيز والأخطاء.',
    crossEidL: 'مسافر لعيد الأضحى؟ انظر', crossEid: 'دليل العيد والأضحية ←',
    btnUmrah: 'خطة العمرة اليومية', btnHajj: 'الحج يوما بيوم',
    secRites: 'المناسك', secRitesT: 'مناسك الحج والعمرة مرتبة', allGuides: 'جميع الأدلة',
    secPlan: 'التخطيط', secPlanT: 'التجهيز والأخطاء والحالات الخاصة',
    secDuas: 'الأدعية', secDuasT: 'أدعية الحج والعمرة الأساسية', duasLink: 'جميع أدعية الحج',
    secQuiz: 'اختبار', secQuizT: 'اختبر معلوماتك عن الحج', quizLink: 'اختبار الحج والعمرة',
    secTools: 'الأدوات', secToolsT: 'أدوات الحج', allTools: 'جميع الأدوات',
    secMonth: 'التقويم', secMonthT: 'الحج في التقويم الهجري', monthLink: 'ذو الحجة — الشهر الثاني عشر',
    faqTitle: 'الأسئلة الشائعة',
  },
};

export const UMRAH_UI: Record<string, any> = {
  en: {
    hubTitle: 'Umrah Guide — Step by Step with Duas (Ihram, Tawaf, Sai)',
    hubDesc: 'How to perform Umrah in order: ihram at the miqat, tawaf, sai and haircut — with timings, crowd tips, kids and elderly guidance, and essential duas with Arabic and meaning.',
    hubKw: 'umrah guide, umrah ka tarika, how to do umrah, umrah step by step, ihram tawaf sai, talbiyah, umrah duas, umrah with kids',
    hubFaq: [
      { q: 'How long does Umrah take?', a: 'Usually 2–4 hours depending on crowds; night hours after Isha are calmest. See the Umrah day plan for timings.' },
      { q: 'What is the difference between Hajj and Umrah?', a: 'Hajj is obligatory once for the able and fixed to Dhul-Hijjah days; Umrah is a shorter, voluntary pilgrimage doable anytime of year.' },
      { q: 'Does Umrah in Ramadan equal Hajj?', a: 'The Prophet ﷺ said an Umrah in Ramadan equals a Hajj (in reward). See the hadith below and plan with the Ramadan hub.' },
      { q: 'What breaks Umrah?', a: 'Violating ihram restrictions needs expiation (dam) per the violation; tawaf, sai and the haircut are all essential. Consult scholars for cases.' },
    ],
    crumb: 'Umrah', badge1: 'Umrah hub', badge2: 'Steps + Duas',
    hubH1: 'Umrah Guide — Step by Step',
    hubSub: 'Ihram, tawaf, sai and haircut in order — with timings, crowd tips, kids and elderly guidance, and duas with Arabic.',
    crossHajjL: 'For the full Hajj rites, see the', crossHajj: 'Hajj & Umrah Guide →',
    btnPlan: 'Umrah day plan', btnHajj: 'Hajj & Umrah guide',
    secSteps: 'Steps', secStepsT: 'Umrah in order', allGuides: 'All guides',
    secDuas: 'Duas', secDuasT: 'Essential Umrah duas', duasLink: 'All Hajj duas',
    secHadith: 'Hadith', secHadithT: 'Umrah in Ramadan', hadithLink: 'Umrah in Ramadan — Equals Hajj',
    secQuiz: 'Quiz', secQuizT: 'Test your Umrah knowledge', quizLink: 'Hajj & Umrah quiz',
    faqTitle: 'Frequently asked questions',
  },
  ur: {
    hubTitle: 'عمرہ گائیڈ — مرحلہ وار طریقہ دعاؤں کے ساتھ (احرام، طواف، سعی)',
    hubDesc: 'عمرہ ترتیب سے کیسے کرو: میقات سے احرام، طواف، سعی اور بال کٹوانا — اوقات، بھیڑ سے بچنے کے مشورے، بچوں بزرگوں کی رہنمائی، اور عربی و ترجمے کے ساتھ ضروری دعائیں۔',
    hubKw: 'umrah guide, umrah ka tarika, how to do umrah, umrah step by step, ihram tawaf sai, talbiyah, umrah duas, umrah with kids',
    hubFaq: [
      { q: 'عمرے میں کتنا وقت لگتا ہے؟', a: 'عام طور پر بھیڑ کے حساب سے 2-4 گھنٹے؛ عشاء کے بعد رات کے اوقات پرسکون ہوتے ہیں۔ اوقات کے لیے عمرہ day plan دیکھو۔' },
      { q: 'حج اور عمرہ میں کیا فرق ہے؟', a: 'حج استطاعت رکھنے والے پر ایک بار فرض ہے اور ذوالحجہ کے دنوں میں مقرر ہے؛ عمرہ مختصر نفلی زیارت ہے جو سال میں کبھی بھی ہو سکتا ہے۔' },
      { q: 'کیا رمضان میں عمرہ حج کے برابر ہے؟', a: 'نبی ﷺ نے فرمایا رمضان میں عمرہ حج کے برابر ہے (ثواب میں)۔ نیچے حدیث دیکھو اور رمضان مرکز سے منصوبہ بناؤ۔' },
      { q: 'عمرہ کس چیز سے ٹوٹتا ہے؟', a: 'احرام کی پابندیاں توڑنے پر خلاف ورزی کے حساب سے دم ہے؛ طواف، سعی اور بال کٹوانا سب ضروری ہیں۔ صورتوں کے لیے علماء سے رجوع کرو۔' },
    ],
    crumb: 'عمرہ', badge1: 'عمرہ مرکز', badge2: 'مراحل + دعائیں',
    hubH1: 'عمرہ گائیڈ — مرحلہ وار',
    hubSub: 'احرام، طواف، سعی اور بال کٹوانا ترتیب سے — اوقات، بھیڑ کے مشورے، بچوں بزرگوں کی رہنمائی، اور عربی کے ساتھ دعائیں۔',
    crossHajjL: 'مکمل حج ارکان کے لیے دیکھو', crossHajj: 'حج و عمرہ گائیڈ →',
    btnPlan: 'عمرہ day plan', btnHajj: 'حج و عمرہ گائیڈ',
    secSteps: 'مراحل', secStepsT: 'ترتیب سے عمرہ', allGuides: 'تمام رہنما',
    secDuas: 'دعائیں', secDuasT: 'ضروری عمرہ دعائیں', duasLink: 'تمام حج دعائیں',
    secHadith: 'حدیث', secHadithT: 'رمضان میں عمرہ', hadithLink: 'رمضان میں عمرہ — حج کے برابر',
    secQuiz: 'کوئز', secQuizT: 'عمرہ کا علم آزماؤ', quizLink: 'حج و عمرہ کوئز',
    faqTitle: 'اکثر پوچھے گئے سوالات',
  },
  hi: {
    hubTitle: 'उमरा गाइड — दुआओं सहित चरणबद्ध विधि (इहराम, तवाफ़, सई)',
    hubDesc: 'उमरा क्रम से कैसे करें: मीक़ात से इहराम, तवाफ़, सई व बाल कटवाना — समय, भीड़ सुझाव, बच्चों-बुज़ुर्गों हेतु मार्गदर्शन, और अरबी व अर्थ सहित आवश्यक दुआएं।',
    hubKw: 'umrah guide, umrah ka tarika, how to do umrah, umrah step by step, ihram tawaf sai, talbiyah, umrah duas, umrah with kids',
    hubFaq: [
      { q: 'उमरे में कितना समय लगता है?', a: 'आमतौर पर भीड़ अनुसार 2-4 घंटे; इशा बाद रात के समय शांततम होते हैं। समय हेतु उमरा day plan देखो।' },
      { q: 'हज और उमरे में क्या अंतर है?', a: 'हज सामर्थ्यवान पर एक बार फ़र्ज़ है और ज़ुल-हिज्जा दिनों में नियत है; उमरा संक्षिप्त नफ़ली तीर्थ है जो वर्ष में कभी भी हो सकता है।' },
      { q: 'क्या रमज़ान में उमरा हज के बराबर है?', a: 'नबी ﷺ ने फ़रमाया रमज़ान में उमरा हज के बराबर है (सवाब में)। नीचे हदीस देखो और रमज़ान केंद्र से योजना बनाओ।' },
      { q: 'उमرا किससे टूटता है?', a: 'इहराम प्रतिबंध तोड़ने पर उल्लंघन अनुसार दम है; तवाफ़, सई व बाल कटवाना सभी आवश्यक हैं। स्थितियों हेतु विद्वानों से पूछो।' },
    ],
    crumb: 'उमरा', badge1: 'उमरा केंद्र', badge2: 'चरण + दुआएं',
    hubH1: 'उमरा गाइड — चरणबद्ध',
    hubSub: 'इहराम, तवाफ़, सई व बाल कटवाना क्रम से — समय, भीड़ सुझाव, बच्चों-बुज़ुर्गों हेतु मार्गदर्शन, और अरबी सहित दुआएं।',
    crossHajjL: 'पूर्ण हज अरकान हेतु देखो', crossHajj: 'हज व उमरा गाइड →',
    btnPlan: 'उमरा day plan', btnHajj: 'हज व उमरा गाइड',
    secSteps: 'चरण', secStepsT: 'क्रम से उमरा', allGuides: 'सभी गाइड',
    secDuas: 'दुआएं', secDuasT: 'आवश्यक उमरा दुआएं', duasLink: 'सभी हज दुआएं',
    secHadith: 'हदीस', secHadithT: 'रमज़ान में उमरा', hadithLink: 'रमज़ान में उमरा — हज के बराबर',
    secQuiz: 'क्विज़', secQuizT: 'उमरा ज्ञान परखो', quizLink: 'हज व उमरा क्विज़',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
  },
  ar: {
    hubTitle: 'دليل العمرة — خطوة بخطوة مع الأدعية (الإحرام والطواف والسعي)',
    hubDesc: 'كيف تؤدي العمرة مرتبة: الإحرام من الميقات والطواف والسعي والحلق — مع الأوقات ونصائح الزحام وإرشادات الأطفال وكبار السن والأدعية الأساسية بالعربية والمعنى.',
    hubKw: 'umrah guide, طريقة العمرة, خطوات العمرة, الإحرام الطواف السعي, التلبية, أدعية العمرة',
    hubFaq: [
      { q: 'كم تستغرق العمرة؟', a: 'عادة 2-4 ساعات حسب الزحام؛ وساعات الليل بعد العشاء أهدأ. انظر خطة العمرة اليومية للأوقات.' },
      { q: 'ما الفرق بين الحج والعمرة؟', a: 'الحج فرض مرة واحدة على المستطيع ومحدد بأيام ذي الحجة؛ والعمرة زيارة أقصر تطوعية في أي وقت من السنة.' },
      { q: 'هل عمرة رمضان تعدل حجة؟', a: 'قال النبي ﷺ: عمرة في رمضان تعدل حجة (في الثواب). انظر الحديث أدناه وخطط مع مركز رمضان.' },
      { q: 'ما الذي يفسد العمرة؟', a: 'انتهاك محظورات الإحرام يوجب الفدية حسب المخالفة؛ والطواف والسعي والحلق كلها أساسية. استشر العلماء في الحالات.' },
    ],
    crumb: 'العمرة', badge1: 'مركز العمرة', badge2: 'الخطوات + الأدعية',
    hubH1: 'دليل العمرة — خطوة بخطوة',
    hubSub: 'الإحرام والطواف والسعي والحلق مرتبة — مع الأوقات ونصائح الزحام وإرشادات الأطفال وكبار السن والأدعية بالعربية.',
    crossHajjL: 'لأركان الحج الكاملة انظر', crossHajj: 'دليل الحج والعمرة ←',
    btnPlan: 'خطة العمرة اليومية', btnHajj: 'دليل الحج والعمرة',
    secSteps: 'الخطوات', secStepsT: 'العمرة مرتبة', allGuides: 'جميع الأدلة',
    secDuas: 'الأدعية', secDuasT: 'أدعية العمرة الأساسية', duasLink: 'جميع أدعية الحج',
    secHadith: 'الحديث', secHadithT: 'عمرة رمضان', hadithLink: 'عمرة رمضان — تعدل حجة',
    secQuiz: 'اختبار', secQuizT: 'اختبر معلوماتك عن العمرة', quizLink: 'اختبار الحج والعمرة',
    faqTitle: 'الأسئلة الشائعة',
  },
};

export const CALENDAR_UI: Record<string, any> = {
  en: {
    crumbCal: 'Islamic Calendar',
    gridEyebrow: 'Months', gridTitle: 'The 12 Hijri months', gridLink: 'Islamic calendar', badgeN: '12 months', faqTitle: 'Frequently asked questions' },
  ur: {
    crumbCal: 'اسلامی کیلنڈر',
    gridEyebrow: 'مہینے', gridTitle: '12 ہجری مہینے', gridLink: 'اسلامی کیلنڈر', badgeN: '12 مہینے', faqTitle: 'اکثر پوچھے گئے سوالات' },
  hi: {
    crumbCal: 'इस्लामी कैलेंडर',
    gridEyebrow: 'महीने', gridTitle: '12 हिजरी महीने', gridLink: 'इस्लामी कैलेंडर', badgeN: '12 महीने', faqTitle: 'अक्सर पूछे जाने वाले प्रश्न' },
  ar: {
    crumbCal: 'التقويم الإسلامي',
    gridEyebrow: 'الأشهر', gridTitle: 'الأشهر الهجرية الـ12', gridLink: 'التقويم الإسلامي', badgeN: '12 شهرا', faqTitle: 'الأسئلة الشائعة' },
};

export const MONTH_UI: Record<string, any> = {
  en: {
    badgeMonth: 'Hijri month', badgeN: 'Month {n} of 12', sacredL: 'Sacred month',
    keyDatesL: 'Key dates', prevL: '← {m}', nextL: '{m} →', hubLink: 'All 12 months',
    detTitle: '{m} — Hijri Month {n} with Key Dates & Resources',
    crumbCal: 'Calendar',
    crumbCal: 'Calendar',
    faqTitle: 'Frequently asked questions',
    faqWhichQ: 'Which Hijri month is {m}?', faqEventsQ: 'What happens in {m}?', faqMoreQ: 'Where do I learn more?',
    faqMoreA: 'Open any linked guide, dua or resource above — or browse the Islamic calendar for dates and the full month list.',
    months: {
      'muharram': { desc: 'The first month of the Hijri year.', note: 'A sacred month. The 10th day, Ashura, is a recommended fast (with the 9th); the new year begins by moon sighting.' },
      'safar': { desc: 'The second month of the Hijri year.' },
      'rabi-al-awwal': { desc: 'The third month of the Hijri year.', note: 'The Prophet ﷺ was born in Mecca in Rabi al-Awwal — most-reported view: the 12th, widely known as Mawlid un-Nabi.' },
      'rabi-al-thani': { desc: 'The fourth month of the Hijri year.' },
      'jumada-al-ula': { desc: 'The fifth month of the Hijri year.' },
      'jumada-al-akhirah': { desc: 'The sixth month of the Hijri year.' },
      'rajab': { desc: 'The seventh month of the Hijri year.', note: 'A sacred month. Shab-e-Miraj (the Night Journey) is observed on 27 Rajab; the Rajab guide covers what is and is not established.' },
      'shaban': { desc: 'The eighth month of the Hijri year.', note: 'Shab-e-Barat falls on the 15th night; the Sha’ban guide gives a balanced, sourced explanation.' },
      'ramadan': { desc: 'The ninth month — the month of fasting.', note: 'Fast from true dawn to sunset; seek Laylatul Qadr in the odd nights of the last ten. Full guidance: the Ramadan hub.' },
      'shawwal': { desc: 'The tenth month of the Hijri year.', note: 'Eid al-Fitr is 1 Shawwal; six voluntary fasts in Shawwal earn a full year’s reward.' },
      'dhul-qadah': { desc: 'The eleventh month of the Hijri year.', note: 'A sacred month.' },
      'dhul-hijjah': { desc: 'The twelfth and final month of the Hijri year.', note: 'Hajj rites run 8th–13th: Tarwiyah (8th), Arafah (9th), Eid al-Adha with Qurbani (10th), and the Tashriq days (11th–13th).' },
    },
    events: {
      'new-year': { name: 'Islamic New Year', note: '1 Muharram — new Hijri year begins' },
      'tasua': { name: 'Tasua (9th Muharram)', note: 'Fast with Ashura (9th + 10th)' },
      'ashura': { name: 'Day of Ashura', note: '10 Muharram — fast; expiates the past year' },
      'karbala': { name: 'Karbala (61 AH)', note: 'Martyrdom of Husayn — told with reverence and restraint' },
      'mawlid': { name: 'Mawlid un-Nabi', note: '12 Rabi al-Awwal — study the Seerah' },
      'miraj': { name: 'Shab-e-Miraj', note: '27 Rajab — the Night Journey; honour with prayer' },
      'miraj-story': { name: 'Isra & Miraj', note: 'The Night Journey and Ascension' },
      'barat': { name: 'Shab-e-Barat', note: '15 Shaban — hopeful individual worship' },
      'ramadan-begins': { name: 'Ramadan begins', note: '1 Ramadan — fasting month starts (sighting)' },
      'qadr-nights': { name: 'Laylatul Qadr (odd nights)', note: '21st, 23rd, 25th, 27th, 29th — seek the Night of Power' },
      'eid-fitr': { name: 'Eid al-Fitr', note: '1 Shawwal — dates, fitrana, Eid prayer' },
      'six-fasts': { name: 'Shawwal six fasts', note: 'Any 6 days of Shawwal — a year of fasting' },
      'tarwiyah': { name: 'Day of Tarwiyah', note: '8 Dhul-Hijjah — Hajj rites begin at Mina' },
      'arafah': { name: 'Day of Arafah', note: '9 Dhul-Hijjah — the Hajj; fast for non-pilgrims' },
      'eid-adha': { name: 'Eid al-Adha', note: '10 Dhul-Hijjah — Qurbani after prayer' },
      'tashriq': { name: 'Days of Tashriq', note: '11th–13th — stoning; no fasting' },
    },
  },
  ur: {
    badgeMonth: 'ہجری مہینہ', badgeN: '12 میں سے مہینہ {n}', sacredL: 'حرمت والا مہینہ',
    keyDatesL: 'اہم تاریخیں', prevL: '← {m}', nextL: '{m} →', hubLink: 'تمام 12 مہینے',
    detTitle: '{m} — ہجری مہینہ {n} اہم تاریخوں و وسائل کے ساتھ',
    crumbCal: 'کیلنڈر',
    crumbCal: 'کیلنڈر',
    faqTitle: 'اکثر پوچھے گئے سوالات',
    faqWhichQ: '{m} ہجری کا کونسا مہینہ ہے؟', faqEventsQ: '{m} میں کیا ہوتا ہے؟', faqMoreQ: 'مزید کہاں سیکھوں؟',
    faqMoreA: 'اوپر کوئی بھی منسلک رہنما، دعا یا وسیلہ کھولو — یا تاریخوں اور مکمل فہرست کے لیے اسلامی کیلنڈر دیکھو۔',
    months: {
      'muharram': { desc: 'ہجری سال کا پہلا مہینہ۔', note: 'حرمت والا مہینہ۔ 10 تاریخ عاشورہ مسنون روزہ ہے (9 کے ساتھ)؛ نیا سال چاند دیکھ کر شروع ہوتا ہے۔' },
      'safar': { desc: 'ہجری سال کا دوسرا مہینہ۔' },
      'rabi-al-awwal': { desc: 'ہجری سال کا تیسرا مہینہ۔', note: 'نبی ﷺ مکہ میں ربیع الاول میں پیدا ہوئے — مشہور قول: 12 تاریخ، جو میلاد النبی کے نام سے معروف ہے۔' },
      'rabi-al-thani': { desc: 'ہجری سال کا چوتھا مہینہ۔' },
      'jumada-al-ula': { desc: 'ہجری سال کا پانچواں مہینہ۔' },
      'jumada-al-akhirah': { desc: 'ہجری سال کا چھٹا مہینہ۔' },
      'rajab': { desc: 'ہجری سال کا ساتواں مہینہ۔', note: 'حرمت والا مہینہ۔ شب معراج (سفر معراج) 27 رجب کو منائی جاتی ہے؛ رجب والی رہنما ثابت و غیر ثابت بتاتی ہے۔' },
      'shaban': { desc: 'ہجری سال کا آٹھواں مہینہ۔', note: 'شب برات 15ویں رات کو ہے؛ شعبان والی رہنما متوازن مستند وضاحت دیتی ہے۔' },
      'ramadan': { desc: 'نواں مہینہ — روزوں کا مہینہ۔', note: 'صبح صادق سے غروب تک روزہ رکھو؛ آخری عشرے کی طاق راتوں میں شب قدر تلاش کرو۔ مکمل رہنمائی: رمضان مرکز۔' },
      'shawwal': { desc: 'ہجری سال کا دسواں مہینہ۔', note: 'عید الفطر یکم شوال کو ہے؛ شوال کے چھ نفلی روزے سال بھر کے برابر ہیں۔' },
      'dhul-qadah': { desc: 'ہجری سال کا گیارھواں مہینہ۔', note: 'حرمت والا مہینہ۔' },
      'dhul-hijjah': { desc: 'ہجری سال کا بارھواں اور آخری مہینہ۔', note: 'حج کے ارکان 8-13 کو ہیں: ترویہ (8)، عرفات (9)، قربانی کے ساتھ عید الاضحیٰ (10)، اور ایام تشریق (11-13)۔' },
    },
    events: {
      'new-year': { name: 'اسلامی نیا سال', note: 'یکم محرم — نیا ہجری سال شروع' },
      'tasua': { name: 'تاسوعہ (9 محرم)', note: 'عاشورہ کے ساتھ روزہ (9+10)' },
      'ashura': { name: 'یوم عاشورہ', note: '10 محرم — روزہ؛ پچھلے سال کا کفارہ' },
      'karbala': { name: 'کربلا (61ھ)', note: 'حسین کی شہادت — ادب و ضبط کے ساتھ' },
      'mawlid': { name: 'میلاد النبی', note: '12 ربیع الاول — سیرت پڑھو' },
      'miraj': { name: 'شب معراج', note: '27 رجب — سفر معراج؛ نماز سے تعظیم' },
      'miraj-story': { name: 'اسراء و معراج', note: 'رات کا سفر اور عروج' },
      'barat': { name: 'شب برات', note: '15 شعبان — انفرادی عبادت کی امید' },
      'ramadan-begins': { name: 'رمضان کا آغاز', note: 'یکم رمضان — روزوں کا مہینہ شروع (رویت)' },
      'qadr-nights': { name: 'شب قدر (طاق راتیں)', note: '21، 23، 25، 27، 29 — قدر کی رات تلاش کرو' },
      'eid-fitr': { name: 'عید الفطر', note: 'یکم شوال — کھجوریں، فطرانہ، عید نماز' },
      'six-fasts': { name: 'شوال کے چھ روزے', note: 'شوال کے کوئی 6 دن — سال بھر کا روزہ' },
      'tarwiyah': { name: 'یوم ترویہ', note: '8 ذوالحجہ — منیٰ میں حج ارکان شروع' },
      'arafah': { name: 'یوم عرفہ', note: '9 ذوالحجہ — حج؛ غیر حاجی روزہ رکھیں' },
      'eid-adha': { name: 'عید الاضحیٰ', note: '10 ذوالحجہ — نماز کے بعد قربانی' },
      'tashriq': { name: 'ایام تشریق', note: '11-13 — رمی؛ روزہ نہیں' },
    },
  },
  hi: {
    badgeMonth: 'हिजरी महीना', badgeN: '12 में से महीना {n}', sacredL: 'पवित्र महीना',
    keyDatesL: 'प्रमुख तिथियां', prevL: '← {m}', nextL: '{m} →', hubLink: 'सभी 12 महीने',
    detTitle: '{m} — हिजरी माह {n}, प्रमुख तिथियों व संसाधनों सहित',
    crumbCal: 'कैलेंडर',
    crumbCal: 'कैलेंडर',
    faqTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqWhichQ: '{m} हिजरी का कौनसा महीना है?', faqEventsQ: '{m} में क्या होता है?', faqMoreQ: 'और कहां सीखूं?',
    faqMoreA: 'ऊपर कोई भी संबद्ध गाइड, दुआ या संसाधन खोलो — या तिथियों व पूर्ण सूची हेतु इस्लामी कैलेंडर देखो।',
    months: {
      'muharram': { desc: 'हिजरी वर्ष का प्रथम माह।', note: 'पवित्र महीना। 10 तारीख़ आशूरा मसनून रोज़ा है (9 के साथ); नववर्ष चांद देखकर आरंभ होता है।' },
      'safar': { desc: 'हिजरी वर्ष का द्वितीय माह।' },
      'rabi-al-awwal': { desc: 'हिजरी वर्ष का तृतीय माह।', note: 'नबी ﷺ का जन्म मक्का में रबी-उल-अव्वल में हुआ — प्रसिद्ध मत: 12 तारीख़, जो मीलाद-उन-नबी नाम से ज्ञात है।' },
      'rabi-al-thani': { desc: 'हिजरी वर्ष का चतुर्थ माह।' },
      'jumada-al-ula': { desc: 'हिजरी वर्ष का पंचम माह।' },
      'jumada-al-akhirah': { desc: 'हिजरी वर्ष का षष्ठ माह।' },
      'rajab': { desc: 'हिजरी वर्ष का सप्तम माह।', note: 'पवित्र महीना। शबे मेराज (मेराज यात्रा) 27 रजब को मनाई जाती है; रजब गाइड स्थापित व अस्थापित बताती है।' },
      'shaban': { desc: 'हिजरी वर्ष का अष्टम माह।', note: 'शबे बरात 15वीं रात को है; शाबान गाइड संतुलित प्रामाणिक व्याख्या देती है।' },
      'ramadan': { desc: 'नवां माह — रोज़ों का महीना।', note: 'सच्ची भोर से सूर्यास्त तक रोज़ा रखो; अंतिम दशक की विषम रातों में शबे क़द्र खोजो। पूर्ण मार्गदर्शन: रमज़ान केंद्र।' },
      'shawwal': { desc: 'हिजरी वर्ष का दशम माह।', note: 'ईद-उल-फ़ित्र 1 शव्वाल को है; शव्वाल के छह नफ़ली रोज़े पूर्ण वर्ष तुल्य हैं।' },
      'dhul-qadah': { desc: 'हिजरी वर्ष का एकादश माह।', note: 'पवित्र महीना।' },
      'dhul-hijjah': { desc: 'हिजरी वर्ष का द्वादश व अंतिम माह।', note: 'हज अरकान 8-13 को हैं: तर्विया (8), अराफ़ात (9), क़ुर्बानी सहित ईद-उल-अज़हा (10), व तशरीक़ दिन (11-13)।' },
    },
    events: {
      'new-year': { name: 'इस्लामी नववर्ष', note: '1 मुहर्रम — नव हिजरी वर्षारंभ' },
      'tasua': { name: 'तासूआ (9 मुहर्रम)', note: 'आशूरा सहित रोज़ा (9+10)' },
      'ashura': { name: 'आशूरा दिवस', note: '10 मुहर्रम — रोज़ा; गत वर्ष का कफ़्फ़ारा' },
      'karbala': { name: 'कर्बला (61 हि.)', note: 'हुसैन की शहादत — आदर व संयम सहित' },
      'mawlid': { name: 'मीलाद-उन-नबी', note: '12 रबी-उल-अव्वल — सीरत पढ़ो' },
      'miraj': { name: 'शबे मेराज', note: '27 रजब — मेराज यात्रा; नमाज़ से सम्मान' },
      'miraj-story': { name: 'इसरा व मेराज', note: 'रात्रि यात्रा व आरोहण' },
      'barat': { name: 'शबे बरात', note: '15 शाबान — व्यक्तिगत इबादत की आशा' },
      'ramadan-begins': { name: 'रमज़ान आरंभ', note: '1 रमज़ान — रोज़ा माह प्रारंभ (दीदार)' },
      'qadr-nights': { name: 'शबे क़द्र (विषम रातें)', note: '21, 23, 25, 27, 29 — क़द्र रात्रि खोजो' },
      'eid-fitr': { name: 'ईद-उल-फ़ित्र', note: '1 शव्वाल — खजूरें, फ़ितराना, ईद नमाज़' },
      'six-fasts': { name: 'शव्वाल छह रोज़े', note: 'शव्वाल के कोई 6 दिन — पूर्ण वर्ष रोज़ा' },
      'tarwiyah': { name: 'तर्विया दिवस', note: '8 ज़ुल-हिज्जा — मीना में हज अरकान आरंभ' },
      'arafah': { name: 'अराफ़ात दिवस', note: '9 ज़ुल-हिज्जा — हज; गैर-हाजी रोज़ा रखें' },
      'eid-adha': { name: 'ईद-उल-अज़हा', note: '10 ज़ुल-हिज्जा — नमाज़ बाद क़ुर्बानी' },
      'tashriq': { name: 'तशरीक़ दिन', note: '11-13 — रमी; रोज़ा नहीं' },
    },
  },
  ar: {
    badgeMonth: 'شهر هجري', badgeN: 'الشهر {n} من 12', sacredL: 'شهر حرام',
    keyDatesL: 'تواريخ مهمة', prevL: '← {m}', nextL: '{m} →', hubLink: 'جميع الأشهر الـ12',
    detTitle: '{m} — الشهر الهجري {n} بالتواريخ والموارد',
    crumbCal: 'التقويم',
    crumbCal: 'التقويم',
    faqTitle: 'الأسئلة الشائعة',
    faqWhichQ: 'أي شهر هجري هو {m}؟', faqEventsQ: 'ماذا يحدث في {m}؟', faqMoreQ: 'أين أتعلم المزيد؟',
    faqMoreA: 'افتح أي دليل أو دعاء أو مورد مرتبط أعلاه — أو تصفح التقويم الإسلامي للتواريخ والقائمة الكاملة.',
    months: {
      'muharram': { desc: 'الشهر الأول من السنة الهجرية.', note: 'شهر حرام. يوم عاشوراء (العاشر) صيام مستحب (مع التاسع)؛ وتبدأ السنة برؤية الهلال.' },
      'safar': { desc: 'الشهر الثاني من السنة الهجرية.' },
      'rabi-al-awwal': { desc: 'الشهر الثالث من السنة الهجرية.', note: 'ولد النبي ﷺ في مكة في ربيع الأول — أشهر الأقوال: الثاني عشر، المعروف بالمولد النبوي.' },
      'rabi-al-thani': { desc: 'الشهر الرابع من السنة الهجرية.' },
      'jumada-al-ula': { desc: 'الشهر الخامس من السنة الهجرية.' },
      'jumada-al-akhirah': { desc: 'الشهر السادس من السنة الهجرية.' },
      'rajab': { desc: 'الشهر السابع من السنة الهجرية.', note: 'شهر حرام. ليلة المعراج (رحلة الإسراء) تحيا في 27 رجب؛ ودليل رجب يبين الثابت وغير الثابت.' },
      'shaban': { desc: 'الشهر الثامن من السنة الهجرية.', note: 'ليلة البراءة في الخامس عشر؛ ودليل شعبان يقدم شرحا متوازنا موثقا.' },
      'ramadan': { desc: 'الشهر التاسع — شهر الصيام.', note: 'صم من الفجر الصادق إلى الغروب؛ والتمس ليلة القدر في أوتار العشر الأواخر. للإرشاد الكامل: مركز رمضان.' },
      'shawwal': { desc: 'الشهر العاشر من السنة الهجرية.', note: 'عيد الفطر في الأول من شوال؛ وصيام ستة أيام من شوال يعدل سنة كاملة.' },
      'dhul-qadah': { desc: 'الشهر الحادي عشر من السنة الهجرية.', note: 'شهر حرام.' },
      'dhul-hijjah': { desc: 'الشهر الثاني عشر والأخير من السنة الهجرية.', note: 'مناسك الحج من 8 إلى 13: التروية (8) وعرفة (9) وعيد الأضحى بالأضحية (10) وأيام التشريق (11-13).' },
    },
    events: {
      'new-year': { name: 'رأس السنة الهجرية', note: '1 محرم — بداية السنة الهجرية' },
      'tasua': { name: 'تاسوعاء (9 محرم)', note: 'صم مع عاشوراء (9+10)' },
      'ashura': { name: 'يوم عاشوراء', note: '10 محرم — صيام يكفر السنة الماضية' },
      'karbala': { name: 'كربلاء (61هـ)', note: 'استشهاد الحسين — بتوقير وضبط' },
      'mawlid': { name: 'المولد النبوي', note: '12 ربيع الأول — ادرس السيرة' },
      'miraj': { name: 'ليلة المعراج', note: '27 رجب — رحلة الإسراء؛ عظمها بالصلاة' },
      'miraj-story': { name: 'الإسراء والمعراج', note: 'الرحلة الليلية والمعراج' },
      'barat': { name: 'ليلة البراءة', note: '15 شعبان — عبادة فردية مرجوة' },
      'ramadan-begins': { name: 'بداية رمضان', note: '1 رمضان — يبدأ شهر الصيام (بالرؤية)' },
      'qadr-nights': { name: 'ليلة القدر (الأوتار)', note: '21 و23 و25 و27 و29 — التمس ليلة القدر' },
      'eid-fitr': { name: 'عيد الفطر', note: '1 شوال — تمر وفطرة وصلاة العيد' },
      'six-fasts': { name: 'صيام الست من شوال', note: 'أي 6 أيام من شوال — تعدل سنة صيام' },
      'tarwiyah': { name: 'يوم التروية', note: '8 ذي الحجة — تبدأ المناسك في منى' },
      'arafah': { name: 'يوم عرفة', note: '9 ذي الحجة — الحج؛ وصيام لغير الحاج' },
      'eid-adha': { name: 'عيد الأضحى', note: '10 ذي الحجة — الأضحية بعد الصلاة' },
      'tashriq': { name: 'أيام التشريق', note: '11-13 — الرمي؛ لا صيام' },
    },
  },
};

/** Localized month description (falls back to English). */
export function monthDesc(slug: string, locale: string): string {
  return (MONTH_UI as any)[locale]?.months?.[slug]?.desc ?? (MONTH_UI.en.months[slug]?.desc ?? '');
}
/** Localized month significance note (empty when none). */
export function monthNote(slug: string, locale: string): string {
  return (MONTH_UI as any)[locale]?.months?.[slug]?.note ?? '';
}
/** Localized calendar event (falls back to English). */
export function monthEvent(key: string, locale: string): { name: string; note: string } {
  return (MONTH_UI as any)[locale]?.events?.[key] ?? MONTH_UI.en.events[key] ?? { name: key, note: '' };
}
